### ISSUE TITLE
Use of Webcam for the code

### ISSUE THREAD

**Issue by mash2612** [Smorodov/Multitarget-tracker#100]
Hi, I was wondering if there is a possibility to use this code when the input is from webcam instead of a file path and name. I explored the option and I think if I overload the function Capture and Detect from the class VideoExample in VideoExample.cpp I can achieve something like this. Is my understanding correct? 
I would need to pass '0' as value instead of the path and file name in Capture().

I might be oversimplifying it here. Your feedback would be great!

**Comment by Nuzhny007** [comment]
Hi!
It's simple: https://github.com/Nuzhny007/Multitarget-tracker/blob/master/VideoExample.cpp#L182
We are waiting of merging my pull request.

**Comment by mash2612** [comment]
Thanks! I will try this out :)
