### ISSUE TITLE
Creating the red halo

### ISSUE THREAD

**Issue by mash2612** [Smorodov/Multitarget-tracker#102]
Hi,
I would like to know what functionality implements the red colored halo behind the pedestrians.Thanks again.

**Comment by Nuzhny007** [comment]
Hi!
All colours are set here: https://github.com/Smorodov/Multitarget-tracker/blob/master/VideoExample.cpp#L27
They are used almost randomly, depending of the objects id. Therefore, the red colour does not mean anything special.

**Comment by mash2612** [comment]
Sorry, I guess I did not frame my question properly. I meant how do I create/manipulate the effect of halo(example:increasing the intensity or length of the halo).

Thanks for your quick response.

Cheers.

**Comment by Nuzhny007** [comment]
Ah, I get it.
It's function CalcMotionMap for visualization the raw detections with tracking result: https://github.com/Smorodov/Multitarget-tracker/blob/7cecf196de1867957a39c65796a40289aa070b25/Detector/MotionDetector.cpp#L109
This approach was made by analogy with MotionHistory from OpenCV: https://github.com/opencv/opencv/blob/1c18b1d245a875565c9b9e49ccec901e9b516337/modules/video/include/opencv2/video/tracking_c.h#L119

**Comment by mash2612** [comment]
Thanks again for the quick turnaround :)

I will have a look.
