### ISSUE TITLE
Adding a "Director" trayectory to tracks

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#103]
Based on this paper

https://medusa.fit.vutbr.cz/traffic/data/papers/2014-CESCG-TrafficAnalysis.pdf

from the DataSet you send me to try the difference between raw detections and track boxes.

Could be possible to add another checkto track accurancy based on trayectory of a line
 
For example in a road

![trayectory](https://user-images.githubusercontent.com/17722229/44527867-61e7ba00-a6e8-11e8-8cb1-8a260ed9bb6e.png)

Orange lines are the director trayectory (added by user). Then we have a green tracker trayectory that could be possible, and another red tracker trayectory that could not be possible or not desirable.
Becouse of the thermal image sometimes the background substractor gives random boxes that not follow the director trayectory so with this test maybe it could be possible to avoid false tracks.

**Comment by 88madri** [comment]
Do you mean a vector of cv::Points ??

**Comment by Nuzhny007** [comment]
I think this functionality does not apply directly to the tracker. I propose to design the current tracker as a shared library, and for your task to make a separate test case. I'll try to implement it this evening.

**Comment by Nuzhny007** [comment]
I make new PL: https://github.com/Smorodov/Multitarget-tracker/pull/104
Now project contains 3 folders: shared library with shared tracking library, previous examples that used this library and new cars counting example.
And in the future I will add lines in this new example.
Line is a two corners (cv::Point2f) in relative coordinates from 0 to 1. I can implement method that will check intersection with line. It will be enough?

**Comment by 88madri** [comment]
mmmm.. maybe I don't  explain well. I mean it's ok to have a counting car project . But what I want it that tracks has to follow a certain trayectory to avoid false detection (like image artifacts) that just appear on image and dont have a complete trayectory-

**Comment by Nuzhny007** [comment]
Hi!
I implemented code with line intersection: https://github.com/Smorodov/Multitarget-tracker/pull/105
You can see how it works: https://www.dropbox.com/s/ztd4eyi04bz3z00/counting2.avi?dl=0
And You can implement logic with road marking based on this functionality. It would be enough?

**Comment by 88madri** [comment]
Yeah it's great but thats not the problem i'm refering to. 
Yo can see in this video. You have correct detections of car but then The thermal image changes rapidly and then you have artifacts in the image that can lead to wrong line intersection. That last box does not have a real trayectory just appear and then cross the screen.

https://drive.google.com/file/d/1j5Z5egFY-6kYFUYe7uwwLeDv0X6LOt5n/view?usp=sharing

**Comment by 88madri** [comment]
Also I have seen on your last pull request some changes involved Kalman filter code, is that related to this?
Thanks in advance

**Comment by Nuzhny007** [comment]
>That last box does not have a real trayectory just appear and then cross the screen.
And you can create 2 road lines: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/main.cpp#L44
And check intersection with they: no intersections - valid car. This lines aren't only for cars counting - they can be used for any logic and conditions.

>Also I have seen on your last pull request some changes involved Kalman filter code, is that related to this?
Yes and no. After testing tracker on any videos with different parameters it was founded some bug. They was fixed.
