### ISSUE TITLE
Issue when running make

### ISSUE THREAD

**Issue by ajedillo** [Smorodov/Multitarget-tracker#108]
Hello, Mr. Smorodov! When running make on a Raspbian Stretch, there is an error when building SSDMobileNetDetector.cpp, which I have attached as a screenshot below --
 
![screen](https://user-images.githubusercontent.com/14220093/48067888-637d3600-e19f-11e8-879e-d0c61ab7167e.png)

I installed OpenCV following instructions set [here](https://www.pyimagesearch.com/2017/09/04/raspbian-stretch-install-opencv-3-python-on-your-raspberry-pi/) and am a little lost how to proceed. What do you recommend?

**Comment by ajedillo** [comment]
Also tried setting OpenCV_DIR here - I realized part of my mistake was I set CMAKE_INSTALL_PREFIX my OpenCV install, so I changed that, but still no change.

![screen](https://user-images.githubusercontent.com/14220093/48068344-8fe58200-e1a0-11e8-9a79-803e2bed7544.png)

**Comment by Nuzhny007** [comment]
Hi!
Whats about OpenCV version?

**Comment by ajedillo** [comment]
Hello! Apologies for the long delay in response. With your input I was finally able to figure out the issue. I had installed an earlier version of OpenCV. I removed it and installed OpenCV4 and it works like a charm. Thanks for your time!

**Comment by ajedillo** [comment]
Quick question - after running make it built libmtracking.so with no issues. What am I supposed to do with the .so file? Sorry, I'm not terribly familiar with c/c++.

**Comment by Nuzhny007** [comment]
Hi!
It looks strange: it will be created two modules:
1. MultitargetTracker: https://github.com/Smorodov/Multitarget-tracker/tree/master/example
2. CarsCounting: https://github.com/Smorodov/Multitarget-tracker/tree/master/cars_counting

Check pls yours building output.

**Comment by Nuzhny007** [comment]
Hi!
In opencv 3.3 was used experimental version of cv::dnn module. You can:
1. *Better* Using OpenCV 4.0
2. Remove last bool parameter from call blobFromImage in SSDMobileNetDetector::DetectInCrop.

**Comment by yiboliu31** [comment]
Thanks for your reply.I have fixed the errors last night.
When I run the code with "./MultitargetTracker ../data/test7.avi -e=4 -g=1 -o=../data/save.avi" using my own MobileNet-ssd model,there was a strange phenomenon,like this:
![screenshot from 2018-12-11 11-24-46](https://user-images.githubusercontent.com/32137970/49776672-ed3c9800-fd37-11e8-892e-dd0a498455d4.png)
there are many wrong track objects

**Comment by Nuzhny007** [comment]
Strange - red halos? They shows raw detections. You can comment this line (CalcMotionMap) in code: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L436

About wrong detections - it's all to the detector. You can set higher threshold: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L375
For example 0.7

**Comment by yiboliu31** [comment]
The odd thing is, the four boxes on the right of the picture look like translating from the two boxes on the left of the picture. @Nuzhny007

**Comment by Nuzhny007** [comment]
Oh, right. Can you show a bit more video - how did they come about?

**Comment by yiboliu31** [comment]
![x](https://user-images.githubusercontent.com/32137970/49793324-ea5d9980-fd6f-11e8-92e2-8a4101039a41.gif)

**Comment by Nuzhny007** [comment]
Mmm... I think that this bug with crop size.
1. What's about input NN size? In my example was used MobileNetSSD with input size 300x300 pixels. And your NN?
2. Change, plz, this constant: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L376
For example: config["maxCropRatio"] = "5.0"
