### ISSUE TITLE
problems about win+cmake

### ISSUE THREAD

**Issue by JINXvvv** [Smorodov/Multitarget-tracker#109]
I have generated a solution file(.sln) by cmake and opened it by VS.
When I run the code, the run interface shows the following words：

Examples of the Multitarget tracking algorithm
Usage:
          ./MultitargetTracker <path to movie file> [--example]=<number of example 0..5> [--start_frame]=<start a video from this position> [--end_frame]=<play a video to this position> [--end_delay]=<delay in milliseconds after video ending> [--out]=<name of result video file> [--show_logs]=<show logs>

Press:
'm' key for change mode: play|pause. When video is paused you can press any key for get next frame.

Press Esc to exit from video

OpenCL not used
[ INFO:0] VIDEOIO: Enabled backends(6, sorted by priority): FFMPEG(1000); MSMF(990); DSHOW(980); VFW(970); CV_IMAGES(960); CV_MJPEG(950)
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:856)
warning: ../data/atrium.avi (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:857)
Can't open ../data/atrium.avi

Because I run it in windows,so I am confused how to add parameters to my command.
Thank you for your help!

**Comment by Nuzhny007** [comment]
Hi!
You can right mouse click on project properties in VS and in opened dialog: "Congiguration properties" -> "Debugging", "Command arguments". For example: https://i.stack.imgur.com/eMjKA.jpg

**Comment by yuyanguo2018** [comment]
> Hi!
> You can right mouse click on project properties in VS and in opened dialog: "Congiguration properties" -> "Debugging", "Command arguments". For example: https://i.stack.imgur.com/eMjKA.jpg

hello,i have the same problem,and had see your reply,but what to write in the filer.txt file?
thank you for your help!

**Comment by yuyanguo2018** [comment]
![image](https://user-images.githubusercontent.com/39588867/49057699-aa5cc980-f23b-11e8-9310-30cff416adb9.png)
 
here is the problem photo.

**Comment by JINXvvv** [comment]
> ![image](https://user-images.githubusercontent.com/39588867/49057699-aa5cc980-f23b-11e8-9310-30cff416adb9.png)
> 
> here is the problem photo.

你把视频路径换成绝对路径试一下，我之前写的相对路径也是打不开

**Comment by yuyanguo2018** [comment]
> > ![image](https://user-images.githubusercontent.com/39588867/49057699-aa5cc980-f23b-11e8-9310-30cff416adb9.png)
> > here is the problem photo.
> 
> 你把视频路径换成绝对路径试一下，我之前写的相对路径也是打不开

谢谢！终于正常运行了

**Comment by Nuzhny007** [comment]
Use full path to the video. In Readme I write linux-style paths

**Comment by chunniunai220ml** [comment]
> > Hi!
> > You can right mouse click on project properties in VS and in opened dialog: "Congiguration properties" -> "Debugging", "Command arguments". For example: https://i.stack.imgur.com/eMjKA.jpg
> 
> hello,i have the same problem,and had see your reply,but what to write in the filer.txt file?
> thank you for your help!



> > > ![image](https://user-images.githubusercontent.com/39588867/49057699-aa5cc980-f23b-11e8-9310-30cff416adb9.png)
> > > here is the problem photo.
> > 
> > 
> > 你把视频路径换成绝对路径试一下，我之前写的相对路径也是打不开
> 
> 谢谢！终于正常运行了
可以告诉一下我你是怎么跑通的吗？ 我生成.sln后，在vs2015debugs时，也有问题，生不成.exe
