### ISSUE TITLE
problems about  function VideoExample::Detection

### ISSUE THREAD

**Issue by JINXvvv** [Smorodov/Multitarget-tracker#110]
I just want to use the function  VideoExample::Detection to detect objects for one frame by ssd.
And I add this function in a cycle in which each frame of the video is read by function VideoCapture.

I also add the code as follows:
SSDMobileNetExample dnn_detector;
Mat frame_mat;
capture >> frame_mat;
cv::UMat grayFrame1;
regions_t regions;
dnn_detector.Detection(frame_mat, grayFrame1, regions);

But the error shows that m_detector in the function detection is empty.
Could you please tell me why?
Thank you.

**Comment by Nuzhny007** [comment]
Hi!
It's an example with SSD: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L372
For SSDMobileNetExample it need to call initialization method with paths to the models.
