### ISSUE TITLE
yolo v3

### ISSUE THREAD

**Issue by JINXvvv** [Smorodov/Multitarget-tracker#113]
If I want to use yolo v3 with GPU , do I need to tick the WITH_CUDA option when compiling opencv?
If I compile opencv without WITH_CUDA , can I use GPU to run the code?

**Comment by Nuzhny007** [comment]
Hi!
OpenCV can't now to use CUDA for dnn. The fastest YOLO in OpenCV can compile with OpenVINO as inference engine.
For YOLO with CUDA you need compile darknet and made a custom detector: https://github.com/pjreddie/darknet

**Comment by Nuzhny007** [comment]
Completed: https://github.com/Smorodov/Multitarget-tracker/pull/117
