### ISSUE TITLE
use cmake to compile the code

### ISSUE THREAD

**Issue by JINXvvv** [Smorodov/Multitarget-tracker#115]
I have used cmake to compile the code successfully.
But when I open MTTracking.sln by VS2015 and rebuild solution ,there is an error:
can't open file '..\build\Debug\mtracking.lib'
And the folder  ..\build\Debug\  is empty.
It seems like something wrong when MTTracking.sln is rebuilding 
Could you please tell me why?

**Comment by Nuzhny007** [comment]
Hi!
1. Where is you binaries dir in cmake?
2. May be it was more errors in compilation process? Can you send full build log?
