### ISSUE TITLE
Can not regenerate the solution

### ISSUE THREAD

**Issue by vba34520** [Smorodov/Multitarget-tracker#118]
Firstly, thank you for your sharing!
Here is the question.

I use CMake to configure and generate your project direly like this.
![snipaste_2019-01-08_14-46-13](https://user-images.githubusercontent.com/40198281/50814015-28d87b00-1353-11e9-9f57-45798be05ba2.png)

Then I regenerate the solution. But it reported errors like this.
It said that it can't find the opencv2/dnn/shape_utils.hpp.
![snipaste_2019-01-08_14-52-09](https://user-images.githubusercontent.com/40198281/50814264-0eeb6800-1354-11e9-9b17-9d2108f50cd9.png)

The "newbuild folder" that built by opencv3.1 and opencv_contrib3.1 has not the "shape_utils.hpp". I don't know how to figure it out.
![snipaste_2019-01-08_14-54-41](https://user-images.githubusercontent.com/40198281/50814463-be283f00-1354-11e9-9569-6924050cbf88.png)

Looking forward to your reply! Thank you so much.

**Comment by Nuzhny007** [comment]
Hi!
OpenCV 3.1 is too ild and do not recommeds for opencv_dnn module. Do you can use OpenCV 3.4 or 4.0?

**Comment by vba34520** [comment]
> Hi!
> OpenCV 3.1 is too ild and do not recommeds for opencv_dnn module. Do you can use OpenCV 3.4 or 4.0?

Thank you very much for your reply! 
I found that 3.1 does't has this file. I'm trying to install 3.4.5 now!
Best wishes.
