### ISSUE TITLE
Can not open file mtracking.lib

### ISSUE THREAD

**Issue by vba34520** [Smorodov/Multitarget-tracker#119]
- OpenCV => :3.4.0
- Operating System / Platform => :Win10 64bit
- Compiler => :Visual Studio 2017

I uninstalled the VS2013 yesterday and install the VS2017 and OpenCV3.4.0 and OpenCV_contrib today.
I can run the test project successfully like this.
![snipaste_2019-01-09_15-16-06](https://user-images.githubusercontent.com/40198281/50883441-0877f180-1423-11e9-923a-1f5cda2df60f.png)

I used CMake configure and generate this project like this.
![snipaste_2019-01-09_15-45-25](https://user-images.githubusercontent.com/40198281/50883988-9f917900-1424-11e9-8ad8-b213b20fd0e3.png)

When I regenerate the solution, it said that it can not open the file "..\Debug\mtracking.lib" like this.
![snipaste_2019-01-09_15-30-43](https://user-images.githubusercontent.com/40198281/50883492-32c9af00-1423-11e9-8234-5cd02c960dac.png)

Thank you very much for your help!

**Comment by Nuzhny007** [comment]
Hi!
It's my bad. You can comment this block: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/Tracker/track.cpp#L553
Or you can put around it condition:
#if (CV_VERSION_MAJOR >= 4)
...
#end

**Comment by vba34520** [comment]
> Hi!
> It's my bad. You can comment this block: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/Tracker/track.cpp#L553
> Or you can put around it condition:
> #if (CV_VERSION_MAJOR >= 4)
> ...
> #end

Sorry, I don't know what exactly you mean.
I opened this page and found it's a file.
Then I compared it with mine and found they are same.

I don't know where to put the"#if xxx" and "#end" around, could you please told me ?

Thank you!

**Comment by Nuzhny007** [comment]
I'm now from phone.
You can comment or delete rows 553-557 from track.cpp. This tracker absent i. OpenCV 3.4. I will fix it later.

**Comment by Nuzhny007** [comment]
Do you can close their issues if the problem was solved?

**Comment by vba34520** [comment]
Certainly, thank you again!
I'm a newcomer of Github, Sorry that.
Good luck with your work.
