### ISSUE TITLE
CMake Warning.

### ISSUE THREAD

**Issue by Surakshaajith** [Smorodov/Multitarget-tracker#12]
I'm trying to build Multitarget-tracker using CMake. Initially i had the warning below,

> You should manually point CMake variable OpenCV_DIR to your build of OpenCV library.
> Call Stack (most recent call first):
>   CMakeLists.txt:57 (find_package)

I manually pointed out the directory of build version of OpenCV library and tried to **build**.

**Warning:**
> CMake Warning at CMakeLists.txt:23 (FIND_PACKAGE):
>   Found package configuration file:
>     C:/OpenCV/opencv/build/x86/vc12/lib/OpenCVConfig.cmake
>   but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
>   NOT FOUND.

I checked the OpenCV_FOUND, but after i press 'configure' again, it automatically unchecks.

**Comment by Smorodov** [comment]
There are two such checkboxes, check also in "ungroupped".
