### ISSUE TITLE
Code link problem

### ISSUE THREAD

**Issue by Tracking2** [Smorodov/Multitarget-tracker#121]
Hi
       Cmake can be compiled, but there is a link error when making，How can I solve this problem?

![image](https://user-images.githubusercontent.com/35992535/50955737-de8eff80-14f4-11e9-8b95-74829667df18.png)

**Comment by Nuzhny007** [comment]
Hi!
All errors are related to opencv_contrib modules. Did you build OpenCV with opencv_contrib?
And what's the OpenCV version? Can you share CMakeCache.txt?

**Comment by Tracking2** [comment]
Thank you for your reply！
I use openCV3.4 and I don't know whether it is compiled opencv_contrib. 

[CMakeCache.txt](https://github.com/Smorodov/Multitarget-tracker/files/2745118/CMakeCache.txt)

**Comment by Nuzhny007** [comment]
Your OpenCV compiled without opencv_contrib modules, in CMakeCache.txt:
> mtracking_LIB_DEPENDS:STATIC=general;opencv_calib3d;general;opencv_core;general;opencv_dnn;general;opencv_features2d;general;opencv_flann;general;opencv_gapi;general;opencv_highgui;general;opencv_imgcodecs;general;opencv_imgproc;general;opencv_ml;general;opencv_objdetect;general;opencv_photo;general;opencv_stitching;general;opencv_video;general;opencv_videoio;

In this case some variables must be disabled:
_//Should use the bgfg algorithms from opencv_contrib?
USE_OCV_BGFG:BOOL=OFF
//Should use the KCF tracker from opencv_contrib for collisions resolving?
USE_OCV_KCF:BOOL=OFF
//Should use the Unscented Kalman Filterr from opencv_contrib?
USE_OCV_UKF:BOOL=OFF_

**Comment by Tracking2** [comment]
Thank you!
when I disable the variables, I can compile the code and run.  But I found that already contains opencv_contrib modules in my opencv lib. How can I call opencv_contrib modules when cmake？

![image](https://user-images.githubusercontent.com/35992535/51010371-fe730180-158e-11e9-91d1-fcb1842f9ab9.png)

![image](https://user-images.githubusercontent.com/35992535/51010618-126b3300-1590-11e9-849a-bb11db9c4945.png)

**Comment by Nuzhny007** [comment]
See you on picture: contrib modules have 3.4.1 version bun main opencv modules 4.0. I recommend delete old files, update contrib and rebuild OpenCV 4.0 with contrib.

**Comment by chensteven** [comment]
Can somebody explain how to compile and link the source code? I'm having troubling making.
