### ISSUE TITLE
Frame capture timeout

### ISSUE THREAD

**Issue by Oreobird** [Smorodov/Multitarget-tracker#124]
I use yolov3-tiny for detector, but it always show: 
```
Frame 1259: tracks = 1, time = 141
Frame 1260: tracks = 1, time = 140
Frame 1261: tracks = 1, time = 162
Process: Frame capture timeout
```
It seems a dead lock problem and I am digging in it.

**Comment by Nuzhny007** [comment]
Hi!
Probably it is a real deadlock. Can you give me advanced information about your case?
OS, hardware (cores of the CPU), CPU or GPU for inference... Sadly I can't repeat this bug.

**Comment by Oreobird** [comment]
- Linux dev-ai 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz

- 4 cores

- CPU for inference

In my case, I comment out the GUI part like imshow and namedwindow function call in VideoExample.cpp, but I do not think that it's the root cause.

**Comment by Nuzhny007** [comment]
Thanks!
I try to fix it: https://github.com/Nuzhny007/Multitarget-tracker/commit/f19fa5c0a6dd118a1ca8466c7181469fe0c688c5

**Comment by Nuzhny007** [comment]
My PL was merged. Do you can test it?
