### ISSUE TITLE
Building the project on Mac

### ISSUE THREAD

**Issue by chensteven** [Smorodov/Multitarget-tracker#126]
What are the steps to building the project on a macOS? I've installed OpenCV 3 and OpenCV-contrib from source already. Here's my error:

<img width="1571" alt="screen shot 2019-03-06 at 2 32 08 pm" src="https://user-images.githubusercontent.com/1616844/53908114-adc2d680-401c-11e9-972e-d0f10f88bdaa.png">

**Comment by Nuzhny007** [comment]
I have not compile on macOS. Try to write: #include <opencv2/objdetect.hpp> on top of the PedestrianDetector.h
