### ISSUE TITLE
cmake error:bgsegm.hpp

### ISSUE THREAD

**Issue by eunmipark1** [Smorodov/Multitarget-tracker#129]
hi
I want to build without an opencv-contrib.
So I 'OFF' three options. (USE_OCV_KCF, USE_OCV_BGFG, USE_OCV_UKF)
However, there is an error saying that 'opencv2 / bgsegm.hpp' is missing.
Below is a revision I tried.

1. CMakeList.txt 
...
set(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR})
set("OpenCV_DIR" "C:/cv-3.2.0/opencv/build/x64/vc14/lib")

option(USE_OCV_KCF "" OFF)
option(USE_OCV_BGFG "" OFF)
option(USE_OCV_UKF "" OFF)

FIND_PACKAGE(OpenCV REQUIRED)
...

2. Add options when make
cmake -DUSE_OCV_BGFG=OFF -DUSE_OCV_KCF=OFF -DUSE_OCV_UKF=OFF .

But when you make it, the following message keeps appearing.
-- Found OpenCV: C:/cv-3.2.0/opencv/build (found version "3.2.0")
-- Looking for C++ include opencv2/bgsegm.hpp
-- Looking for C++ include opencv2/bgsegm.hpp - not found

I keep trying many times with delete 'cmakeCache' 
but I get an error that there is no 'bgsegm.hpp'.

Is there a right way to turn off options?
thanks for your great work.

**Comment by Nuzhny007** [comment]
Hi!
Thanx for your feedback. This error is strange that we are building this project on travis without opencv_contrib. And build status is OK.
But I added code with disabling this options when they are disabled in CMake: https://github.com/Smorodov/Multitarget-tracker/pull/130/commits/8f58f494f5d174236983d1c2e568e571fcb939d1
Try please:
1. git pull
2. make
