### ISSUE TITLE
Tracking with learning

### ISSUE THREAD

**Issue by Surakshaajith** [Smorodov/Multitarget-tracker#13]
My Goal is to have real-time MultiTracker with Learning.<Br>I used Kalman filter to track an object but i found errors in the estimation while tracking. <br>
The object was not been tracked continuously. I want to implement some learning mechanism along with Tracking.<Br>
 One way i thought of doing this is,<Br>
1) calculate the average HSV of a particular roi then store that HSV value in a vector(`Scalar` or `Vec3b`)<br>
2) Compare the new HSV value (average from some ROI) with all previous HSV values present in vector collection. <br>
3) If the new HSV value did not match with the *HSV values in vector* then track this as a new separate object.<br>
4) else if the new roi matched *HSV values in vector*, then it is said to be the same object present in the roi. continue tracking old object. <br>
5) Have some regular time based checking to remove old *HSV values in vector*.<Br>

I tried KCF, MIL e.t.c they are not realtime. can you recommend any realtime learning mecahnism or ways to improve above proposed one.

**Comment by Nuzhny007** [comment]
Hi!
You can try tu use Lucas-Canade optical flow for tracking point on object. It will be better that HSV value and faster than KCF and MIL.

**Comment by seovchinnikov** [comment]
Also please  take a look at https://github.com/nwojke/deep_sort
and based on it
https://github.com/bendidi/Tracking-with-darkflow/

**Comment by Nuzhny007** [comment]
Thanks!
Very interesting projects. I think that it can use this approach and implement it with opencv_dnn on C++ only. Or may be you want to do it?

**Comment by Nuzhny007** [comment]
Yes. But now I don't have any time. It's my hobby project.
May be do you want to do it?
