### ISSUE TITLE
When I extract the tracker from your code to run independently，I find  the tracker doesn't work,the output the targets‘ position is Invariable

### ISSUE THREAD

**Issue by a77514860** [Smorodov/Multitarget-tracker#131]
Hi，
Am I right in coding this way?
![image](https://user-images.githubusercontent.com/41535150/54905424-f125ac00-4f1b-11e9-93aa-9d75ef600273.png)
![image](https://user-images.githubusercontent.com/41535150/54905338-c176a400-4f1b-11e9-9f00-0941dcf9d3c5.png)
![image](https://user-images.githubusercontent.com/41535150/54905781-c720b980-4f1c-11e9-8920-39bf5a5b8adb.png)
and I don't know how to Initialize the first frame.

**Comment by Nuzhny007** [comment]
Hi!
After selectROIs call: 
`std::for_each(rois.begin(), rois.end(), [&](cv::Rect rect) { regions.emplace_back(rect); });`
And after m_tracker->Update(...) call:
`regions.clear();
for (const auto& track : m_tracker->tracks)
    {
            cv::rectangle(frame, track->GetLastRect(), cv::Scalar(0, 255, 0), 1, cv::LINE_AA);
    }`
