### ISSUE TITLE
How to use the staple tracker for tracking multiple objects?

### ISSUE THREAD

**Issue by xdg2016** [Smorodov/Multitarget-tracker#133]
Hello sir, I saw your code, it's amasing. I want to use the staple tracker to track multiple objects,such as cars and people.Can you tell me how to modify? thanks!

**Comment by Nuzhny007** [comment]
Hi!
This is simple - in TrackerSettings set the m_lostTrackType as tracking::TrackSTAPLE. For example here instead TrackKCF: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L293
