### ISSUE TITLE
About arm processor.

### ISSUE THREAD

**Issue by dibet** [Smorodov/Multitarget-tracker#136]
Hi, i would like know if you has compiled your code in arm processor like odroid.
I have problem with 
 staple/sse.hpp:8:64: fatal error: emmintrin.h: No such file or directory
Thanks.

**Comment by Nuzhny007** [comment]
Hi!
This is bug:  the STAPLE tracker can work only with x86 processors. Now it will be disabled on ARM: https://github.com/Smorodov/Multitarget-tracker/pull/137
Check, plz, the new version

**Comment by isra60** [comment]
Also it should check for aarch64 architectures for example the tegra TX2

**Comment by Nuzhny007** [comment]
Fixed: https://github.com/Smorodov/Multitarget-tracker/pull/138

**Comment by dibet** [comment]
Wow. i will check it. Thanks. Can i make a suggestion? I don't know if you take it in consideration.

Do you can include an abstract class that implement some methods like :

virtual void startNewTrack( int trackerid, const cv::UMat & region, const cv::UMat & currentImage  ) = 0; //when we detect new object for tracking....
virtual void finishTrack( int trackerid ) = 0; //when the object leave the scene.....
virtual void detectionObjectTracked( int trackerid, const cv::UMat & region, const cv::UMat & currentImage ) = 0; // when an object is detected and tracked.

These methods can be append as public in the CTracker class.

Thanks for your wonderfull work.
Dibet

**Comment by Nuzhny007** [comment]
Hi!
Yes, I can add this methods.
Now I'm working on this task: https://github.com/Smorodov/Multitarget-tracker/issues/135
For it will be a little changed interface by CTracker (for correct multithreading work): https://github.com/Nuzhny007/Multitarget-tracker/blob/slow_detect/src/Tracker/Ctracker.h#L105
After that I'll add new methods. I hope that it will be easier to work.

**Comment by dibet** [comment]
I have the same problem #135 . I make an image queue and use the virtual functions previously mentioned. On each detection i append the image to the queue and when the tracker was lossed, i process all the de detections (ex gender classification, age regression, ....).

**Comment by isra60** [comment]
But maybe I don't explain well on #135. My app runs in real time, so I don't want a queue of Detections.
I want to discard every 1 frames of two for example. But I want the kalman tracker to give me the updated detections every frame.

**Comment by Nuzhny007** [comment]
It will be just example and no part of the CTracker API. And it will be faster than now.

0. The detector is very slow, 1-2 fps or T = 500-1000 ms on frame.

1. It used 3 threads:
1.1. Main thread for video decoding and cv::imshow
1.2. Thread for Detector
1.3. Thread for Tracker

2. The Main thread decodes frames and push into FramesQue.

3. In second thread Detector get frame from FramesQue and run recognition every T ms or 1th, 12th, 24th frame...

4. In third thread Tracker get each frame and tracks all detected objects.

5. The Main thread get frames with tracking result and shows it.

**Comment by Nuzhny007** [comment]
Now detector works on each frame in VideoExample. But it used 2 threads for a little parallelization.

**Comment by isra60** [comment]
But this part..
4 . In third thread Tracker get each frame and tracks all detected objects. 

How will the tracker get updated without new detections? For example it will assume kalman prediction to follow the trayectory of a Track?? Or this tracker will depend on KCF Track??

**Comment by Nuzhny007** [comment]
Now first version is completed: https://github.com/Smorodov/Multitarget-tracker/pull/140
And yes -  it works fine with visual tracking (KCF, CSRT or STAPLE).
