### ISSUE TITLE
Result is bad

### ISSUE THREAD

**Issue by jinfagang** [Smorodov/Multitarget-tracker#143]
using ssd mobilenet:

![image](https://user-images.githubusercontent.com/21303438/57697445-d05d1580-7685-11e9-8929-549d0f82636a.png)

**Comment by jinfagang** [comment]
Not good at all

**Comment by Nuzhny007** [comment]
Hi!
Do you can share this video for testing?

**Comment by jinfagang** [comment]
@Nuzhny007  thanks for you reply, it's just a MOT video, I share a link tomorrow
