### ISSUE TITLE
Problem with cmake : bgsegm.hpp not found 

### ISSUE THREAD

**Issue by germal** [Smorodov/Multitarget-tracker#144]
Hi , 

I have installed opencv_contrib 4.0 on Ubuntu 18 but cmake cannot found the opencv2/bgsegm.hpp.
I tried to link the file in different locations but without success.Please where cmake try to search this file ?
Thanks a lot
Germal

![image](https://user-images.githubusercontent.com/47027729/57878770-0f709f80-781b-11e9-987f-f1ebb1e97136.png)

**Comment by ilyas95** [comment]
I have the same problem

**Comment by Nuzhny007** [comment]
Hi!
This code makes check: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/CMakeLists.txt#L174

And if OpenCV was compiled with opencv_contrib and OpenCV_DIR=<correct path to OpenCV  build directory> then check_include_file_cxx returns TRUE.
You can set manually USE_OCV_BGFG=ON, USE_OCV_KCF=ON and USE_OCV_UKF=ON.
If all includes are correct than Multitarget-tracker will be compiled.

**Comment by germal** [comment]
Thank you @Nuzhny007 !!! It works perfectly
Best Regards,
germal
