### ISSUE TITLE
How do i use my own trained weight and cfg file?

### ISSUE THREAD

**Issue by MrBob5566** [Smorodov/Multitarget-tracker#149]
I had used darknet to train my own weight file and cfg file , and how do I use this files in this program and used it to track my trained items.

I know author put the weight and cfg in the  "data" folder , but when I replace them , video can't detect anying.

Please help!!!

**Comment by Nuzhny007** [comment]
Hi!
Do you use YoloDarknetExample or YoloExample? YoloDarknetExample uses darknet as backend and YoloExample uses opencv_dnn. Yours network doesn't work with both examples?
The path to the model you can set here for YoloExample: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L552
Or here for YoloDarknetExample: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L671
