### ISSUE TITLE
bool Init Tracker this nullptr

### ISSUE THREAD

**Issue by Yooyi0401** [Smorodov/Multitarget-tracker#150]
When i build new version, i have this problem in my case. 
get the errors:

      bool Tracker::init 
      if( isInit )
      {
         return false;
      }
      (it will return false)this nullptr

According the image, I think that the "image"(or frame) maybe the reason. How can i solve this problem ?  Could you please tell me why ? Thanks a lot.

![擷取](https://user-images.githubusercontent.com/49556328/61997836-434d2880-b0da-11e9-91f8-ea54119d1056.PNG)

**Comment by Nuzhny007** [comment]
Hi!
See on watch window: this == 0. It seems that you used not initialized or deleted object. And I need more context  for find error.

**Comment by Yooyi0401** [comment]
Environment Opencv 3.4.6, CUDA 10.0
When I change track method, I solve the problem. Change CSRT to KCF. 
But I don't understand the reason. Is that Opencv 3.4.6 doesn't support this method?

![image](https://user-images.githubusercontent.com/49556328/62002690-16316200-b13c-11e9-82c4-1ece579f0dd8.png)

And another question how to build in Linux? I already cmake the project and I make it. But there is a problem that the main can't link the header file (error : #include "xxxx.h").
I have tried a stupid method that get the header file which i need to the same file, but it isn't work either. Sorry I am Rookie in linux. Really Thank you  for your help.
![91055](https://user-images.githubusercontent.com/49556328/62002755-dc615b00-b13d-11e9-9159-15f021f719d9.jpg)

![91054](https://user-images.githubusercontent.com/49556328/62002752-cf446c00-b13d-11e9-90c8-58fa123d4378.jpg)

**Comment by Nuzhny007** [comment]
Hi!
To make on linux: https://github.com/Smorodov/Multitarget-tracker#build
Or short:

> mkdir build
> cd build
> cmake . ../ -DCMAKE_BUILD_TYPE=Release
> make -j4

**Comment by Yooyi0401** [comment]
Thanks a lot. I finally built it successfully on Linux. Because of a lot little problem (like opencv has some error etc.), I reply slowly. I rebuild it again and again, and also opencv. And then, I will try to solve the remaining problems. Attach a successful picture.
![S__27590665](https://user-images.githubusercontent.com/49556328/62415163-e4e2f580-b657-11e9-97fa-8463f80f052a.jpg)

**Comment by Nuzhny007** [comment]
Hm, segmentation fault. Do you can build project (and OpenCV) in Debug mode to search for error?

**Comment by Nuzhny007** [comment]
Hi!
It was maked a couple of changes in pipeline and YOLO detector. Do you can to check test again? Thank you.
