### ISSUE TITLE
Hungarian algorithm question

### ISSUE THREAD

**Issue by zieitokk** [Smorodov/Multitarget-tracker#155]
Hi. Recently I want to write a unit test for your hungarian algorithm. 

However, when I set `distMatrix` into `const std::vector<float> distMatrix = {10, 19, 8, 15, 10, 18, 7, 17, 13, 16, 9, 14, 12, 19, 8, 18, 14, 17, 10, 19};` and set the row=5, column=4, it outputs the total cost as 33, which is wrong. 

Besides, when I set the row=4 and column=5 with the exact same distMatrix, program stuck at somewhere.

**Comment by Nuzhny007** [comment]
Hi!
Test is a great idea. Do you can share it? I will add it to the project and fix errors.

**Comment by zieitokk** [comment]
I just add the following code below the hungarian algorithm cpp file
```
// unit test
int main(int argc, char** argv)
{
    const std::vector<float> distMatrix = {10, 19, 8, 15, 10, 18, 7, 17, 13, 16, 9, 14, 12, 19, 8, 18, 14, 17, 10, 19};
    std::vector<int> assignment;
    float cost;
    AssignmentProblemSolver::TMethod method = AssignmentProblemSolver::TMethod::optimal;
    AssignmentProblemSolver Solver;
    cost = Solver.Solver(distMatrix, 4, 5, assignment, method);    
    printf("the cost is: %f\n", cost);
    return 0;
}

**Comment by zieitokk** [comment]
Hi.
I have test the `without_forbidden_assignments` method, and it outputs the right answer.
And I'm sorry that I mistakenly put the wrong sequence for distMatrix. 

There is no wrong output issue. And the program stuck issue may come from the multi to one issue.
So when I change the TMethod into `without_forbidden_assignments`, stuck issue disappeared.
