### ISSUE TITLE
kcf

### ISSUE THREAD

**Issue by Allesgute1** [Smorodov/Multitarget-tracker#164]
hello, I miss a problem:
KCF tracker was disabled in CMAKE! Set lostTrackType = TrackNone in constructor.
Have you ever meet it?
Thank you!

**Comment by Nuzhny007** [comment]
Hi!
It need to install opencv_contrib and in CMake enable USE_OCV_KCF=ON

**Comment by Chetanbansiwal** [comment]
The CMakeLists.txt:183 is trying to find opencv2/bgsegm.hpp . However, in case of Opencv 4.1.2 this file directly goes to /usr/local/include/opencv4/openc2/bgsegm.hpp when opencv is installed with opencv_contrib and never comes to OpenCV_DIR/opencv2 folder or OpenCV_DIR/include folder.
The OpenCV_DIR is set to the "build" folder of opencv. opencv_contrib was also installed while "make" was run for opencv.
can you suggest changes to the CMakeLists.txt file?
I am using Opencv master branch(4.1.2-dev) with opencv_contrib master branch

**Comment by Chetanbansiwal** [comment]
For now, I've just deleted the whole "if" block and simply put option ON for all 3. But it may be better to check something else in "if" condition in future.

**Comment by Nuzhny007** [comment]
I make OpenCV + contrib and don't install it. After than:
cmake . .. -DCMAKE_BUILD_TYPE=Relase -DOpenCV_DIR=/path/to/opencv/build -DUSE_OCV_KCF=ON

And it works!
