### ISSUE TITLE
Question about Confidence and Type of CRegion from DeepLearning based detectors.

### ISSUE THREAD

**Issue by isra60** [Smorodov/Multitarget-tracker#167]
Hi. I'm working with Darknet based detector. So this detector gives the confidence and type of the track.

So it could be possible to add something like a mean to confidence?? in order to get rid of bad detection frames and get a more stable confidence value?

And also I found that the code check for type

```
if (m_tracks[i]->CheckType(regions[j].m_type))
{
}
```
But for example  with a Truck the detector could give you in some frames a car instead of a Truck, so that detection will get discarted???

Thanks in advanced.

**Comment by Nuzhny007** [comment]
Hi!
Do you want to add confidence to the distance between tracks and detections (== regions)? I can do it. How can it works?
1. dist *= m_confidence;
2. dist = alpha * dist + (1 - alpha) * m_confidence;
3. Something else?

About types. It is problem: car and truck, person and motorbike... If we will have a confusion matrix then it will be possible to check the nearest types. I can add confusion matrix with default value as identity matrix. And you can set other values:

```
            | car  | truck | person
car       |   0.8 |   0.2 | 0
truck    |   0.1 |   0.9 | 0
person |    0   |     0  | 1
```
And non zero values can be interpret as matching types. What do you think about it?

**Comment by isra60** [comment]
Sorry for the delay, here in Spain we were on bank holidays.

I like the idea of confusion matrix checking the nearest types.

About deep learning confidence I only think about getting the real time mean confidence of all values. But it could be a good addition to ponderate with the distance.

**Comment by Nuzhny007** [comment]
Here: https://github.com/Smorodov/Multitarget-tracker/pull/168
Without confusion matrix, you can create list of the near types:

```
settings.AddNearTypes("car", "bus", false);
settings.AddNearTypes("car", "truck", false);
settings.AddNearTypes("person", "bicycle", true);
settings.AddNearTypes("person", "motorbike", true);
```
It's  ok?

And about confidence. Now you can set threshold: config.emplace("confidenceThreshold", "0.1");
And check latest confidence for example in DrawData: track.m_confidence.
Do you want to add confidence to distance? Now I'm not sure than it will be good.
Anything else?
