### ISSUE TITLE
Compilation error in LDES Tracker

### ISSUE THREAD

**Issue by ijarraki** [Smorodov/Multitarget-tracker#169]
commit 61680a8ef07ee286300d04a6fca98328a442a55b:

mkdir build
cd build
cmake -DUSE_OCV_KCF=ON ../
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable exact version "10.0") 
-- Found OpenCV: /usr/local (found version "4.2.0") 
-- Looking for C++ include opencv2/bgsegm.hpp
-- Looking for C++ include opencv2/bgsegm.hpp - found
-- Configuring done
-- Generating done
-- Build files have been written to: /path/Multitarget-tracker/build
make -j4
Scanning dependencies of target mtracking
[  6%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/BackgroundSubtract.cpp.o
[  6%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/vibe_src/vibe.cpp.o
[  6%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/BaseDetector.cpp.o
[  6%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/MotionDetector.cpp.o
[  8%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/Subsense/BackgroundSubtractorLBSP.cpp.o
[  9%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/Subsense/BackgroundSubtractorLOBSTER.cpp.o
[ 11%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/Subsense/BackgroundSubtractorSuBSENSE.cpp.o
[ 13%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/Subsense/LBSP.cpp.o
[ 14%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/FaceDetector.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/PedestrianDetector.cpp.o
[ 18%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/pedestrians/c4-pedestrian-detector.cpp.o
[ 19%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/SSDMobileNetDetector.cpp.o
[ 21%] Building CXX object src/CMakeFiles/mtracking.dir/Detector/YoloDetector.cpp.o
[ 22%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/Ctracker.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/track.cpp.o
[ 26%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/HungarianAlg/HungarianAlg.cpp.o
[ 27%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/Kalman.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/dat/dat_tracker.cpp.o
[ 31%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/staple/fhog.cpp.o
[ 32%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/staple/staple_tracker.cpp.o
/path/Multitarget-tracker/src/Tracker/dat/dat_tracker.cpp: In member function ‘virtual cv::RotatedRect DAT_TRACKER::Update(const cv::Mat&, float&)’:
/path/Multitarget-tracker/src/Tracker/dat/dat_tracker.cpp:175:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (i != best_candidate) {
                 ~~^~~~~~~~~~~~~~~~~
/path/Multitarget-tracker/src/Tracker/dat/dat_tracker.cpp:192:87: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             cv::rectangle(pm_search_color, hypotheses[i], cv::Scalar(0, 255, 255 * (i != best_candidate)), 2);
                                                                                     ~~^~~~~~~~~~~~~~~~~
/path/Multitarget-tracker/src/Tracker/staple/fhog.cpp: In function ‘void gradMag(float*, float*, float*, int, int, int, bool)’:
/path/Multitarget-tracker/src/Tracker/staple/fhog.cpp:92:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
                 if( c==0 ) continue; _m = sse::CMPGT( _M2[y1], _M2[y] );
                 ^~
/path/Multitarget-tracker/src/Tracker/staple/fhog.cpp:92:38: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
                 if( c==0 ) continue; _m = sse::CMPGT( _M2[y1], _M2[y] );
                                      ^~
/path/Multitarget-tracker/src/Tracker/staple/fhog.cpp: In function ‘void gradMagNorm(float*, float*, int, int, float)’:
/path/Multitarget-tracker/src/Tracker/staple/fhog.cpp:125:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(sse) i*=4; for(; i<n; i++) M[i] /= (S[i] + norm);
     ^~
/path/Multitarget-tracker/src/Tracker/staple/fhog.cpp:125:19: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
     if(sse) i*=4; for(; i<n; i++) M[i] /= (S[i] + norm);
                   ^~~
[ 34%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/ldes/correlation.cpp.o
[ 36%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/ldes/fft_functions.cpp.o
/path/Multitarget-tracker/src/Tracker/staple/staple_tracker.cpp: In member function ‘void STAPLE_TRACKER::mexResize(const cv::Mat&, cv::Mat&, cv::Size, const char*)’:
/path/Multitarget-tracker/src/Tracker/staple/staple_tracker.cpp:44:96: warning: unused parameter ‘method’ [-Wunused-parameter]
 xResize(const cv::Mat &im, cv::Mat &output, cv::Size newsz, const char *method)
                                                                         ^~~~~~
[ 37%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/ldes/fhog.cpp.o
[ 39%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/ldes/hann.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/ldes/ldes_tracker.cpp.o
[ 42%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/tokenise.cpp.o
[ 44%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/mytree.cpp.o
[ 45%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/mygraph.cpp.o
[ 47%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/mwbmatching.cpp.o
[ 49%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/mincut.cpp.o
/path/Multitarget-tracker/src/Tracker/ldes/ldes_tracker.cpp: In member function ‘cv::Mat LDESTracker::getFeatures(const cv::Mat&, cv::Mat&, int*, bool)’:
/path/Multitarget-tracker/src/Tracker/ldes/ldes_tracker.cpp:416:19: error: conversion from ‘const cv::Mat’ to non-scalar type ‘IplImage {aka _IplImage}’ requested
  IplImage z_ipl = patchl;
                   ^~~~~~
[ 50%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/gport.cpp.o
[ 52%] Building C object src/CMakeFiles/mtracking.dir/Tracker/graph/fheap.c.o
src/CMakeFiles/mtracking.dir/build.make:638: recipe for target 'src/CMakeFiles/mtracking.dir/Tracker/ldes/ldes_tracker.cpp.o' failed
make[2]: *** [src/CMakeFiles/mtracking.dir/Tracker/ldes/ldes_tracker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 54%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/GTL/src/bellman_ford.cpp.o
CMakeFiles/Makefile2:140: recipe for target 'src/CMakeFiles/mtracking.dir/all' failed
make[1]: *** [src/CMakeFiles/mtracking.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Nuzhny007** [comment]
Hi!
Try to change Multitarget-tracker/src/Tracker/ldes/ldes_tracker.cpp:416:
`IplImage z_ipl(patchl);`

And what the OpenCV version do you use?

**Comment by ijarraki** [comment]
I've tried changing it to either:
IplImage z_ipl = (patchl);
or
IplImage z_ipl = (patchl) ;
or
IplImage z_ipl(patchl);

Still getting the same fatal errors during compilation for the first two alternatives (which makes sense, your suggestion differs in the error message "IplImage z_ipl(patchl);":
Multitarget-tracker/src/Tracker/ldes/ldes_tracker.cpp: In member function ‘cv::Mat LDESTracker::getFeatures(const cv::Mat&, cv::Mat&, int*, bool)’:
/path/Multitarget-tracker/src/Tracker/ldes/ldes_tracker.cpp:417:23: error: no matching function for call to ‘_IplImage::_IplImage(const cv::Mat&)’
  IplImage z_ipl(patchl);
                       ^
In file included from /usr/local/include/opencv4/opencv2/core/core_c.h:48:0,
                 from /usr/local/include/opencv4/opencv2/imgproc/types_c.h:46,
                 from /usr/local/include/opencv4/opencv2/imgproc/imgproc_c.h:46,
                 from /path/Multitarget-tracker/src/Tracker/ldes/fhog.hpp:59,
                 from /path/Multitarget-tracker/src/Tracker/ldes/ldes_tracker.h:5,
                 from /path/Multitarget-tracker/src/Tracker/ldes/ldes_tracker.cpp:1:
/usr/local/include/opencv4/opencv2/core/types_c.h:327:1: note: candidate: _IplImage::_IplImage()
 _IplImage
 ^~~~~~~~~
/usr/local/include/opencv4/opencv2/core/types_c.h:327:1: note:   candidate expects 0 arguments, 1 provided
/usr/local/include/opencv4/opencv2/core/types_c.h:327:1: note: candidate: constexpr _IplImage::_IplImage(const _IplImage&)
/usr/local/include/opencv4/opencv2/core/types_c.h:327:1: note:   no known conversion for argument 1 from ‘const cv::Mat’ to ‘const _IplImage&’
/usr/local/include/opencv4/opencv2/core/types_c.h:327:1: note: candidate: constexpr _IplImage::_IplImage(_IplImage&&)
/usr/local/include/opencv4/opencv2/core/types_c.h:327:1: note:   no known conversion for argument 1 from ‘const cv::Mat’ to ‘_IplImage&&’
[ 50%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/gport.cpp.o
[ 52%] Building C object src/CMakeFiles/mtracking.dir/Tracker/graph/fheap.c.o
[ 54%] Building CXX object src/CMakeFiles/mtracking.dir/Tracker/graph/GTL/src/bellman_ford.cpp.o
src/CMakeFiles/mtracking.dir/build.make:638: recipe for target 'src/CMakeFiles/mtracking.dir/Tracker/ldes/ldes_tracker.cpp.o' failed
make[2]: *** [src/CMakeFiles/mtracking.dir/Tracker/ldes/ldes_tracker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:140: recipe for target 'src/CMakeFiles/mtracking.dir/all' failed
make[1]: *** [src/CMakeFiles/mtracking.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I'm using OpenCV master (pre-4.2.0), built for CUDA DNN acceleration.

**Comment by ijarraki** [comment]
Compiles just fine against 4.1.2/opencv commit 46206b481446fb0f64f4a4ad9d52d775ded5f688, 4.2 will drop support for the legacy feature in question.

I've enabled BUILD_YOLO_LIB, the compile succeeds and I get "libyolo_lib.so"; however if I try to use MultitargetTracker -e=6 for darknet backend I get "Wrong example number!".

Second issue: is there a way to force the different trackers display output to be "maximised" by default?

**Comment by Nuzhny007** [comment]
1. The first bug with IplImage will be fixed with this PR: https://github.com/Smorodov/Multitarget-tracker/pull/170
2. About BUILD_YOLO_LIB: try, plz, remove CMake cache. It looks like very strangely.
3. maximised: do you mean cv::namedWindows with flag cv::WINDOW_AUTOSIZE?
