### ISSUE TITLE
No targets specified and no makefile found.

### ISSUE THREAD

**Issue by hadi-ghnd** [Smorodov/Multitarget-tracker#174]
I am trying to build the project using CMake. However, I am having problems.

### System configuration:
windows 10
visual studio 19
OpenCV 4.2
CMake 3.16

### My steps:

1. Downloaded the **.zip** file from the repository and extracted it.
2. Configure and generate with CMake.

![image](https://user-images.githubusercontent.com/24352869/71630885-953b3280-2bd3-11ea-8ca3-14d65c01f030.png)

3. go to **/build** directory and run **PowerShell** and try **make**.

![image](https://user-images.githubusercontent.com/24352869/71630932-cfa4cf80-2bd3-11ea-9a90-79c8ae7ea419.png)

4. go to **/build** directory and open **MTTracking.sln**. switch to **Release** mode and build **ALL_BUILD**.

![image](https://user-images.githubusercontent.com/24352869/71630976-11357a80-2bd4-11ea-9c06-e3a95a94a71d.png)

### Question:
What am I doing wrong here?  Am I missing any steps?

Thank you for your time!

**Comment by Nuzhny007** [comment]
Hi!
Do you can show all errors? Compiler says about 4 errors but I see only 3.
And show, please, more options in CMake.

**Comment by hadi-ghnd** [comment]
I changed Cuda version to 10.2 and compiled with visual studio 19. These errors were solved but there is still no **makefile** in the build folder.

In the **Release** folder I added all the dll files from OpenCV and Qt. It seems to be working now.

**Comment by Nuzhny007** [comment]
Makefile is for linux-based systems. For Windows you makes all right
