### ISSUE TITLE
How to switch between different detectors and trackers?

### ISSUE THREAD

**Issue by hadi-ghnd** [Smorodov/Multitarget-tracker#177]
I am trying to find a config file where I can set the detector and tracker. It seems that there are different detectors and we should choose one from the list:
```
    Motion_VIBE,
    Motion_MOG,
    Motion_GMG,
    Motion_CNT,
    Motion_SuBSENSE,
    Motion_LOBSTER,
    Motion_MOG2,
    Face_HAAR,
    Pedestrian_HOG,
    Pedestrian_C4,
    SSD_MobileNet,
    Yolo_OCV,
    Yolo_Darknet
```

And also there are multiple trackers:

```
    Hungrian
    weighted bipartite graphs
    bellman_ford
    bid_dijkstra
    ldes_tracker
    Ctracker
    fhog
    etc ...
```

My question is how to switch between these options? Also, which is better in general?

Thank you for your time!

**Comment by Nuzhny007** [comment]
Hi!
Sorry for long silence.

**Detectors:**
Motion_VIBE, Motion_MOG, Motion_GMG, Motion_CNT, Motion_SuBSENSE, Motion_LOBSTER,     Motion_MOG2 are good for static cameras, lighting and background.
Face_HAAR - fast on CPU but not accuracy for face detection.
Pedestrian_HOG and Pedestrian_C4 - HOG based algorithms for pedestrians detection only.
SSD_MobileNet and Yolo_OCV - the same opencv_dnn based methods but with different DNNs.
Yolo_Darknet - used C + CUDA implemented Darknet framework for fast objects detection on GPU.

**Assignment  problem:**
Hungrian O(N^3) and weighted bipartite graphs O(M N^2) used different approach for solving this problem.

**Other:**
bellman_ford and bid_dijkstra are direct not used
...

**Comment by hadi-ghnd** [comment]
Thank you for your helpful answer! I am working with static cameras, so I can use the first group of background subtraction methods for detection.
If you don't mind me asking, how can I switch between these detection and tracking methods in the code? 
I know with **Number of example** we can choose different modules, but what about different trackers?

**Comment by Nuzhny007** [comment]
Feor detectors: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/examples.h#L62
For trackes params: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/examples.h#L91
