### ISSUE TITLE
Display tracker id

### ISSUE THREAD

**Issue by sathiez** [Smorodov/Multitarget-tracker#178]
Hi,

There will be unique tracker id for each tracks.
How to display tracker id along with object type and confidence for each object? 
for eg: (person : 0.65 , <tracker_id>)

**Comment by Nuzhny007** [comment]
It's simple. Now:
`
std::string label = track.m_type + ": " + std::to_string(track.m_confidence);`
New:
`std::string label = track.m_type + ": " + std::to_string(track.m_confidence) + ", " + std::to_string(track.m_ID);`
