### ISSUE TITLE
make error: opencv2/bgsegm.hpp

### ISSUE THREAD

**Issue by MinaBahig** [Smorodov/Multitarget-tracker#18]
I'm using OpenCV 3.2.0 on Ubuntu 14.04
when I try to run "make" I get the following error:
"
In file included from /home/mina/Desktop/Hungarian/Multitarget-tracker/main.cpp:2:0:
/home/mina/Desktop/Hungarian/Multitarget-tracker/vibe_src/BackgroundSubtract.h:6:30: fatal error: opencv2/bgsegm.hpp: No such file or directory
 #include <opencv2/bgsegm.hpp>
                              ^
compilation terminated.
make[2]: *** [CMakeFiles/MultitargetTracker.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
make: *** [all] Error 2
"
Lately, I've learned that bgsegm might work on older OpenCV versions (e.g. 3.0.0), but I'm currently using 3.2.0 for my projects, so is there a way for the code to run on 3.2.0?
Thanks in advance.

**Comment by Nuzhny007** [comment]
Do you have an opencv_contrib? Here: https://github.com/opencv/opencv_contrib
MOG and GMG algorithm was added from bgsegm module: https://github.com/opencv/opencv_contrib/tree/master/modules/bgsegm

**Comment by Nuzhny007** [comment]
Master branch has also BackgroundSubtractorCNT algorithm. But it will be added after official library release.

**Comment by MinaBahig** [comment]
I have opencv_contrib and specified OPENCV_EXTRA_MODULES_PATH while building opencv, however it seems I can only include it in python projects (import cv2.bgsegm) but not in C/C++ projects.

**Comment by Nuzhny007** [comment]
You can open CMakeCache.txt from OpenCV build and find strings:
//Include opencv_bgsegm module into the OpenCV build
BUILD_opencv_bgsegm:BOOL=ON

It's really ON?

**Comment by MinaBahig** [comment]
I couldn't find these lines

**Comment by MinaBahig** [comment]
I couldn't find these lines in CmakeCache.txt
Had to rebuild opencv but no use.

**Comment by Nuzhny007** [comment]
I think that you can fix this issue by the reconfigure your OpenCV. But I also add option USE_OCV_BGFG to the CMake. It can enable or disable MOG and GMG from the sources - Vibe will be used by default. See my pull request #19.

**Comment by Nuzhny007** [comment]
![screenshot from 2017-04-06 06-33-13](https://cloud.githubusercontent.com/assets/5041357/24736803/030f0264-1a93-11e7-8d87-a67ebd9a2648.png)
Do you set this options?

**Comment by littletomatodonkey** [comment]
How can I build this program if I use opencv2.4.13? I find it also gives the error like this.... And I can not build opencv_contrib with opencv2.4.XX

**Comment by Nuzhny007** [comment]
If you set variable USE_OCV_BGFG in OFF then opencv_contrib will not be used.

**Comment by littletomatodonkey** [comment]
I just set that to OFF and it did not work neither, and I found it was because I you write it with opencv3, I just modified some codes and it can work now, thank you!
