### ISSUE TITLE
Best parameters and improve the tracking

### ISSUE THREAD

**Issue by zpmmehrdad** [Smorodov/Multitarget-tracker#181]
Hi @Nuzhny007 

I have some videos with 2704x1520 resolution and I have recorded around the city. I'm using SSD to detecting the objects and I want to know, What is the best parameters to get good result?
Sometimes when the car is away, it gives an ID and when it gets close to the object it gives a new ID

[My video](https://www.youtube.com/watch?v=P8TWtT2aP-I)

I use this setting:
TrackerSettings settings;
settings.SetDistance(tracking::DistCenters);
settings.m_kalmanType = tracking::KalmanLinear;
settings.m_filterGoal = tracking::FilterCenter;
settings.m_lostTrackType = tracking::TrackCSRT;  
settings.m_matchType = tracking::MatchBipart;
settings.m_dt = 3.0f;//0.4f;          
settings.m_accelNoiseMag = 0.5f;      
settings.m_distThres = 0.95f;                  
settings.m_minAreaRadius = uframe.rows / 10.f;

**Comment by Nuzhny007** [comment]
Hi! It's individually. My values for ADAS on Nvidia Jetson Nano:
```
TrackerSettings settings;
settings.SetDistance(tracking::DistCenters);
settings.m_kalmanType = tracking::KalmanLinear;
settings.m_filterGoal = tracking::FilterCenter;
settings.m_lostTrackType = tracking::TrackKCF;       // Use visual objects tracker for collisions resolving
settings.m_matchType = tracking::MatchHungrian;
settings.m_dt = 0.2f;                                // Delta time for Kalman filter
settings.m_accelNoiseMag = 0.2f;                     // Accel noise magnitude for Kalman filter
settings.m_distThres = 0.8f;                         // Distance threshold between region and object on two frames
settings.m_minAreaRadius = frame.rows / 20.f;
settings.m_maximumAllowedSkippedFrames = cvRound(2 * m_fps); // Maximum allowed skipped frames
settings.m_maxTraceLength = cvRound(5 * m_fps);      // Maximum trace length
```
And advanced filtration before drawing tracks:
```
if (track.IsRobust(2,            // Minimal trajectory size
			0.5f,                        // Minimal ratio raw_trajectory_points / trajectory_lenght
			cv::Size2f(0.1f, 8.0f))      // Min and max ratio: width / height
			)
		{
			...
```

I will think how to make automatic parameters adjusting...

**Comment by zpmmehrdad** [comment]
@Nuzhny007 Hi,

Thanks for your response, When I use tracking::DistRects instead of tracking::DistCenters the result is good but sometimes it gives me an ID on two different objects and in a same class. 
Can I to fix this problem?

Thanks in advance

**Comment by Nuzhny007** [comment]
Hm, I'll try to reproduce this bug.

**Comment by zpmmehrdad** [comment]
@Nuzhny007 Hi,

In these pictures I have two objects in the same class (No Truck) but it gaves me the track id 39 for first object and also gaves me number 39 for second object. My video 60 FPS, I think it depends to distance between two objects. How can I improve it?

![1](https://user-images.githubusercontent.com/5433346/72709068-57e61700-3b79-11ea-9e28-2a8578e05057.jpg)
![2](https://user-images.githubusercontent.com/5433346/72709073-5a487100-3b79-11ea-878b-186be355dee8.jpg)


   TrackerSettings settings;
                        settings.SetDistance(tracking::DistRects);
                        settings.m_kalmanType = tracking::KalmanLinear;
                        settings.m_filterGoal = tracking::FilterCenter;
                        settings.m_lostTrackType = tracking::TrackCSRT;       // Use visual objects tracker for collisions resolving
                        settings.m_matchType = tracking::MatchHungrian;
                        settings.m_dt = 0.4;
                        settings.m_accelNoiseMag = 0.5f;
                        settings.m_distThres = 0.95f;
                        settings.m_minAreaRadius = uframe.rows / 20.f;
 settings.m_maximumAllowedSkippedFrames = cvRound(2 * video_fps); //cvRound(2 * video_fps); // Maximum allowed skipped frames
                            settings.m_maxTraceLength = cvRound(2 * video_fps);

**Comment by zpmmehrdad** [comment]
@Nuzhny007 Hi,
Did you check it?

Thanks

**Comment by Nuzhny007** [comment]
Hi!
I tested on similar scene. The objects are very similar and visual tracker (CSRT) jumps on new sign. It need to implement graph-flow tracking, for example: http://www.cvlibs.net/projects/online_tracking/
I will think more. I don’t have a simple ready-made solution yet

**Comment by zpmmehrdad** [comment]
@Nuzhny007 Hi,

Thanks for your response, So why do I change the SetDistance to DistCenter the tracker works fine? but has a problem, sometimes the tracker gives two ID for an object. Is there a way to solve it?

**Comment by Nuzhny007** [comment]
DistCenter is intuitive and clear on how to set a threshold.

>but has a problem, sometimes the tracker gives two ID for an object
On one frame or on different frames?

**Comment by zpmmehrdad** [comment]
@Nuzhny007  Hi,

On different frames.

**Comment by Nuzhny007** [comment]
It's a problem of the current approach. I have a plans to the implementation graph-flow tracking and reidentification like DeepSort - https://github.com/humoncy/YOLOv3-SORT-ReID.
