### ISSUE TITLE
Unscented Kalman Filter segmentation fault

### ISSUE THREAD

**Issue by meftehSafa** [Smorodov/Multitarget-tracker#184]
After enabling UKF on CMakeLists.txt, a segmentation fault error appears. This error is because the disability to create m_unscentedKalman variable ( is always NULL). Perhaps, the code is always stuck up on this condition m_initialPoints.size() < MIN_INIT_VALS on update function.
Is there any solution ?? either i modified the MIN_INIT_VALS = 0 the error persist

**Comment by Nuzhny007** [comment]
Thank you! I'll fix this bug

**Comment by Nuzhny007** [comment]
Fixed
