### ISSUE TITLE
about association？

### ISSUE THREAD

**Issue by 123lifei** [Smorodov/Multitarget-tracker#193]
I find the assignment distances matrix is computed after kalman-tracker is updated in your project But in the SORT paper the assignment distances matrix is computed after kalman predicting. it means in your project the process is predicting ，then update and Associated by Hungary Algorithm ，But in sort paper the process is predicting ，then Associated by Hungary Algorithm and update。Is that right？Thank you

**Comment by Nuzhny007** [comment]
Yes. What is the question?
"distances matrix is computed after kalman-tracker is updated in your project"
"in the SORT paper the assignment distances matrix is computed after kalman predicting"
It's the same. @Smorodov?

**Comment by Smorodov** [comment]
I think assignment problem is better to solve after kalman prediction, but difference not very large. So, I don't think it will change the results much.
