### ISSUE TITLE
Request for the specifications used

### ISSUE THREAD

**Issue by PSURESH192** [Smorodov/Multitarget-tracker#2]
Sir 
may i know the opencv version and the libraries required to be built for successful building of this codes.thank you in advance

**Comment by Smorodov** [comment]
It need OpenCV version >= 2.4 that's all. It may be minor changes for different versions but they are not hard to correct.

**Comment by PSURESH192** [comment]
Thank you very much for spending your valuable time in sending the reply to
me sir.

Regards

Prabha Suresh
