### ISSUE TITLE
how to use yolo darnet?

### ISSUE THREAD

**Issue by xinsuinizhuan** [Smorodov/Multitarget-tracker#223]
when i run car_count exmaple, it tip me,
Darknet inference engine was not configured in CMake

**Comment by Nuzhny007** [comment]
Hi!
This example uses a YOLO v4 for detection and Darknet framework as inference backend. So it need set cmake option -DBUILD_YOLO_LIB=ON and install before CUDA and cuDNN.
Something:
`cmake . .. -DUSE_OCV_KCF=ON -DBUILD_YOLO_LIB=ON -DBUILD_CARS_COUNTING=ON`
