### ISSUE TITLE
I have compiled successfully now, how can I use this to test my own video

### ISSUE THREAD

**Issue by byq-luo** [Smorodov/Multitarget-tracker#225]
I have compiled successfully on Windows 10 (x64）now, how can I use this to test my own video.

Usage:
         ./MultitargetTracker <path to movie file> [--example]=<number of example 0..7> [--start_frame]=<start a video from this position> [--end_frame]=<play a video to this position> [--end_delay]=<delay in milliseconds after video ending> [--out]=<name of result video file> [--show_logs]=<show logs> [--gpu]=<use OpenCL> [--async]=<async pipeline>
         ./MultitargetTracker ../data/atrium.avi -e=1 -o=../data/atrium_motion.avi

I didn't understand it, please guide me to specific operations, thank you.

**Comment by Nuzhny007** [comment]
The base examples (you can change parameters and use advanced options):

0. Mouse tracking example:
`MultitargetTracker.exe -e=0 -o=res_mouse.mp4`

1. Motion detector with background/foreground segmentation:
`MultitargetTracker.exe ../../data/atrium.avi -e=1 -a=0 -o=res_bgfg.mp4`

2. Haar face detection and tracking:
`MultitargetTracker.exe ../../data/smuglanka.mp4 -e=2 -a=0 -o=res_face.mp4`

3. HOG pedestrian detection and tracking:
`MultitargetTracker.exe ../../data/atrium.avi -e=3 -a=0 -o=res_pedestrians.mp4`

4. MobileNet detector with opencv_dnn backend. MobileNetSSD weights you must download manually and set paths to cfg and weight file in examples.h in SSDMobileNetExample::InitDetector method:
`MultitargetTracker.exe ../../data/atrium.avi -e=4 -a=0 -o=res_ocvdnn_mobilenet.mp4`

5. YOLO detector with opencv_dnn backend. YOLO weights you must download manually and set paths to cfg and weight file in examples.h in YoloExample::InitDetector method:
`MultitargetTracker.exe ../../data/atrium.avi -e=5 -a=0 -o=res_ocvdnn_yolo.mp4`

6. YOLO detector with Darknet backend (build project with -DBUILD_YOLO_LIB=ON). YOLO weights you must download manually and set paths to cfg and weight file in examples.h in YoloDarknetExample::InitDetector method:
`MultitargetTracker.exe ../../data/atrium.avi -e=6 -a=0 -o=res_darknet_yolo.mp4`

7.  YOLO detector with TensorRT backend (build project with -DBUILD_YOLO_TENSORRT=ON). YOLO weights you must download manually and set paths to cfg and weight file in examples.h in YoloTensorRTExample::InitDetector method:
`MultitargetTracker.exe ../../data/atrium.avi -e=7 -a=0 -o=res_tensorrt_yolo.mp4`

8. CarsCounting example works with YOLO network and Darknet backend (build project with -DBUILD_CARS_COUNTING=ON -DBUILD_YOLO_LIB=ON). YOLO weights you must download manually and set paths to cfg and weight file in CarsCounting.cpp in CarsCounting::InitTracker method. Lines configuration in cars_counting/main.cpp by cars_counting.AddLine:
`CarsCounting.exe video_with_traffic.mp4 -o=cars_count_speed.avi`

9. AsyncDetector also works with YOLO network and Darknet backend (build project with -DBUILD_ASYNC_DETECTOR=ON -DBUILD_YOLO_LIB=ON). YOLO weights you must download manually and set paths to cfg and weight file in AsyncDetector.cpp in AsyncDetector::CaptureThread method:
`AsyncDetector.exe ../../data/atrium.avi -g=0 -o=async.avi`

**Comment by byq-luo** [comment]
> The base examples (you can change parameters and use advanced options):
> 
> 1. Mouse tracking example:
>    `MultitargetTracker.exe -e=0 -o=res_mouse.mp4`
> 2. Motion detector with background/foreground segmentation:
>    `MultitargetTracker.exe ../../data/atrium.avi -e=1 -a=0 -o=res_bgfg.mp4`
> 3. Haar face detection and tracking:
>    `MultitargetTracker.exe ../../data/smuglanka.mp4 -e=2 -a=0 -o=res_face.mp4`
> 4. HOG pedestrian detection and tracking:
>    `MultitargetTracker.exe ../../data/atrium.avi -e=3 -a=0 -o=res_pedestrians.mp4`
> 5. MobileNet detector with opencv_dnn backend. MobileNetSSD weights you must download manually and set paths to cfg and weight file in examples.h in SSDMobileNetExample::InitDetector method:
>    `MultitargetTracker.exe ../../data/atrium.avi -e=4 -a=0 -o=res_ocvdnn_mobilenet.mp4`
> 6. YOLO detector with opencv_dnn backend. YOLO weights you must download manually and set paths to cfg and weight file in examples.h in YoloExample::InitDetector method:
>    `MultitargetTracker.exe ../../data/atrium.avi -e=5 -a=0 -o=res_ocvdnn_yolo.mp4`
> 7. YOLO detector with Darknet backend (build project with -DBUILD_YOLO_LIB=ON). YOLO weights you must download manually and set paths to cfg and weight file in examples.h in YoloDarknetExample::InitDetector method:
>    `MultitargetTracker.exe ../../data/atrium.avi -e=6 -a=0 -o=res_darknet_yolo.mp4`
> 8. YOLO detector with TensorRT backend (build project with -DBUILD_YOLO_TENSORRT=ON). YOLO weights you must download manually and set paths to cfg and weight file in examples.h in YoloTensorRTExample::InitDetector method:
>    `MultitargetTracker.exe ../../data/atrium.avi -e=7 -a=0 -o=res_tensorrt_yolo.mp4`
> 9. CarsCounting example works with YOLO network and Darknet backend (build project with -DBUILD_CARS_COUNTING=ON -DBUILD_YOLO_LIB=ON). YOLO weights you must download manually and set paths to cfg and weight file in CarsCounting.cpp in CarsCounting::InitTracker method. Lines configuration in cars_counting/main.cpp by cars_counting.AddLine:
>    `CarsCounting.exe video_with_traffic.mp4 -o=cars_count_speed.avi`
> 10. AsyncDetector also works with YOLO network and Darknet backend (build project with -DBUILD_ASYNC_DETECTOR=ON -DBUILD_YOLO_LIB=ON). YOLO weights you must download manually and set paths to cfg and weight file in AsyncDetector.cpp in AsyncDetector::CaptureThread method:
>     `AsyncDetector.exe ../../data/atrium.avi -g=0 -o=async.avi`

My gratitude to you for all you have done for me.
