### ISSUE TITLE
CarsCounting.exe video_with_traffic.mp4 -o=cars_count_speed.avi

### ISSUE THREAD

**Issue by byq-luo** [Smorodov/Multitarget-tracker#227]
I have successfully run this[CarsCounting.exe video_with_traffic.mp4 -o=cars_count_speed.avi], but only have the vehicle counts, no speed, what's going on?
![image](https://user-images.githubusercontent.com/54296913/83934667-319ddc80-a7e5-11ea-8607-79cf004368e7.png)

**Comment by Nuzhny007** [comment]
Unfortunately, with speed - no so simple. I have read this paper: https://medium.com/hal24k-techblog/how-to-track-objects-in-the-real-world-with-tensorflow-sort-and-opencv-a64d9564ccb1

So it need to set 4 pairs: coordinate in pixel on frame and world geographical coordinate:
1. Take snapshot from your video and open it in editor.
2. Open Goggle Earth on place with camera.
3. It is necessary to find the 4 key points (with coordinates in pixels) that are visible in the satellite image (with geographical coordinates).
4. Put the 4 pairs in code. Here: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L382
```
	std::vector<cv::Point> framePoints{ cv::Point(420, 348), cv::Point(509, 283), cv::Point(731, 281), cv::Point(840, 343) };
	std::vector<cv::Point2f> geoPoints{ cv::Point2f(45.526646, 5.974535), cv::Point2f(45.527566, 5.973849), cv::Point2f(45.527904, 5.974135), cv::Point2f(45.526867, 5.974826) };
	m_geoParams.SetKeyPoints(framePoints, geoPoints);
```
Yes, it's hard and I think about semiautomatic binding frame to satellite. So, you can also change lines positions here: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/main.cpp#L44
 ```
   cars_counting.AddLine(RoadLine(cv::Point2f(0.1f, 0.7f), cv::Point2f(0.47f, 0.7f), 0));
    cars_counting.AddLine(RoadLine(cv::Point2f(0.52f, 0.6f), cv::Point2f(0.8f, 0.6f), 1));
```

**Comment by byq-luo** [comment]
> Unfortunately, with speed - no so simple. I have read this paper: https://medium.com/hal24k-techblog/how-to-track-objects-in-the-real-world-with-tensorflow-sort-and-opencv-a64d9564ccb1
> 
> So it need to set 4 pairs: coordinate in pixel on frame and world geographical coordinate:
> 
> 1. Take snapshot from your video and open it in editor.
> 2. Open Goggle Earth on place with camera.
> 3. It is necessary to find the 4 key points (with coordinates in pixels) that are visible in the satellite image (with geographical coordinates).
> 4. Put the 4 pairs in code. Here: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L382
> 
> ```
> 	std::vector<cv::Point> framePoints{ cv::Point(420, 348), cv::Point(509, 283), cv::Point(731, 281), cv::Point(840, 343) };
> 	std::vector<cv::Point2f> geoPoints{ cv::Point2f(45.526646, 5.974535), cv::Point2f(45.527566, 5.973849), cv::Point2f(45.527904, 5.974135), cv::Point2f(45.526867, 5.974826) };
> 	m_geoParams.SetKeyPoints(framePoints, geoPoints);
> ```
> 
> Yes, it's hard and I think about semiautomatic binding frame to satellite. So, you can also change lines positions here: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/main.cpp#L44
> 
> ```
>   cars_counting.AddLine(RoadLine(cv::Point2f(0.1f, 0.7f), cv::Point2f(0.47f, 0.7f), 0));
>    cars_counting.AddLine(RoadLine(cv::Point2f(0.52f, 0.6f), cv::Point2f(0.8f, 0.6f), 1));
> ```

Thanks for your help

**Comment by vinnadipo09** [comment]
@byq-luo Did you manage to get the speeds working for you?
