### ISSUE TITLE
 Is it possible to keep the trajectory of each car all the time without disappearing, so that I can analyze the overall distribution of the trajectory of the vehicle throughout the day

### ISSUE THREAD

**Issue by byq-luo** [Smorodov/Multitarget-tracker#228]
Is it possible to keep the trajectory of each car all the time without disappearing, so that I can analyze the overall distribution of the trajectory of the vehicle throughout the day/one hour.
![image](https://user-images.githubusercontent.com/54296913/83937031-cf9ca180-a7fb-11ea-9150-e7d0ff0404e7.png)

In addition, can cars_counting.AddLine be made mouse interactive, so that it is more convenient to draw the detection line of each lane?
Thank you.

**Comment by Nuzhny007** [comment]
1. It's simple, for example 10 minutes for trajectory:
 `settings.m_maxTraceLength = cvRound(10 * 60 * m_fps);`

2. Yes. I'll think how to make it with OpenCV GUI.

**Comment by byq-luo** [comment]
> 1. It's simple, for example 10 minutes for trajectory:
>    `settings.m_maxTraceLength = cvRound(10 * 60 * m_fps);`
> 2. Yes. I'll think how to make it with OpenCV GUI.
Thank you for your generous help.

**Comment by byq-luo** [comment]
> 1. It's simple, for example 10 minutes for trajectory:
>    `settings.m_maxTraceLength = cvRound(10 * 60 * m_fps);`
> 2. Yes. I'll think how to make it with OpenCV GUI.

Thank you for your generous help

**Comment by byq-luo** [comment]
> > 1. It's simple, for example 10 minutes for trajectory:
> >    `settings.m_maxTraceLength = cvRound(10 * 60 * m_fps);`
> > 2. Yes. I'll think how to make it with OpenCV GUI.
> 
> Thank you for your generous help

I had did it，But it didn't work.

![image](https://user-images.githubusercontent.com/54296913/83941184-f8cd2a00-a81b-11ea-80a9-06ef517053d5.png)

**Comment by Nuzhny007** [comment]
Aaa... Do you want save trajectories after the vehicles was leave frame? This project has not this functionality but you can write it himself. In method CarsCounting::DrawData we get all detections and draw trajectories. You can save they with timestamps  and hold 1 hour.

**Comment by byq-luo** [comment]
> Aaa... Do you want save trajectories after the vehicles was leave frame? This project has not this functionality but you can write it himself. In method CarsCounting::DrawData we get all detections and draw trajectories. You can save they with timestamps and hold 1 hour.
Thank you. I try it.
