### ISSUE TITLE
compilation in Ubuntu 14.04

### ISSUE THREAD

**Issue by ARHLANE** [Smorodov/Multitarget-tracker#23]
Hi Mr Smorodov
thank you for sharing your code
I want to compile this project in ubuntu 14.04 with opencv 3.1.0.
But I do not know how to compile it with gcc ??

**Comment by Nuzhny007** [comment]
You can run cmake first. And then make.

**Comment by ARHLANE** [comment]
I tried to compile but I get the following error
arhlane@arhlane-HP-Pavilion-g6-Notebook-PC:~/Multitarget-tracker/build$ make -j3
Scanning dependencies of target MultitargetTracker
[  2%] [  5%] [  7%] Building CXX object CMakeFiles/MultitargetTracker.dir/main.cpp.o
Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/Detector.cpp.o
c++: error: unrecognized command line option '--std=gnu++14'
make[2]: *** [CMakeFiles/MultitargetTracker.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
c++: error: unrecognized command line option '--std=gnu++14'
make[2]: *** [CMakeFiles/MultitargetTracker.dir/Detector/Detector.cpp.o] Error 1
Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o
c++: error: unrecognized command line option '--std=gnu++14'
make[2]: *** [CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o] Error 1
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
make: *** [all] Error 2

**Comment by Nuzhny007** [comment]
Ok.
--std=gnu++14 used only for function std::make_unique. And gcc from 14.04 don't support this C++ standart.
What you can do: in CMakeLists.txt change to --std=gnu++11.
And all calls std::make_unique change to constructor std::unique_ptr.
See another ussue: https://github.com/Smorodov/Multitarget-tracker/issues/9

**Comment by ARHLANE** [comment]
Thank you very much for your reply
I made the changes you asked me
Now I have successfully executed the code but when I tried to compile the executable file (./MultitargetTracker) I receive the following error
OpenCV CNT algorithm is not implemented! Used Vibe by default.
OpenCV Error: Unsupported format or combination of formats in CvVideoWriter_GStreamer :: open, file /home/arhlane/opencv-3.1.0/modules/videoio/src/cap_gstreamer.cpp, line 1380
Terminate called after throwing an instance of 'cv :: Exception'
   What (): /home/arhlane/opencv-3.1.0/modules/videoio/src/cap_gstreamer.cpp:1380: error: (-210) Gstreamer Opencv backend does not support this file type. In function CvVideoWriter_GStreamer :: open

Aborted (core dumped)

**Comment by Nuzhny007** [comment]
1.
>OpenCV CNT algorithm is not implemented! Used Vibe by default.
This algorithm is new and absent in your OpenCV version. In main.cpp write:
CDetector detector(BackgroundSubtract::ALG_MOG, useLocalTracking, gray);

2.
>OpenCV Error: Unsupported format or combination of formats in CvVideoWriter_GStreamer
In main.cpp try write:
writer.open(outFile, cv::VideoWriter::fourcc('h', '2', '6', '4'), capture.get(cv::CAP_PROP_FPS), frame.size(), true);

**Comment by ARHLANE** [comment]
I replaced
CDetector detector (BackgroundSubtract :: ALG_CNT, useLocalTracking, gray);
by
  CDetector detector (BackgroundSubtract :: ALG_MOG, useLocalTracking, gray);
And I also replaced
Writer.open (outFile, cv :: VideoWriter :: fourcc ('M', 'J', 'P', 'G'), capture.get (cv :: CAP_PROP_FPS), frame.size (), true);
by
Writer.open (outFile, cv :: VideoWriter :: fourcc ('h', '2', '6', '4'), capture.get (cv :: CAP_PROP_FPS), frame.size (), true); }

But I still receive the following error
OpenCV Error: Unsupported format or combination of formats (Gstreamer Opencv backend does not support this file type.)

**Comment by Nuzhny007** [comment]
Mmm... This error says that your version of gstreamer can't create result video file with mjpeg and h264 encoding. For check this hypotheses you can comment line **Writer.open (outFile,**

**Comment by ARHLANE** [comment]
when i comment line Writer.open..
Now I have successfully compiled the projects
Is that I can use it with ip camera?
Is that I can implement this projects with raspberry pi?
cordially

**Comment by Nuzhny007** [comment]
Yes, you can use this project with ip-camera. I don't now about gstreamer but on my Ubuntu OpenCV uses capture from ip-camera with ffmpeg. You can set address (eg std::string inFile("rtsp://admin:pass@192.168.0.1/live");) and example will be work.

I haven't a Raspberry pi but Tracker must compile and work.

**Comment by ARHLANE** [comment]
I tried using an ip camera but it does not work in real time FPS too slow
Is that the problem is ffmpeg (already installed)?
cordially

**Comment by Nuzhny007** [comment]
You can use valgrind for profiling.
And more fast settings for detector and tracker:

```
bool useLocalTracking = false;
CDetector detector(BackgroundSubtract::ALG_MOG, useLocalTracking, gray);
CTracker tracker(useLocalTracking,
                     CTracker::RectsDist,
                     CTracker::KalmanLiner
                     CTracker::FilterCenter,
                     CTracker::TrackNone,      // Use KCF tracker for collisions resolving
                     CTracker::MatchHungrian,
                     0.3f,                    // Delta time for Kalman filter
                     0.1f,                    // Accel noise magnitude for Kalman filter
                     gray.cols / 20.0f,       // Distance threshold between two frames
                     fps,                     // Maximum allowed skipped frames
                     5 * fps                 // Maximum trace length
                     );
```

**Comment by ARHLANE** [comment]
Nuzhny007
thanks for your reply
I use Valgrind for profiling and now the MotionDetector code works fine but I in my project I want the tracking and counting of the person, when I execute PedestrianDetector it does not work in real time FPS too slow even with a video
How can I improve tracking of people?
I have already done a person detection code with HOG now I need to add tracking in my code (Kalman for example) and that's why I tried to understand your implementation

**Comment by Nuzhny007** [comment]
Hi!
In our project uses c4-pedestrian-detector (example number 3 - function PedestrianDetector). From here: https://github.com/sturkmen72/C4-Real-time-pedestrian-detection
You can run our example - it will be faster then classic HOG detector.
And HOG detector also implemented - try it with macros #define USE_HOG 1

**Comment by ARHLANE** [comment]
316/5000
Hello again 
I tested the project C4-Real-time-pedestrian-detection but it is also very slow, is that the problem is the dimensions of vidio?
I do not know how I can get a real-time tracking (peaple) like your results (Motion Detection and Tracking: https://www.youtube.com/watch?v=GjN8jOy4kVw)

**Comment by Nuzhny007** [comment]
Hi!
In this video I don't use Pedestrian detector - only motions. And my CPU - desktop Intel i7 K-series. It's very fast.
And yes. The analysis of the FullHD videos will be slow. But you can:
1. scale down frames before detection and tracking;
2. use pedestrian detector not for all windows sizes - only for real pedestrians in specific video.

I think than real time for pedestrians detection - it can be done.

**Comment by Atarashii** [comment]
hello, trying to make the repository using ubuntu and getting a weird error.. i have to add that i have never tried this before and that i am not used to building from other people's repositories, could you possibly help me solve this?:

Atarashii@LILLITH:/mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/build$ make
Scanning dependencies of target MultitargetTracker
[  2%] Building CXX object CMakeFiles/MultitargetTracker.dir/main.cpp.o
In file included from /mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/Tracker/Ctracker.h:8:0,
                 from /mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/main.cpp:6:
/mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/Tracker/track.h: In member function ‘void CTrack::RectUpdate(const CRegion&, bool, cv::Mat, cv::Mat)’:
/mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/Tracker/track.h:392:33: error: ‘createTracker’ is not a member of ‘cv::TrackerKCF’
                     m_tracker = cv::TrackerKCF::createTracker(params);
                                 ^
In file included from /mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/main.cpp:11:0:
/mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/pedestrians/c4-pedestrian-detector.h: At global scope:
/mnt/c/Users/atara/Desktop/PROGRAMS/REPO/Multitarget-tracker/pedestrians/c4-pedestrian-detector.h:594:74: warning: unused parameter ‘m’ [-Wunused-parameter]
 double UseSVM_CD_FastEvaluationStructure(const char* modelfile,const int m,Array2dC<double>& result)
                                                                          ^
CMakeFiles/MultitargetTracker.dir/build.make:62: recipe for target 'CMakeFiles/MultitargetTracker.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MultitargetTracker.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MultitargetTracker.dir/all' failed
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

i have no idea where to start to fix this.

please help

**Comment by Smorodov** [comment]
Options USE_OCV_BGFG, USE_OCV_KCF, USE_OCV_UKF can be used only if you have installed opencv_contrib module, which is not installed by default. Else turn them off in cmake.

**Comment by Atarashii** [comment]
thank you so much, that fixed the build issue, now that i have a .exe file, i have one last noob question that i would like to ask...

how do i now use the exe file? if double clicked it briefly opens a cmd window then closes instantly.

is it possible to apply this software to any video of my choosing? can it be applied to, say, a usb webcam?

**Comment by daphfair** [comment]
Good evening, 

I am compiling on Ubuntu 14.04 and made the changes recommended above in regard to editing references to std::make_unique to std::unique_ptr and  specifiing gnu++11 in CMakeLists.txt.

When I run make, however, it halts at 2% with numerous issues, including: 

In file included from /usr/include/c++/4.8/memory:81:0,
                 from /home/thisUser/russ/Multitarget-tracker/Tracker/Ctracker.h:4,
                 from /home/thisUser/russ/Multitarget-tracker/MouseExample.h:5,
                 from /home/thisUser/russ/Multitarget-tracker/main.cpp:1:
/usr/include/c++/4.8/bits/unique_ptr.h:160:7: note: std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = CDetector; _Dp = std::default_delete<CDetector>]
       unique_ptr(unique_ptr&& __u) noexcept
       ^
/usr/include/c++/4.8/bits/unique_ptr.h:160:7: note:   candidate expects 1 argument, 3 provided
/usr/include/c++/4.8/bits/unique_ptr.h:157:17: note: constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Tp = CDetector; _Dp = std::default_delete<CDetector>; std::nullptr_t = std::nullptr_t]
       constexpr unique_ptr(nullptr_t) noexcept : unique_ptr() { }
                 ^
/usr/include/c++/4.8/bits/unique_ptr.h:157:17: note:   candidate expects 1 argument, 3 provided
/usr/include/c++/4.8/bits/unique_ptr.h:151:7: note: std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>::pointer, typename std::remove_reference<_To>::type&&) [with _Tp = CDetector; _Dp = std::default_delete<CDetector>; std::unique_ptr<_Tp, _Dp>::pointer = CDetector*; typename std::remove_reference<_To>::type = std::default_delete<CDetector>]
       unique_ptr(pointer __p,
       ^
/usr/include/c++/4.8/bits/unique_ptr.h:151:7: note:   candidate expects 2 arguments, 3 provided
/usr/include/c++/4.8/bits/unique_ptr.h:146:7: note: std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>::pointer, typename std::conditional<std::is_reference<_Dp>::value, _Dp, const _Dp&>::type) [with _Tp = CDetector; _Dp = std::default_delete<CDetector>; std::unique_ptr<_Tp, _Dp>::pointer = CDetector*; typename std::conditional<std::is_reference<_Dp>::value, _Dp, const _Dp&>::type = const std::default_delete<CDetector>&]
       unique_ptr(pointer __p,
       ^
/usr/include/c++/4.8/bits/unique_ptr.h:146:7: note:   candidate expects 2 arguments, 3 provided
/usr/include/c++/4.8/bits/unique_ptr.h:141:7: note: std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Tp, _Dp>::pointer) [with _Tp = CDetector; _Dp = std::default_delete<CDetector>; std::unique_ptr<_Tp, _Dp>::pointer = CDetector*]
       unique_ptr(pointer __p) noexcept
       ^
/usr/include/c++/4.8/bits/unique_ptr.h:141:7: note:   candidate expects 1 argument, 3 provided
/usr/include/c++/4.8/bits/unique_ptr.h:135:17: note: constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr() [with _Tp = CDetector; _Dp = std::default_delete<CDetector>]
       constexpr unique_ptr() noexcept
                 ^
/usr/include/c++


=== 
Any idea what the issue is and how I might address it? I am not an experienced Linux user so I appreciate any suggestions you have.

**Comment by Nuzhny007** [comment]
Hi!
You can try to use raw pointer on the CDetector (without unique_ptr).

**Comment by HanWu1** [comment]
@Atarashii   Hello,I heard that you  met one  problem that I troubled:
CMakeFiles/MultitargetTracker.dir/build.make:62: recipe for target 'CMakeFiles/MultitargetTracker.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MultitargetTracker.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MultitargetTracker.dir/all' failed
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

i have no idea where to start to fix this.please  give me one hand that how you solve it? thank you very much!

**Comment by HanWu1** [comment]
hello,as i make Multitarget-tracker/build ,i meet the problem follow:
Scanning dependencies of target MultitargetTracker
[  1%] Building CXX object CMakeFiles/MultitargetTracker.dir/main.cpp.o
[  3%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/BaseDetector.cpp.o
[  5%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/MotionDetector.cpp.o
[  7%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o
/home/zyb/code/Multitarget-tracker/Detector/BackgroundSubtract.cpp: In constructor ‘BackgroundSubtract::BackgroundSubtract(BackgroundSubtract::BGFG_ALGS, int, int, int, int, int, int)’:
/home/zyb/code/Multitarget-tracker/Detector/BackgroundSubtract.cpp:40:26: error: ‘createBackgroundSubtractorCNT’ is not a member of ‘cv::bgsegm’
             m_modelOCV = cv::bgsegm::createBackgroundSubtractorCNT(15, true, 15 * 60, true);
                          ^
CMakeFiles/MultitargetTracker.dir/build.make:134: recipe for target 'CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o' failed
make[2]: *** [CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MultitargetTracker.dir/all' failed
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2


i have install opencv with opencv-contrib,while cmake,i set USE_OCV_BGFG, USE_OCV_KCF and USE_OCV_UKF,,then what should i do,please?thank you very much .

**Comment by HanWu1** [comment]
@RedOne88 hello,  have you solved the problem?i also meet it ,can you me ?Thanks you!

**Comment by Nuzhny007** [comment]
Hi!
Try to set  USE_OCV_BGFG=OFF in CMake before compilation (and USE_OCV_KCF and USE_OCV_UKF).
Function createBackgroundSubtractorCNT contains in opencv_contrib repository. I think than you dosn't compile it.

**Comment by HanWu1** [comment]
@Nuzhny007 Mr Smorodov,my workspace is ubuntu 16.04+ opencv3.2.0 (+opencv-contrib3.2.0),
(1)just now i cmake-gui,and configure (Multitarget-tracker/build)  get the  follow : 
The C compiler identification is GNU 4.9.3
The CXX compiler identification is GNU 4.9.3
Check for working C compiler: /usr/bin/cc
Check for working C compiler: /usr/bin/cc -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /usr/bin/c++
Check for working CXX compiler: /usr/bin/c++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - not found
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - found
Found Threads: TRUE  
Found CUDA: /usr/local/cuda (found suitable exact version "8.0") 
Found OpenCV: /usr/local (found version "3.2.0") 
Looking for C++ include opencv2/bgsegm.hpp
Looking for C++ include opencv2/bgsegm.hpp - found
Configuring done
 
(2)then i generate,
Generate done 
(3)then i close cmake-gui, i go to Multitarget-tracker/build,and run make (make):
lvp@ciisr1307-ThinkStation-P510:~/Multitarget-tracker/build$ make
Scanning dependencies of target MultitargetTracker
[  1%] Building CXX object CMakeFiles/MultitargetTracker.dir/main.cpp.o
[  3%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/BaseDetector.cpp.o
[  5%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/MotionDetector.cpp.o
[  7%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o
/home/lvp/Multitarget-tracker/Detector/BackgroundSubtract.cpp: In constructor ‘BackgroundSubtract::BackgroundSubtract(BackgroundSubtract::BGFG_ALGS, int, int, int, int, int, int)’:
/home/lvp/Multitarget-tracker/Detector/BackgroundSubtract.cpp:40:26: error: ‘createBackgroundSubtractorCNT’ is not a member of ‘cv::bgsegm’
             m_modelOCV = cv::bgsegm::createBackgroundSubtractorCNT(15, true, 15 * 60, true);
                          ^
CMakeFiles/MultitargetTracker.dir/build.make:134: recipe for target 'CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o' failed
make[2]: *** [CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/MultitargetTracker.dir/all' failed
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
 
the above is what i do,can you help me ,thank you

**Comment by Nuzhny007** [comment]
The createBackgroundSubtractorCNT function is in opencv_contrib repository bgsegm module, here:
https://github.com/opencv/opencv_contrib/blob/master/modules/bgsegm/include/opencv2/bgsegm.hpp#L240
Check please this file in your copy of the opencv_contrib sources.

**Comment by HanWu1** [comment]
thanks very much. now i have changed bgsegm.hpp ,and begin to make the opencv3.2.0 and opencv-contrib3.2.0 agin.

**Comment by HanWu1** [comment]
@Smorodov Mr Smorodov，i feel so sorry that trouble you again. may i ask you about your workspace (opencv version, opencv_contrib-version, ubuntu-version and so on),i have found that opencv-3.2.0 with opencv_contrib-3.2.0 is not enough to run the project, there is no some numbers of cv::bgsegm, cv:dnn,and so on; the moduls about bgsegm, dnn is diffrernt in diffrernt opencv_contrib-version. 
just change the modules is not ok ,so what i can do is just to ask you about the version or the workspace you use. thank you .
