### ISSUE TITLE
how to use the USE_OCV_KCF?

### ISSUE THREAD

**Issue by xinsuinizhuan** [Smorodov/Multitarget-tracker#230]
I want to use KCF to track the object, but when  i set it ,it not use the kcf:
TrackerSettings settings;
		settings.SetDistance(tracking::DistJaccard);
		settings.m_kalmanType = tracking::KalmanLinear;
		settings.m_filterGoal = tracking::FilterCenter;
		settings.m_lostTrackType = tracking::TrackNone; // Use KCF tracker for collisions resolving
		settings.m_matchType = tracking::MatchHungrian;
		settings.m_dt = 0.3f;                           // Delta time for Kalman filter
		settings.m_accelNoiseMag = 0.2f;                // Accel noise magnitude for Kalman filter
		settings.m_distThres = 0.7f;                    // Distance threshold between region and object on two frames
		settings.m_minAreaRadiusPix = frame.rows / 20.f;
		settings.m_maximumAllowedSkippedFrames = cvRound(2 * m_fps); // Maximum allowed skipped frames
		settings.m_maxTraceLength = cvRound(3 * m_fps);      // Maximum trace length

it need to set user_ocv_kcf, then i could use the kcf:
![图片](https://user-images.githubusercontent.com/40679769/84563896-7dc2c100-ad91-11ea-85b6-90e51f109657.png)

**Comment by Nuzhny007** [comment]
Hi!
1. Do you have installed opencv_contrib?
2. Show me, plz, build/CMakeCache.txt
