### ISSUE TITLE
Are there something bugs in Kalman.cpp?

### ISSUE THREAD

**Issue by xzou999** [Smorodov/Multitarget-tracker#246]
In function TKalmanFilter::CreateLinearAcceleration(cv::Rect_<track_t> rect0, Point_t rectv0), 

1. m_linearKalman.transitionMatrix was assigned only 11x12 elements?
2. in m_linearKalman.processNoiseCov assignment, only 11 elements in first row, does it right?

**Comment by Nuzhny007** [comment]
Thank you for help!
Fix: https://github.com/Smorodov/Multitarget-tracker/pull/247
