### ISSUE TITLE
compile error with CUDA 10.1, cuDNN 7.5, TensorRT 5.1.5

### ISSUE THREAD

**Issue by j2innet** [Smorodov/Multitarget-tracker#249]
i had this error. i guess is tensorrt version is too low? 

compile error with CUDA 10.1, cuDNN 7.5, TensorRT 5.1.5

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(20): error: member function declared with "override" does not override a base class member
/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.cu(77): error: identifier "PluginTensorDesc" is undefined
/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(49): error: identifier "IPluginV2IOExt" is undefined

for more detail i attach the terminal output below..

does anyone can suggest the root cause? 
thanks. 

`[ 26%] Built target mtracking
[ 75%] Built target yolo_lib
[ 76%] Building NVCC (Device) object src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir/yolo_rt_lib_generated_mish.cu.o
/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(12): error: not a class or struct name

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(20): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(25): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(27): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(29): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(31): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(33): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(35): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(37): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(39): error: identifier "PluginTensorDesc" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(39): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(43): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(45): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(47): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(49): error: identifier "IPluginV2IOExt" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(49): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(51): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(53): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(55): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(57): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(59): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(61): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(64): error: identifier "PluginTensorDesc" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(64): error: identifier "PluginTensorDesc" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(64): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(66): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(40): error: name followed by "::" must be a class or namespace name

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(88): error: identifier "IPluginV2IOExt" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(88): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::createPlugin"

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(88): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(90): error: identifier "IPluginV2IOExt" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(90): error: return type is not identical to nor covariant with return type "nvinfer1::IPluginV2 *" of overridden virtual function "nvinfer1::IPluginCreator::deserializePlugin"

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.h(90): error: member function declared with "override" does not override a base class member

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.cu(77): error: identifier "PluginTensorDesc" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.cu(77): error: identifier "PluginTensorDesc" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.cu(105): error: identifier "IPluginV2IOExt" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.cu(179): error: identifier "IPluginV2IOExt" is undefined

/home/nuvo/git/src/Multitarget-tracker/src/Detector/tensorrt_yolo/mish.cu(186): error: identifier "IPluginV2IOExt" is undefined

38 errors detected in the compilation of "/tmp/tmpxft_000013bd_00000000-6_mish.cpp1.ii".
CMake Error at yolo_rt_lib_generated_mish.cu.o.cmake:275 (message):
  Error generating file
  /home/nuvo/git/src/Multitarget-tracker/build/src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir//./yolo_rt_lib_generated_mish.cu.o

src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir/build.make:1239: recipe for target 'src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir/yolo_rt_lib_generated_mish.cu.o' failed
make[2]: *** [src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir/yolo_rt_lib_generated_mish.cu.o] Error 1
CMakeFiles/Makefile2:314: recipe for target 'src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir/all' failed
make[1]: *** [src/Detector/tensorrt_yolo/CMakeFiles/yolo_rt_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Nuzhny007** [comment]
Show, plz, variable TensorRT_INCLUDE_DIR from CMakeCache.txt in your build directory

**Comment by j2innet** [comment]
hi Nuzhny, thanks for reply. 

here's the info as per requested. 

//Path to a file.
TensorRT_INCLUDE_DIR:PATH=/opt/TensorRT-5.1.5.0/include

//Path to a library.
TensorRT_LIBRARY:FILEPATH=/opt/TensorRT-5.1.5.0/lib/libnvinfer.so

//No help, variable specified on the command line.
TensorRT_ROOT:UNINITIALIZED=/opt/TensorRT-5.1.5.0

**Comment by Nuzhny007** [comment]
So, it's really problem in TensorRT version. In TensorRT 5.1 absent IPluginV2IOExt class: https://github.com/NVIDIA/TensorRT/blob/release/5.1/include/NvInfer.h

And in latest TensorRT: https://github.com/NVIDIA/TensorRT/blob/release/7.1/include/NvInferRuntimeCommon.h#L641
But this class is only Interface (pure abstract class). Try to copy it from 7.1 to misc.h before 12 line ( class MishPlugin: public IPluginV2IOExt ).

**Comment by Nuzhny007** [comment]
Same issue: https://github.com/enazoe/yolo-tensorrt/issues/51

**Comment by j2innet** [comment]
> Same issue: https://github.com/enazoe/yolo-tensorrt/issues/51
> 
> 

Good reference. 
They fixed by changing the base class to IPluginV2
I will try and update here.

**Comment by j2innet** [comment]
> Same issue: [enazoe/yolo-tensorrt#51](https://github.com/enazoe/yolo-tensorrt/issues/51)

renaming can't fix it. 
bump into other error, i go to github tensorrt to look up those class name, at least need trt 6.0.1.5
so now i readjust my environment and try again. 

Distro version=Ubuntu 18.04
Kernel version=5.4.0
CUDA version=10.1.105
OPENCV version=3.2.0
OPENCV CUDA version=NO
CUDNN version=7.6.5.32
TENSORRT version=6.0.1.5


redo cmake

cmake .. -DUSE_OCV_BGFG=ON -DUSE_OCV_KCF=ON -DUSE_OCV_UKF=ON -DBUILD_YOLO_LIB=ON -DBUILD_YOLO_TENSORRT=ON -DBUILD_ASYNC_DETECTOR=ON -DBUILD_CARS_COUNTING=ON -DTensorRT_ROOT=/opt/TensorRT-6.0.1.5
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable exact version "10.1") 
-- Found OpenCV: /opt/opencv-3.4.5 (found version "3.4.5") 
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so (found version "7.6") 
-- Found TensorRT: /opt/TensorRT-6.0.1.5/lib/libnvinfer.so (found version "..") 
-- Looking for C++ include opencv2/bgsegm.hpp
-- Looking for C++ include opencv2/bgsegm.hpp - found
-- Configuring done
-- Generating done
-- Build files have been written to: /media/nuvo/DATA/home/nuvo/git/src/Multitarget-tracker/build

new error for make below. 

[ 65%] Built target mtracking
[ 67%] Building CXX object src/Detector/CMakeFiles/mdetection.dir/OCVDNNDetector.cpp.o
/media/nuvo/DATA/home/nuvo/git/src/Multitarget-tracker/src/Detector/OCVDNNDetector.cpp: In member function ‘virtual bool OCVDNNDetector::Init(const config_t&)’:
/media/nuvo/DATA/home/nuvo/git/src/Multitarget-tracker/src/Detector/OCVDNNDetector.cpp:161:57: error: no match for ‘operator=’ (operand types are ‘std::vector<std::__cxx11::basic_string<char> >’ and ‘std::vector<cv::String>’)
         m_outNames = m_net.getUnconnectedOutLayersNames();
                                                         ^

**Comment by Nuzhny007** [comment]
Ah, OpenCV 3!
In OpenCV 4: cv::Ptr = std::shared_ptr and cv::String == std::string. But in OpenCV 3 they have custom implementation. A fast decisions:
1. change type of m_outNames from std::vector<std::string> to std::vector<cv::String>
or
2. Write loop over m_net.getUnconnectedOutLayersNames() with manual push_back to m_outNames
