### ISSUE TITLE
could not transfer from initializer to SPSettings; could not open "..\Debug\mtracking.lib"

### ISSUE THREAD

**Issue by HaronCHou** [Smorodov/Multitarget-tracker#264]
Hi~
I'm trying to run this without yolo, just background subtraction based tracking algorithm, and meeting two errors, could you help me with this? Thanks. 

The following is my cmake details. 
------------------------------
G:\python based algo\Multitarget-tracker\build>cmake_vs2015.bat
G:\python based algo\Multitarget-tracker\build>cd ..
G:\python based algo\Multitarget-tracker>cd build
G:\python based algo\Multitarget-tracker\build>cmake.exe . ..  -G "Visual Studio 14 2015 Win64"           -DOpenCV_DIR=F:/opencv4.1.0/opencv/build           -DUSE_OCV_BGFG=OFF           -DUSE_OCV_KCF=OFF            -DUSE_OCV_UKF=OFF            -DSILENT_WORK=OFF           -DBUILD_EXAMPLES=ON           -DBUILD_ASYNC_DETECTOR=ON           -DBUILD_CARS_COUNTING=OFF           -DBUILD_YOLO_LIB=OFF           -DBUILD_YOLO_TENSORRT=OFF
-- Selecting Windows SDK version  to target Windows 10.0.16299.
-- Found OpenMP_C: -openmp
-- Found OpenMP_CXX: -openmp
-- Found OpenMP: TRUE
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc14
-- OpenCV STATIC: OFF
-- Found OpenCV 4.1.0 in F:/opencv4.1.0/opencv/build/x64/vc14/lib
-- You might need to add F:\opencv4.1.0\opencv\build\x64\vc14\bin to your PATH to be able to run your applications.
-- Looking for C++ include opencv2/bgsegm.hpp
-- Looking for C++ include opencv2/bgsegm.hpp - not found
-- Configuring done
-- Generating done
-- Build files have been written to: G:/python based algo/Multitarget-tracker/build

G:\python based algo\Multitarget-tracker\build>cmake.exe --build . -j 6 --config Release
Microsoft (R) 生成引擎版本 14.0.23107.0
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Building Custom Rule G:/python based algo/Multitarget-tracker/src/Detector/CMakeLists.txt
  Building Custom Rule G:/python based algo/Multitarget-tracker/thirdparty/inih/CMakeLists.txt
  Building Custom Rule G:/python based algo/Multitarget-tracker/src/Tracker/CMakeLists.txt
  BaseDetector.cpp
  ini.c
  object_types.cpp
  INIReader.cpp
  Ctracker.cpp
------------------------------------------------------
error：
G:\python based algo\Multitarget-tracker\src\Tracker\Ctracker.cpp(14): error C2440: “初始化”: 无法从“initializer list”转换为“SPSettings” [G:\python based algo\Multitarget-tracker\build\src\Tracker\mtracking.vcxproj]
![Snipaste_2020-11-27_09-59-38](https://user-images.githubusercontent.com/22512646/100402468-49209880-3097-11eb-9ca0-9edfb6fad51b.png)

**Comment by HaronCHou** [comment]
Hi, finally got it ! 
win10, visual studio 2015.  My coding is not good. Don't know why this is invalid.

![Snipaste_2020-11-27_10-42-55](https://user-images.githubusercontent.com/22512646/100404843-550f5900-309d-11eb-827e-5efccec51c3a.png)

**Comment by Nuzhny007** [comment]
Hi!
Problem is in vs 2015 and old C++ standart. Instead:
`SPSettings spSettings = { settings.m_distThres, 12 };`
you can write:

```
SPSettings spSettings;
spSettings.m_distThres = settings.m_distThres;
spSettings.m_maxHistory = 12;
```
