### ISSUE TITLE
How to use the voc training dataset

### ISSUE THREAD

**Issue by one-cai-ji** [Smorodov/Multitarget-tracker#275]
Hello, I want to use the yolov4 model trained on the voc data set, but I tried to change the parameter settings in the nameFile in the code, but it did not work. So can you tell me what other changes I should make

**Comment by Nuzhny007** [comment]
Hi!
If do you use Darknet backend then check this parameter - set YOLOv4 instead ScaledYOLOv4: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/examples.h#L607
And change path to the cfg and weight file in same case. For YOLO v4: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/examples.h#L623

**Comment by one-cai-ji** [comment]
Thank you very much for your patient answer. 
In the example of CarsCounting.exe one parameter is -n = ../../data/coco.names,But when I use darknet to train my own data set, I use the VOC data set. There is no category I want in coco.names, so should I change this parameter to voc.names?

**Comment by Nuzhny007** [comment]
Yes,  -n=../../data/voc.names    or        --names=../../data/voc.names

And do not use spaces around '='
