### ISSUE TITLE
How do I use the own class names?

### ISSUE THREAD

**Issue by Yooyi0401** [Smorodov/Multitarget-tracker#280]
When I put the own "names", I sure that m_classNames get the string.
However, when check m_classNames with FillTypesMap, it always alert. It seems like that the bool need to be false and I can get correct.
How do I fix them?
![image](https://user-images.githubusercontent.com/49556328/104674350-7811cd00-571e-11eb-93ab-a155e801012f.png)
![image](https://user-images.githubusercontent.com/49556328/104674319-68928400-571e-11eb-91b8-175ec4b6b4df.png)

**Comment by Nuzhny007** [comment]
Sorry, my bad. Fixed: https://github.com/Smorodov/Multitarget-tracker/pull/281
Get, plz, a new version with fix.

**Comment by Yooyi0401** [comment]
Thank you very much QAQ
