### ISSUE TITLE
Configure CMakeLists problem

### ISSUE THREAD

**Issue by 17520299** [Smorodov/Multitarget-tracker#287]
Hi, i'm a newbie in this field.
I have a problem when i configure CMakeLists.txt.
![a](https://user-images.githubusercontent.com/71239193/106541020-b6d3bf80-6533-11eb-8c95-562c6cbd7023.png)
I installed cmake, open_cv and opencv_contrib too but i don't know how to configure CMakeLists.txt.
And my PC is running with AMD GPUs, is it possible to run cuda?
Please help me!!! Thanks you.

**Comment by Nuzhny007** [comment]
Hi!
Do you use cmake from terminal or with cmake-gui? 
In terminal: cmake <...some params> -DOpenCV_DIR=c:/path/to/opencv/
In cmake gui select path to opencv installation folder manually

**Comment by Nuzhny007** [comment]
> And my PC is running with AMD GPUs, is it possible to run cuda?

It's a good question. AMD has a ROCm project for compilation CUDA code. But I never use it for this project.

**Comment by 17520299** [comment]
Did you use ubuntu or windows when you config it? Because ROCm project only in Ubuntu, Visual Studio IDE only in Windows!!!

**Comment by 17520299** [comment]
Yesterday, I used Window but today I use Ubuntu because I read ROCm project run only in Linux. When I config CMakeLists.txt, PC notify me this message.
![Screenshot from 2021-02-03 11-10-03](https://user-images.githubusercontent.com/71239193/106697144-c7a63300-6610-11eb-9919-6fb00ad1c563.png)

**Comment by Nuzhny007** [comment]
OpenCV_DIR - it's build or install directory, not sources.

**Comment by Nuzhny007** [comment]
>Did you use ubuntu or windows when you config it? Because ROCm project only in Ubuntu, Visual Studio IDE only in Windows!!!
I'm using both systems but I don't have a AMD's GPU

**Comment by 17520299** [comment]
When I config in Window, I used cmake -DOpenCV_DIR=/path/to/opencv/ and it is successful but it occur an error about visual studio 2019.
Whether this command line which i used wrong?

**Comment by Nuzhny007** [comment]
Example.

1. I have directory "libraries" and make
```
cd libraries
 git clone <...>opencv.git
 git clone <...>opencv_contrib.git
mkdir opencv_release
cd opencv_release
cvmake . ../opencv -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules
make -j10

```
2. In another directory "projects":
```
cd projects
git clone <...>Multitarget-tracker.git
cd Multitarget-tracker
mkdir build
cd build
cmake . -DCMAKE_BUILD_TYPE=Release -DOpenCV_DIR=../../libraries/opencv_release
make -j10

```

And in your case (both with Linux and Windows) it would work like this

**Comment by 17520299** [comment]
Excuse me, I have a question.
If i had a trained-model detection. I wanna replace it into your code so i need to install all environment?

**Comment by Nuzhny007** [comment]
>If i had a trained-model detection. I wanna replace it into your code so i need to install all environment to run your project? Because my mentor say it can be run without Nvidia's GPU.

Actually not. In my code GPU used direct in two cases: with Darknet detector and with TensorRT detector. You can disable all nvidia dependencies on cmake with options: -DBUILD_YOLO_LIB=OFF and -DBUILD_YOLO_TENSORRT=OFF

A simple way to add your custom detector:
1. Add new detector id in enum: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/common/defines.h#L87
2. Implement your detector with common interface derived from BaseDetector: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/Detector/BaseDetector.h#L9
3. Create instance of your detector in fabric: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/Detector/BaseDetector.cpp

**Comment by 17520299** [comment]
> Example.
> 
> 1. I have directory "libraries" and make
> 
> ```
> cd libraries
>  git clone <...>opencv.git
>  git clone <...>opencv_contrib.git
> mkdir opencv_release
> cd opencv_release
> cvmake . ../opencv -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules
> make -j10
> ```
> 
> 1. In another directory "projects":
> 
> ```
> cd projects
> git clone <...>Multitarget-tracker.git
> cd Multitarget-tracker
> mkdir build
> cd build
> cmake . -DCMAKE_BUILD_TYPE=Release -DOpenCV_DIR=../../libraries/opencv_release
> make -j10
> ```
> 
> And in your case (both with Linux and Windows) it would work like this
Excuse me, in step 1: when i've just done cmake . -... i continue with make -j10 but cmd show make: *** no targets specified and no makefile found. The same error happened with step 2.(make -j10)
This command is really important, isn't it?

**Comment by Nuzhny007** [comment]
You can build projects with cmake:
`
cmake --build .`
