### ISSUE TITLE
How to get id of track working with yolo

### ISSUE THREAD

**Issue by muratayoshio** [Smorodov/Multitarget-tracker#291]
Hi Andrey 
First that all congratz, amazing Job you have done..

I'm currently working with Yolo v4 for detection, using the settings.ini file but the video doesn´t show any track identification (the detection is perfect by the way), 
the CSV output doesn´t show any track id...What I'm doing wrong??

the command line in Linux I 'm using is:
./MultitargetTracker ../data/videoOrig.mp4 -e=5 -a=0 -0=output.avi -r=file.csv -g=1 -sl=1 -s=../data/settings.ini

Thank you in advance and congrtz again, superb job!!

**Comment by Nuzhny007** [comment]
So, some questions:
1. Without settings file a tracking works correctly?
2. You write -zero for output: "-0=output.avi"   It need to write o-small: "-o=output.avi"

**Comment by muratayoshio** [comment]
Thanks
Trying without settings the generated video output only detections no
tracking
And it was a typho , I put -o correctly and indeed it generates the
detections on video and in csv

**Comment by Nuzhny007** [comment]
So, what is the main problem now? Do you can show result video with incorrect tracking?

**Comment by muratayoshio** [comment]
Thank you Andrey,
 Video and csv output is only providing information about detection:

(This is part of the csv results)
4,truck,1138,129,62,76,0.548438,
--
4,car,852,231,125,85,1.0682,
4,car,1089,186,71,60,1.05652,
4,car,616,321,206,135,1.07575,
4,car,962,188,80,57,1.03403,
4,car,590,427,317,266,1.02435,
4,car,1176,346,249,129,1.03003,
4,car,1645,468,276,151,1.00739,
4,car,8,626,370,383,0.949672,
...

There is no information, no results of tracking... (e.g. IDs )

Thank you for your help

**Comment by Nuzhny007** [comment]
>Thank you Andrey,

I'm Sergey.

>There is no information, no results of tracking... (e.g. IDs )

You can change one parameter in source code - set false: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L31
Or write results in custom format.

**Comment by muratayoshio** [comment]
Thank you Sergey(sorry for have changed your name before)
After the change its necessary to remake (rebuild) the entire solution isn´t??

**Comment by muratayoshio** [comment]
I just want to obtain the Id and class of the track, 
Something like this:
https://github.com/Smorodov/Multitarget-tracker/issues/181#issuecomment-576155688

Using Yolo customized detector

Running this command:

./MultitargetTracker ../data/videoOrig.mp4 -e=5 -a=0 -o=output.avi -r=output.csv -g=1 -sl=1 -s=../data/settings.ini

But only the detections results appear (in video and CSV file):

4,bus,1045,516,79,27,0.820545,
4,motorbike,255,517,26,14,0.71068,
4,motorbike,685,744,31,14,0.683672,
4,motorbike,1265,703,39,15,0.535062,
4,motorbike,1934,754,36,14,0.697107,
4,motorbike,378,700,33,16,0.621178,
4,motorbike,964,734,35,16,0.661596,
4,motorbike,1103,576,28,9,0.519553,

csv should be like:
4,**Object_ID**,bus,1045,516,79,27,0.820545,
4,**Object_ID**,motorbike,255,517,26,14,0.71068


It's necessary to change the source code?? Thank you in advance...

**Comment by Nuzhny007** [comment]
Fill free for changing format! Here: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/VideoExample.h#L115
You can write:
```

m_resCSV << frame.first << delim << detect.m_trackID << delim << TypeConverter::Type2Str(detect.m_type) << delim << detect.m_rect.x << delim << detect.m_rect.y << delim <<
							detect.m_rect.width << delim << detect.m_rect.height << delim <<
							detect.m_conf << delim << std::endl;
```

**Comment by muratayoshio** [comment]
Perfect Sergey, it works writing to the CSV file the Track ID and the class!!.. :)

What if I want to print also the track id and the track tail in the video (actually the tail appears without -e=5 option)...currently only the class and the accuracy is printed in the generated video... Shall I edit to the open cv options within the same VideoExample.h ??

Thank you for ur help!

**Comment by Nuzhny007** [comment]
See you DrawTrack function in VideoExample.cpp. It has bool drawTrajectory parameter. So, you can set this parameter true in your code.

**Comment by muratayoshio** [comment]
It works perfectly...  Thank you so very much for your help!!

**Comment by kenrickfernandes** [comment]
Hello, how did you print out the track_id onto the video frames using the Yolo example?
