### ISSUE TITLE
CarsCouting Problem

### ISSUE THREAD

**Issue by 17520299** [Smorodov/Multitarget-tracker#295]
Excuse me, profressor. Cars Counting included measured velocity of vehicle function?
I haven't installed yolo_lib yet.Instead, I have a trained-model car detection by Yolo v4. So i can use it for Cars Counting? 
Thanks you, sir!

**Comment by Nuzhny007** [comment]
Yes, but it need some manual work. You must set pairs of coordinates for binding video frame in pixels to map in geographical coordinates: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L423
1. Save one frame from video and open it in image editor (gimp, ms paint etc);
2. Open Google Earth and find place with camera;
3. find 4 key points on frame and on map (points aren't on one straight line!);
4. Save coordinates in pixels and in degrees into vectors framePoints and geoPoints.

**Comment by 17520299** [comment]
Hi, prof!
In module CarsCouting, How can i configure the Road Line to count car on road?
and Is Configuration-4-key-point different with Road Line?

**Comment by 17520299** [comment]
Hi, prof!
In Cars Counting module, just number of all car and truck, etc across the line. 
I wanna show every kind of vehicles, can you show me where to config it in your code, prof?
Thanks you so much!!!

**Comment by Nuzhny007** [comment]
Hi!

>In module CarsCouting, How can i configure the Road Line to count car on road?

Here AddLine method: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/main.cpp#L49

>and Is Configuration-4-key-point different with Road Line?

Yes, it's different

>I wanna show every kind of vehicles, can you show me where to config it in your code, prof?

You can add any type to white list: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L355
Or you can remove all types of objects from white list

**Comment by 17520299** [comment]
Hi, prof!
![Screenshot from 2021-03-11 11-25-00](https://user-images.githubusercontent.com/71239193/110735588-aca48f80-825c-11eb-8aad-7c873745474f.png)
Can you show me how to config in step 2 and 3 with Yolov4 trained-model? Thanks you so much.

**Comment by 17520299** [comment]
Hi, prof!
If i have a YOLOv4 trained-vehicle model, instead of config belong to 3 step as you told me. 
I link my yolov4 weights, yolov4.cfg and yolov4.names into command line, be the same with your example. I can run modules CarsCounting, can't i?
Thanks you prof!

**Comment by Nuzhny007** [comment]
Hi!
Yes, you can. A 3 steps from another issue are for custom detector. If you want any existing detector with custom model then just set a model from command line and select inference framework.

**Comment by 17520299** [comment]
Hi, prof!
https://github.com/Smorodov/Multitarget-tracker/blob/a235980ff7059d4d1941f7f4760724a98b568cf1/cars_counting/CarsCounting.cpp#L196
Please explain for me about const TrackingObject& track!!! 
What does it mean and it included what inside?
Thanks you prof!

**Comment by Nuzhny007** [comment]
Here: https://github.com/Smorodov/Multitarget-tracker/blob/9e7c558535f890d3eecec4b395d869cc3e5fdb79/src/Tracker/track.h#L188
It a current state of the tracking object. And a full info about object contains CTrack class: https://github.com/Smorodov/Multitarget-tracker/blob/9e7c558535f890d3eecec4b395d869cc3e5fdb79/src/Tracker/track.h#L251

**Comment by 17520299** [comment]
Hi!!!!
Excuse me, prof.
I don't understand some line in your code.
There are :
> cv::Mat colorFrame;
> capture >> colorFrame;
and 
> m_trace.size()
what are they? and what value do they return?
Thanks you so much, prof!

**Comment by Nuzhny007** [comment]
```
cv::Mat colorFrame;
capture >> colorFrame;
```
This is capturing a new frame from file/camera.

`m_trace.size()`
Length of the trajectory

**Comment by 17520299** [comment]
Hi, prof!!!
https://github.com/Smorodov/Multitarget-tracker/blob/8282f258abe40e9ca9edb214809024b437cf9d30/src/Tracker/Ctracker.cpp#L56 
Excuse me. You can explain for me Update() function, can't you? 
And how is the flow of data(video) through the source code ? 
In my thinking, every frame of the video is splited and go through carscounting.cpp.
Example: frame --> gray scale --> draw detect --> drawtrack and velocity --> checkIntersection.
sorry prof about my questions because i is really a newbie in tracking, especially C/C++.
Hope you help me!

**Comment by Nuzhny007** [comment]
>Example: frame --> gray scale --> draw detect --> drawtrack and velocity --> checkIntersection

Gray scale don't used for neural networks based detector. In cars counting used a simple serial pipeline:
1. Capture frame
2. Detector -> regions with bounding box, type and score
3. Tracker.Update -> solving assignment problem with Hungarian algorithm or bipartite graph matching (new regions and old tracks), Kalman filter for predict a new coordinates
4. Draw results
5. Intersection

In another examples I used more complicated  pipeline with multithreading.

**Comment by 17520299** [comment]
Hi, prof!
I have a same problem with CarsCounting modules in 2 computer(one have cuda(Yolo_lib=on) and the other has not(yolo_lib=off).
2 Computer gave me a same result.
![Screenshot from 2021-03-20 13-59-24](https://user-images.githubusercontent.com/71239193/111862221-7f579000-8986-11eb-825b-14fa33269bb4.png)
Can you explain this problem, prof!
Thanks you very much!

**Comment by Nuzhny007** [comment]
Use -inf=opencv command line parameter

**Comment by Nuzhny007** [comment]
Use -inf=opencv command line parameter

**Comment by 17520299** [comment]
Hello!!
It's the same return, prof. 
Do you think cfg, names file and libgtk2.0-dev be problem?
> Use -inf=opencv command line parameter

**Comment by Nuzhny007** [comment]
1. Hm. Do you work through ssh?
If not then lets install libgtk or qt, reconfigure opencv and rebuild it.

2. You can rebuild only this project with -DSILENT_WORK=ON

**Comment by 17520299** [comment]
1. When i set -DSILENT_WORK=ON. It can't build successfully CarsCounting. if -DSILENT_WORK=OFF, it is successful. 
2. In PC which dont have cuda, i set YOLO_LIB=OFF although I have weights, cfg, names of YOLOv4 but it returns Darknet inference engine was not configured in Cmake. That mean I must set YOLO_LIB=ON to use CarsCounting? And i need to install darknet from alexeyAB in my PC?
3. VideoExample(face and pedestrian) is work normally.
4. what package is nescessary to build CarsCounting successfully?
Thanks you very much, prof!

**Comment by Nuzhny007** [comment]
Now I'm not at home and have only phone with slow mobile internet. And can't check this case. But the error on your previous screenshot says that you need install any graphical library. For example liggtk2.0-dev, reconfigure OpenCV in CMake with gtk, rebuild it. And all will work

**Comment by 17520299** [comment]
Hello, 
After installing libgtk2.0-dev packages, i have another problem with libcudnn_cnn_train.so.8.
![Screenshot from 2021-03-23 15-40-35](https://user-images.githubusercontent.com/71239193/112118000-854faa00-8bee-11eb-975e-8d8aa7cb53de.png)
Would you mind telling me what i should do next, prof?
Thank you so much.

**Comment by 17520299** [comment]
Hi, prof!
I have run CarsCounting module successfully, but there are 2 problems which occur in output video.
1. There are no type of objects which belong to each bbox.
2. Function velocity measurement cant work.
![Screenshot from 2021-03-23 19-34-42](https://user-images.githubusercontent.com/71239193/112149808-f5bbf280-8c11-11eb-9121-960d0b6689b8.png)

Now, i use my custom yolov4 weights instead of pre-trained from alexey. Do you think these problem cause the bug in my case??
Thanks you prof!

**Comment by 17520299** [comment]
> Hi, prof!
> I have run CarsCounting module successfully, but there are 2 problems which occur in output video.
> 
> 1. There are no type of objects which belong to each bbox.
> 2. Function velocity measurement cant work.
>    ![Screenshot from 2021-03-23 19-34-42](https://user-images.githubusercontent.com/71239193/112149808-f5bbf280-8c11-11eb-9121-960d0b6689b8.png)
> 
> Now, i use my custom yolov4 weights instead of pre-trained from alexey. Do you think these problem cause the bug in my case??
> Thanks you prof!
>
I know why that problem occurs because i didn't set geoCoordinate.(velocity measurement)
Thank you so much.

**Comment by 17520299** [comment]
Hi, prof! 
I has set geoCoordinate but it still cant display velocity measurement function.
Would you mind telling me what happened, please!
Thank you so much!

**Comment by Nuzhny007** [comment]
Hi!
Enable code here - set #if 1 instead #if 0: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L421

And here you can add advanced logs in stdout to control that all parameters is correct: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L236

**Comment by 17520299** [comment]
Hi!
> And here you can add advanced logs in stdout to control that all parameters is correct: https://github.com/Smorodov/Multitarget-tracker/blob/master/cars_counting/CarsCounting.cpp#L236
>
What does it mean prof?? 
Thank you!

**Comment by Nuzhny007** [comment]
You can print into stdout period, distance etc. Some parameters witch do you want to see on frame. I can't  now write more logs - only on next week.

**Comment by Nuzhny007** [comment]
You can print into stdout period, distance etc. Some parameters witch do you want to see on frame. I can't  now write more logs - only on next week.

About performance: check your model with Multitarget-tracker example with tensorrt backend and set option -a=1
In this case you can get a maximum speed

**Comment by 17520299** [comment]
Hi! I understand what you say.
I can run your whole CarsCounting project successfully.
Thank you for your support so much.
Best regard!

**Comment by 17520299** [comment]
> About performance: check your model with Multitarget-tracker example with tensorrt backend and set option -a=1
> In this case you can get a maximum speed
> 
How about yolo_lib prof! I can do it the same with -a=1

**Comment by Nuzhny007** [comment]
Hi!
I'm now with my laptop. And yes - you can try use Multitarget-tracker with any backend (darknet, tensorrt, opencv_dnn etc) and with  -a=1 it will up to 2 times faster. If this result will prefer for you then I can refactor CarsCounting with some parallel pipeline

**Comment by 17520299** [comment]
Hi, 
When i use pre-trained yolov3, speed of video is faster than my custom yolov4.
although my yolov4 only have 4 classes and i have set -a=1.
Do you think what happened?
Thank you prof!

**Comment by 17520299** [comment]
Hi,  
> ![Screenshot from 2021-03-30 16-44-50](https://user-images.githubusercontent.com/71239193/113115065-3a5d1480-9236-11eb-8528-c9754cc76d1f.png)
> 
I wonder if a number of vehicles are too much as this, the fps is slow?
There are any idea for increasing fps in this case, prof!
Thank you so much!

**Comment by 17520299** [comment]
Hi, 
> ![Uploading Screenshot from 2021-03-31 16-15-16.png…]()
> ![Screenshot from 2021-03-31 16-16-47](https://user-images.githubusercontent.com/71239193/113121155-8ca13400-923c-11eb-91f2-0c203f8252d6.png)
> 
I used this option for CarsCouting, prof!

**Comment by Nuzhny007** [comment]
>I used this option for CarsCouting, prof!

Ok, I'll make it for CarsCounting also. And it will be faster

**Comment by 17520299** [comment]
Hi, prof!
If i wanna put a Text in a video, i need to write another function or only write a cv::putText at somewhere in your code?
Thank you so much!

**Comment by Nuzhny007** [comment]
Hi!
A big portion of refactoring CarsCounting module: https://github.com/Smorodov/Multitarget-tracker/pull/307
Read, plz, description of this PL and Files changed tab. Save your code before pulling a new updates.

**Comment by 17520299** [comment]
Hi prof,
I have a question to discuss with you.
Firestly, In CarsCoutning, if an vehicle try to turn left, right or back, the trajectory will be wrong. 
Secondly, the performance of GPUs in my laptop is so low. it only use 10-15% when i check it in task manager. If i wanna increase performance of GPUs upto 40% or more to improve CarsCouting's result, it is possible?
Can you show me some keywords or another tracking algorithm to find out the way to solve these problem?
Thanks you so much!

**Comment by Nuzhny007** [comment]
Hi!
1. Tt need to enable advanced debug info:  Pull the latest changes from this repository.
For enabling advanced info in CTracker.cop set: #define DRAW_DBG_ASSIGNMENT 1
Here: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/Tracker/Ctracker.cpp#L143
And after show me debug video video or screen shots with error.

2. Task manager don't show correctly GPU utilization. You need to use nvidia-smi utility, run it from command line: nvidia-smi -l
So on my laptop with Windows Intel core i7 + Nvidia GeForce 1060M:

GPU utilization about 70% with command line: MultitargetTracker.exe D:\data\vehicles\Relaxing_highway_traffic.mp4  -ef=0 -w=C:\work\home\mtracker\Multitarget-tracker\data\yolov4.weights -c=C:\work\home\mtracker\Multitarget-tracker\data\yolov4.cfg -inf=tensorrt -e=7 -a=0 -g=0
![Untitled](https://user-images.githubusercontent.com/5041357/115118299-2e4db280-9fab-11eb-819f-7d837981f849.png)

GPU utilization about 80% with command line: MultitargetTracker.exe D:\data\vehicles\Relaxing_highway_traffic.mp4  -ef=0 -w=C:\work\home\mtracker\Multitarget-tracker\data\yolov4.weights -c=C:\work\home\mtracker\Multitarget-tracker\data\yolov4.cfg -inf=tensorrt -e=7 -a=1 -g=0
![Untitled2](https://user-images.githubusercontent.com/5041357/115118306-3dccfb80-9fab-11eb-8ee9-cbab81403366.png)

**Comment by Nuzhny007** [comment]
And I think if you will not show and update the result window then GPU utilization will be more.

**Comment by 17520299** [comment]
Hi prof!
Firstly, These are some wrong trackings, you can see that the red line is drawn in the sky, purple line is in the rightside and the green one is in line 0 direction. 
![1](https://user-images.githubusercontent.com/71239193/115147658-3d556300-a086-11eb-8c56-c9633123aaa5.png)
Secondly, when i rebuild newest version, i encountered a problem that it cannot detect vehicle like this. can you explain me what happened?
![Untitled](https://user-images.githubusercontent.com/71239193/115147713-8efded80-a086-11eb-8901-d8b9172acea2.png)
Finally, the last time i checked GPU utilization is 84% by nvidia-smi.
Thank you so much!

**Comment by Nuzhny007** [comment]
Hi!
And whats about new debug window? Set, plz, #define DRAW_DBG_ASSIGNMENT 1 and show screen from this debug windows. And a part of log from console will be helpful. I need some advanced information for bugs fixing

**Comment by 17520299** [comment]
Hi!
It still don't show any logs in console. Two screens appeared and didn't run like this. 
![174768149_810877079807029_3343299503997997405_n](https://user-images.githubusercontent.com/71239193/115170765-a3c09c80-a0eb-11eb-8e7d-a3daf8b9ecf4.png)
Ps: i set -a=0.

**Comment by Nuzhny007** [comment]
Ok, it still not anought. More logs: Multitarget-tracker.exe <... your params...> 1>1.txt 2>2.txt
And after closing program show, plz, a content of the 1.txt and 2.txt

**Comment by 17520299** [comment]
Hi prof!
I have looked for what you changed in your code (latest version) for hours. 
I still do the same way as before and i try to build my previous version again succesfully while latest version cannot detect the vehicle as i mentioned in previous comment(tracks=0).
Please show me what you do to config it.
Thanks you so much!

**Comment by Nuzhny007** [comment]
Hi!
I'm using default settings: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/CarsCounting.cpp#L218
Or for concrete place with camera - concrete parameters

**Comment by 17520299** [comment]
Hi!
![image](https://user-images.githubusercontent.com/71239193/115399582-9225e480-a212-11eb-9f6e-794f76126ba1.png)
I see some elements in the dbgAssignment window. 
while the green, blue rectangle, and the red circle belong to each others is the tracking true. On the other hand, it is wrong.
And the pink rectangle is the last state which the detector save in the window, isn't it?
Why is detector not able to detect all vehicle in frame?
My model is problem? or what?
Please explain me, prof!
Thanks you so much.

**Comment by Nuzhny007** [comment]
Hi!
Red circle - current track size and position.
Margenta rectangle - latest detection from model on previous frames (tracking work only on Kalman prediction).
Green rectangle - current detection assigned to track.
Blue rectangle - current detection assigned to track but distance between track and detection is too big (dist > m_distThres).

I think, it can be select good parameters for your case, May be:
```

m_trackerSettings.m_kalmanType = tracking::KalmanLinear;
	m_trackerSettings.m_filterGoal = tracking::FilterRect;
	m_trackerSettings.m_lostTrackType = useDeepSORT ? tracking::TrackNone : tracking::TrackSTAPLE; // Use visual objects tracker for collisions resolving. Used if m_filterGoal == tracking::FilterRect
	m_trackerSettings.m_matchType = tracking::MatchBipart;
	m_trackerSettings.m_useAcceleration = false;                   // Use constant acceleration motion model
	m_trackerSettings.m_dt = m_trackerSettings.m_useAcceleration ? 0.05f : 0.4f; // Delta time for Kalman filter
	m_trackerSettings.m_accelNoiseMag = 0.2f;                     // Accel noise magnitude for Kalman filter
	m_trackerSettings.m_distThres = 0.8f;                         // Distance threshold between region and object on two frames
	m_trackerSettings.m_minAreaRadiusPix = -1.f;
	m_trackerSettings.m_minAreaRadiusK = 0.8f;

```
But I don't sure - need make some experiments.

The next big improvement - make tracking not in pixels coordinates on frame but on geo coordinates on Earth plane. It need a big portion of changes and refactoring. I'm planing this work in the nearest time.

**Comment by 17520299** [comment]
Hi prof!
My yolov4 cannot detect all vehicles in frame althrough i fined-tune some parameters TrackerSettings.
Do you think that my model is not good enough?
I have trained 600 pictures and 100 for test.
Thanks you so much!

**Comment by 17520299** [comment]
In latest release, i see some detect which have tag "unknown". 
I dont understand about it!

**Comment by Nuzhny007** [comment]
Hi!
1. For my test I'm using default pretrained YOLOv4 from AlexeyAB repository. But if you has frame with size significantly greater than input layer then you can split frame to crops and make detection.  Detector has parameter config.emplace("maxCropRatio", "-1"). Instead -1 you can set multiplier coefficient for crop size. For example: maxCropRatio = 2
If input layer has size 608x608 then crop size = 1216x1216. And FullHD frame 1920x1080 will be splatted to 4 crops with overlap. It will be slowed but more correctly.

2. "unknown" type may be if your types absent in this enum: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/common/object_types.h#L6
Add your type after obj_vehicle. And here his name: https://github.com/Smorodov/Multitarget-tracker/blob/master/src/common/object_types.cpp#L85

**Comment by 17520299** [comment]
Hi prof!
i use -bs=2 in carscounting and it cannot detect any vehicles on frame!
Can you show me why? 
Thanks you so much!!!

**Comment by Nuzhny007** [comment]
Hi!
Thanx, it was a bug.
Fixed: https://github.com/Smorodov/Multitarget-tracker/pull/325

**Comment by 17520299** [comment]
Hi, prof!
when i dive in Kalman Filter and Hungarian Algorithm, i have some questions.
1. can you explain me some parameters in your code about kalman filter as m_accelNoiseMag, m_minAreaRadiusPix, m_minAreaRadiusK? and m_distThres is IoU threshold for comparing similarity of object between 2 frame continuosly?
2. you only use IoU to compare similarity of object between 2 frames or another scores as shape score and convolutional cost?
3. in case, i have 1080p video, if i reduce  its resolution to 720p, performance is possible to increase? ps: i set maxcrop=4 with 1080p, some vehicles cannot be detected.
4. there're so many times the ID switch occur if 2 or 3 objects overlap to each other, i think that only IoU is not good enough.
Thanks you so much, and sorry if my english is bad!!!

**Comment by Nuzhny007** [comment]
Hi!

1. You can use google translate for our russian wiki: https://github.com/Smorodov/Multitarget-tracker/wiki/Fine-tuning-TrackerSettings

2. I'm using different scores for different cases. For example for tracking a small objects like birds or UAVs the best metric is a  DistCenters.

3. Now, resolution reduce don't give you a big performance. For best detection a small vehicles You need set maxCropRatio = 1 (but it will slow). Also you can use TensorRT backend with batch size = 2 or 4 and FP16 precision on GPU 20xx or 30xx

4.  Yes, IoU is not enough. For this case used DeepSORT. In this project you can use it here with re-id models from OpenVINO (your OpenCV must be compiled with OpenVINO support): https://github.com/Smorodov/Multitarget-tracker/blob/master/example/examples.h#L682

**Comment by 17520299** [comment]
Thank yvererverry much for this response!!!

**Comment by 17520299** [comment]
Hi prof!
Excuse me, can you explained me why period = min(2*m_fps, traceSize)
What does it mean?
(3.6f*m_fps)/period is time in real-time, isn't it? why 3.6f not another numbers?
Thanks you so much, prof!!!

**Comment by Nuzhny007** [comment]
> Excuse me, can you explained me why period = min(2*m_fps, traceSize)

2 seconds for speed calculation. This number must be small for calculating instantaneous velocity and big for error minimization. I'm using 2 seconds.

> (3.6f * m_fps)/period is time of object appear in real-time, isn't it? why 3.6f not another numbers?

3.6f - coefficient for converting velocity from meters/sec to km/h. 3.6 = 3600 seconds in hour / 1000 meters in km

**Comment by 17520299** [comment]
Hi, prof!
when i use KalmanLinear and KalmanUnscented. With KalmanLinear vehicles are still tracked as below while KalmanUnscented not, and objects moved out frame but the detection still appear in frame.
![linear](https://user-images.githubusercontent.com/71239193/125875889-236f1eaf-9835-4e85-a08a-7119821911db.jpg)
**Linear**
![unscented](https://user-images.githubusercontent.com/71239193/125875891-e3c686cc-879f-4fbb-8252-6bdd007e98c1.jpg)
**Unscented**
I read your Fine-tuning TrackSettings, you mentioned KalmanUnscented included acceleration more than Linear. Some articles say UnscentedKalman for non-linear, so i dont understand about what main different between KalmanLinear and KalmanUnscented in this case.
Please help me!!!
Thank you so much, prof!

**Comment by Nuzhny007** [comment]
I'm not sure that all my code with Uncented Kalman filer is correct. Linear is better

**Comment by 17520299** [comment]
Hi, prof!!!
I have a question about DistRects.
Which case you will use DistRects? and what is its reason?
Please answer me when you see my question!!!! Please!!!
Thanks you so much!!!

**Comment by Nuzhny007** [comment]
I used this distance for tracking small objects with background subtraction based detector. It works better that centers dist and IoU (Jaccard) distance for very small objects doesn't work.

**Comment by 17520299** [comment]
Thanks you so much prof for support me up to now! So i will close this issue.
Thanks you!!!
