### ISSUE TITLE
Export video output and trajectories output while processing

### ISSUE THREAD

**Issue by juanmanuelrq** [Smorodov/Multitarget-tracker#296]
Hi,

I am using your Multitarget-tracker

Could you help me with this question?, please

how can I export video output and trajectories output while processing

best regards

**Comment by Nuzhny007** [comment]
Hi!
You can set output in command line options: ./Multitarget-tracker <video_name> -o=res_video.mp4 -r=res.csv

**Comment by juanmanuelrq** [comment]
Hi @Nuzhny007 

Thanks for your answer and your attention

In my case, when I run this command

`./MultitargetTracker ../data/01PM_CARRERA50_CALLE14_20210217_1723.MP4 -e=5 -a=1 -o=01PM_CARRERA50_CALLE14_20210217_1723_out.avi -r=01PM_CARRERA50_CALLE14_20210217_1723_out.csv -g=1 -sl=1 -s=../data/settings.ini`

the file 01PM_CARRERA50_CALLE14_20210217_1723_out.csv is empty

![image](https://user-images.githubusercontent.com/29231800/109305855-54a56c00-780c-11eb-9d29-2ec19a9b4ffb.png)

best regards

**Comment by Nuzhny007** [comment]
Hi!
Log will write in ResultsLog destructor - after closing application. And on your screenshot application still works - waits key press

**Comment by juanmanuelrq** [comment]
Hi @Nuzhny007 

how can I write .csv result while the video is processing?

`./MultitargetTracker /root/sier/in.MP4 -e=5 -a=1 -o=out.avi -r=out.csv -g=1 -sl=1 -s=../data/settings.ini.base`

![image](https://user-images.githubusercontent.com/29231800/109575805-89414e00-7ac0-11eb-99d1-8f7bfc85d8f7.png)

**Comment by Nuzhny007** [comment]
I added: https://github.com/Smorodov/Multitarget-tracker/pull/297/commits/b6ba13e01216ab7221dc6f64097fc9f5d379732b
Try it, plz

**Comment by juanmanuelrq** [comment]
Hi @Nuzhny007 

I try your solution and I have and excelente result,

thank you very mucho for your help

![image](https://user-images.githubusercontent.com/29231800/109662195-cba67180-7b38-11eb-84cc-b034edbe2cee.png)

best regards
