### ISSUE TITLE
could you Add "make install" for compile? 

### ISSUE THREAD

**Issue by jcyhcs** [Smorodov/Multitarget-tracker#299]
hi,professor:

i use your cmake to compile the project, it works.  my application need libmtracking.so,  so  can you add make install  in your  cmakelist? it very usefull  ,thank you !

**Comment by Nuzhny007** [comment]
Hi!
Ok, I'll do it.

**Comment by Nuzhny007** [comment]
If you need only libraries than this PL will be useful: https://github.com/Smorodov/Multitarget-tracker/pull/300

**Comment by jcyhcs** [comment]
hi,professor!
em..., libs default install in /usr/local/lib,  but the include header header fils i also need, could you please make install the HEADER files?  thks

**Comment by Nuzhny007** [comment]
Here: https://github.com/Smorodov/Multitarget-tracker/pull/302
I hope it will work correctly. Now about 2 weeks I'm very busy and don't have any time for this project. Only small fixes
