### ISSUE TITLE
Running Cars Counting without GPU

### ISSUE THREAD

**Issue by BinhPham93** [Smorodov/Multitarget-tracker#305]
Dear professor,

I have tried to implement the CarsCounting code on my laptop (it does not have a GPU)
![4](https://user-images.githubusercontent.com/81282015/113135642-3221bc80-91d7-11eb-8017-fe3d93cf260a.JPG)

First I use Cmake to set up the file:
![1](https://user-images.githubusercontent.com/81282015/113135799-6b5a2c80-91d7-11eb-90bf-71981167adeb.JPG)

Then I build it with Microsoft Visual Studio Community 2019 (version 16.9.2)
![2](https://user-images.githubusercontent.com/81282015/113136035-b8d69980-91d7-11eb-9d85-f767c7a1e28f.JPG)

Lastly, I run the application file and got a notice:
![3](https://user-images.githubusercontent.com/81282015/113136120-d277e100-91d7-11eb-9450-4cece2402994.JPG)

Will it possible to use this model without the GPU? If it is, would you mind giving some instructions to set up the file? 

Thank you so much for your time.

**Comment by 17520299** [comment]
Hi, anh.
Cai nay phai chay tren cuda moi build duoc anh oi, luc truoc em cung tung thu roi ma khong duoc.

**Comment by BinhPham93** [comment]
> Hi, anh.
> Cai nay phai chay tren cuda moi build duoc anh oi, luc truoc em cung tung thu roi ma khong duoc.

Cam on ban nha. Minh cung thu chay tren Google Colab notebook, nhung no su dung python nen cung chua biet lam sao. Ban co' biet cach nao khac de chay tren cloud khong, chi minh voi?

**Comment by 17520299** [comment]
Xai terminal cua colab thi config giong nhu tren linux, nhung ma muon demo tren colab thi em khong biet.

**Comment by BinhPham93** [comment]
Minh thay co comment cung tung hoi tac gia co file python makefile khong nhung van chua thay upload. Phan object detection cua darknet thi minh da chay tren CPU duoc (kha la cham neu la video) nen minh cu nghi la code nay chay duoc. Cam on ban da cho minh biet (minh thu cung ca thang roi ma chua duoc, cung hoc duoc nhieu thu)!

**Comment by 17520299** [comment]
Em nghi se cai dat duoc, nhung ma gioi han thoi gian cua colab thi hoi kho. De em thu xem coi sao

**Comment by BinhPham93** [comment]
Neu ban chay duoc, cho minh biet voi nhe'!

**Comment by 17520299** [comment]
Chay duoc, nhung qua trinh config project hoi lau, dung terminal thi se duoc, nhung cai source code do can phai sua nhieu cho moi build len duoc.
luc demo se khong thay duoc video truc tiep(do em khong biet cach hien thi) nhung co the down video da demo ve may de xem.

**Comment by BinhPham93** [comment]
Vay thi qua ok roi. Chay lau thi khong sao, minh chi can no config duoc video roi minh download ve la duoc. Ban co the share cach sua the nao khong? Minh hoc ben xay dung, nen phan source code minh khong hieu het duoc. Minh co lop project yeu cau ap dung machine learning nen bua gio minh may mo Code de su dung. Email cua minh: phamngocbinh2403@gmail.com
That su cam on ban nhieu lam!
