### ISSUE TITLE
How to couple the points and track ID together

### ISSUE THREAD

**Issue by k-maheshkumar** [Smorodov/Multitarget-tracker#32]
I can see that the tracker works by assigning id to the tracks, but the ID is not assigned to the points togethers as an object, so that we can use it further.

I am expecting something like this,

track.object.m_trackID
track.object.rect
track.object.pt   <--- this point should get updated, as the object moves

Please help me with the same.

Thank you.

**----update----**
sorry, I just saw it. All info I wanted is in GetLastRect(). But Is there any possibility for changing RotatedRect instead of normal Rect ?. So, that we can use minarearect instead of boundingrect.

**Comment by Smorodov** [comment]
Not completely got what do you want. 
Check tracks plotting, each track have it's own ID and its points tail. 
Seems you can extract all necessary info you need learning tracks plotting method..

**Comment by Nuzhny007** [comment]
>But Is there any possibility for changing RotatedRect instead of normal Rect ?. So, that we can use minarearect instead of boundingrect.
It's good but will be work only with enabled LK tracking. If you want I can make this pull request.

**Comment by k-maheshkumar** [comment]
Yes please..  Make a pull request. I really want that feature..

Regards,
Mahesh Kumar Karikalan

---- Sergey Nuzhny wrote ----


But Is there any possibility for changing RotatedRect instead of normal Rect ?. So, that we can use minarearect instead of boundingrect.
It's good but will be work only with enabled LK tracking. If you want I can make this pull request.

**Comment by k-maheshkumar** [comment]
@Nuzhny007 I could see no pull request. Can you please give pull request at the earliest. I need to use RotatedRect in my project.

Thanks in advance.

**Comment by Nuzhny007** [comment]
Hi!
It's not so simple but work is in progress.

**Comment by Nuzhny007** [comment]
You can see my branch: https://github.com/Nuzhny007/Multitarget-tracker/tree/reg_type
Too many changes but new version isn't ready now.

**Comment by k-maheshkumar** [comment]
Thank you. I will check it out

**Comment by Nuzhny007** [comment]
Here: https://github.com/Smorodov/Multitarget-tracker/pull/147
