### ISSUE TITLE
Carscounting problem

### ISSUE THREAD

**Issue by lianglei68** [Smorodov/Multitarget-tracker#326]
In the carscounting example，how do I get the number of each type objects that intersect lines, and save the results as a CSV file? thank you

**Comment by Nuzhny007** [comment]
Hi!
You can add saving code here: https://github.com/Smorodov/Multitarget-tracker/blob/master/example/CarsCounting.cpp#L389
If method IsIntersect returns not zero value then write line with track.mID and track.m_type to csv file.
