### ISSUE TITLE
Would you please explain more detail how to run the code on both Windows and Linux? 

### ISSUE THREAD

**Issue by GodfreyLiu** [Smorodov/Multitarget-tracker#33]

**Comment by GodfreyLiu** [comment]
Hello,I download the code from your link, however I don't know how to run it. And  I wan to ask if it can be run on Windows System? Would you please teach me how to run the code on both Windows and Linux. Especially on Windows, because I am very beginner with programming, I think I need how to run the code on Windows first and forgive me that my question is simple. My email is liumg0617@gmail.com﻿

**Comment by Smorodov** [comment]
Hello, what do you have now?
What environment?
Have you visual studio installed?
What about OpenCV and CMAKE ?

**Comment by GodfreyLiu** [comment]
Hello, Thank you so much for your reply.

I have installed visual studio and OpenCV2.4.9 and CMAKE3.8.2.

When I download the CMAKE, it has .zip and .msi. and I download .msi
version and install it.

What should I do next step?

I am interested in programming and computer vision, but I it very hard for
me at beginning.






2017-06-01 18:19 GMT+09:00 Andrey Smorodov <notifications@github.com>:

**Comment by Smorodov** [comment]
​
 ScreenCaptureProject1.mp4
<https://drive.google.com/file/d/0Bxk3hR536PxSenhMQzhvLWduWk0/view?usp=drive_web>
​Just make a clip on how to build the app.

2017-06-01 14:50 GMT+03:00 GodfreyLiu <notifications@github.com>:

**Comment by Smorodov** [comment]
You need to update sources from repository, I just fixed an issue with conditional compilation.

**Comment by GodfreyLiu** [comment]
When I use CMAKE to compile, it shows following information
![image](https://cloud.githubusercontent.com/assets/29115458/26707550/96fa84ac-4780-11e7-9c56-0987b23e6f8a.png)
however I installed opencv in C:\opencv

**Comment by GodfreyLiu** [comment]
I solved this opencv problem.
But when I build the code, it still has a lot of errors
![image](https://cloud.githubusercontent.com/assets/29115458/26711705/48d8410c-479d-11e7-8896-d920b53c503d.png)
![image](https://cloud.githubusercontent.com/assets/29115458/26711709/5306741e-479d-11e7-8e11-e204289c6da3.png)
I think that I forget to download something.
could you give me some information?
Thank you.

**Comment by Smorodov** [comment]
You seems did not noticed that I wrote above.

> You need to update sources from repository, I just fixed an issue with conditional compilation.

**Comment by Nuzhny007** [comment]
I think that it can remove folder vs2015 from yours latest commit. It contains a compilations cache. 
> You need to update sources from repository, I just fixed an issue with conditional compilation.
