### ISSUE TITLE
velocity

### ISSUE THREAD

**Issue by Rahma-MNIFI** [Smorodov/Multitarget-tracker#331]
could you explain the workflow of velocity calculation plz? thanks

1. what is track.m_trace [xxxx] ?
2.  what track.m_trace.size() return ?
3.  what is m_fps  and why it is multiplied by 2 ?
4. what do you mean by 3.6f ?

![velocity](https://user-images.githubusercontent.com/78857777/124995136-cf925500-e03e-11eb-918f-d7af03dbd761.PNG)

**Comment by Nuzhny007** [comment]
1. Trajectory (set of points) on frame
2. It returns points count in trajectory
3. m_fps - frames per second for this video, "multiplied by 2" - I'm taking last 2 seconds of trajectory
4.  3.6f - coefficient for converting velocity from meters/sec to km/h
