### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by calderonsin** [Smorodov/Multitarget-tracker#333]
Hi Mr Smorodov, im trying to compile and Im having trouble. I run this command:
cmake . .. -DUSE_OCV_BGFG=ON -DUSE_OCV_KCF=ON -DUSE_OCV_UKF=ON -DBUILD_YOLO_LIB=ON -DBUILD_YOLO_TENSORRT=OFF -DBUILD_ASYNC_DETECTOR=ON -DBUILD_CARS_COUNTING=ON -DOpenCV_DIR=/usr/include/opencv
       make -j

 this error is shown:

In file included from /home/juccalderondo/Multitarget-tracker/src/Tracker/track.cpp:1:0:
/home/juccalderondo/Multitarget-tracker/src/Tracker/track.h:7:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
src/Tracker/CMakeFiles/mtracking.dir/build.make:120: recipe for target 'src/Tracker/CMakeFiles/mtracking.dir/track.cpp.o' failed
make[2]: *** [src/Tracker/CMakeFiles/mtracking.dir/track.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/juccalderondo/Multitarget-tracker/src/Tracker/graph/GTL/src/debug.cpp: In static member function 'static void GTL::GTL_debug::debug_message(const char*, ...)':
/home/juccalderondo/Multitarget-tracker/src/Tracker/graph/GTL/src/debug.cpp:19:44: warning: unused parameter 'message' [-Wunused-parameter]
 void GTL_debug::debug_message (const char* message, ...)
                                            ^~~~~~~
In file included from /home/juccalderondo/Multitarget-tracker/src/Tracker/Ctracker.cpp:4:0:
/home/juccalderondo/Multitarget-tracker/src/Tracker/track.h:7:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
src/Tracker/CMakeFiles/mtracking.dir/build.make:94: recipe for target 'src/Tracker/CMakeFiles/mtracking.dir/Ctracker.cpp.o' failed
make[2]: *** [src/Tracker/CMakeFiles/mtracking.dir/Ctracker.cpp.o] Error 1
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp: In member function 'Point_t TKalmanFilter::GetPointPrediction()':
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:550:16: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
         switch (m_type)
                ^
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp: In member function 'Point_t TKalmanFilter::Update(Point_t, bool)':
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:595:20: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
             switch (m_type)
                    ^
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:647:16: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
         switch (m_type)
                ^
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp: In member function 'cv::Rect TKalmanFilter::GetRectPrediction()':
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:699:16: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
         switch (m_type)
                ^
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp: In member function 'cv::Rect TKalmanFilter::Update(cv::Rect, bool)':
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:758:20: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
             switch (m_type)
                    ^
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:813:16: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
         switch (m_type)
                ^
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp: In member function 'cv::Vec<float, 2> TKalmanFilter::GetVelocity() const':
/home/juccalderondo/Multitarget-tracker/src/Tracker/Kalman.cpp:883:16: warning: enumeration value 'KalmanCount' not handled in switch [-Wswitch]
         switch (m_type)

**Comment by calderonsin** [comment]
and then a lot of waning and at the end this:
[ 87%] Linking CXX shared library ../../../libyolo_lib.so
[ 87%] Built target yolo_lib
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2


My SO is Ubuntu 18.04.3 LTS And the GCC package is: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by Nuzhny007** [comment]
Go here: https://github.com/Smorodov/Multitarget-tracker/issues/332
