### ISSUE TITLE
Missing common files for mtdetection when using MT Tracking as a library

### ISSUE THREAD

**Issue by YvesBos** [Smorodov/Multitarget-tracker#360]
Full build & install succeeds with no errors as per instructions in the README.md. Problems arise however when using MT Tracking as a library, consider the following minimal example:

```
cmake_minimum_required(VERSION 3.21)

find_package(MTTracking REQUIRED)
find_package(OpenCV REQUIRED)

add_library(my-lib SHARED main.cpp)

target_include_directories(my-lib PUBLIC ${MTTracking_INCLUDE_DIR})
target_link_libraries(my-lib PUBLIC ${OpenCV_LIBS} MTTracking::mtracking MTTracking::mdetection)
```

Where `main.cpp` contains just:

```
#include <mtracking/Ctracker.h>
#include <mdetection/BaseDetector.h>
```

Building this results in the following error:
```
cmake --build . -j                                                                                               
[ 50%] Building CXX object CMakeFiles/my-lib.dir/main.cpp.o
In file included from /home/yves/Development/testmtt/main.cpp:2:
/usr/local/include/mdetection/BaseDetector.h:4:10: fatal error: defines.h: No such file or directory
    4 | #include "defines.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/my-lib.dir/build.make:76: CMakeFiles/my-lib.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/my-lib.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
Both mtracking and mdetection use the sources in `common` but they are only added as a library for mtracking and installed as public headers. Hence `#include <mtracking/Ctracker.h>` causes no issues. I've tried adding the sources as a library for mdetection too & installing the public headers but run into redefinition errors. As a test, I've tried adding `include_directories(/usr/local/include/mtracking)` to have `defines.h` available for mtdetection, it solves the error above but later a similar error occurs for `TypeConverter::m_typeNames` in `object_types.cpp`.

How do I go about solving this?

**Comment by YvesBos** [comment]
I managed to work around the issue by having cmake include the headers in `/usr/local/include/mtracking` as described above. For the error related to `object_types.cpp`: I inlcuded it in the `detector_sources` and it builds without errors now. 

Surely there is a better way to build the library correctly?

**Comment by Nuzhny007** [comment]
Thnx for your response!
I'll fix it in near time.

**Comment by Nuzhny007** [comment]
Fixed: https://github.com/Smorodov/Multitarget-tracker/pull/361
Try, plz, a new version:
git pull
cmake .
make
sudo make install

**Comment by YvesBos** [comment]
Confirmed fixed, it builds correctly now. Thanks!
