### ISSUE TITLE
installing problem : Ubuntu with opencv 3.2

### ISSUE THREAD

**Issue by RedOne88** [Smorodov/Multitarget-tracker#37]
Hello Mr Smorodov,
First, I want to you thanks for sharing your code.
I have an problem in installing step :
[ 6%] Building CXX object CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o
/Multitarget-tracker-master/Detector/BackgroundSubtract.cpp: In constructor ‘BackgroundSubtract::BackgroundSubtract(BackgroundSubtract::BGFG_ALGS, int, int, int, int, int, int)’:
/Multitarget-tracker-master/Detector/BackgroundSubtract.cpp:40:26: error: ‘createBackgroundSubtractorCNT’ is not a member of ‘cv::bgsegm’
m_modelOCV = cv::bgsegm::createBackgroundSubtractorCNT(15, true, 15 * 60, true);
^
CMakeFiles/MultitargetTracker.dir/build.make:100: recipe for target 'CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o' failed
make[2]: *** [CMakeFiles/MultitargetTracker.dir/Detector/BackgroundSubtract.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/MultitargetTracker.dir/all' failed
make[1]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
Makefile:76: recipe for target 'all' failed

Can you help me plz!
Thanks you in advance.

**Comment by RedOne88** [comment]
I changed the platform to solve the problem, I worked on windows, I managed to compile the program with Cmake, I launched the program with microsoft visual studio 2013. and zuut, the problems are happening.

Error 10 error C2039: 'createBackgroundSubtractorCNT': is not a member of 'cv :: bgsegm' \ Multitarget-tracker \ Multitarget-tracker-master \ Detector \ BackgroundSubtract.cpp

Error 11 error C3861: 'createBackgroundSubtractorCNT': identifier not found C: \ Users \ Redouane \ Desktop \ Multitarget-tracker \ Multitarget-tracker-master \ Detector \ BackgroundSubtract.cpp

12 IntelliSense: namespace "cv :: bgsegm" does not have a member "createBackgroundSubtractorCNT"

As always, I commented out the lines from 39 to 49. but by running the program with the command: MultitargetTracker.exe atrium.avi 1

It opens the video to the frame 21 and after he gives me this error:

Debug ASSERTION FAILED§
FIle f: \ dd \ vctools \ crt \ crtw32 \ misc \ dbgdel.cpp
Line: 52
Expression: _BLOCK_TYPE_IS_VALID (pHead-> nBlockUse)

**Comment by Nuzhny007** [comment]
Hi!
I have updated a Readme file in latest pull request with information about configure CMake with and without installed opencv_contrib. If you don't have it then options USE_OCV_BGFG, USE_OCV_KCF and USE_OCV_UKF will be disabled.
And I described run options for MultitargetTracker executable.

**Comment by RedOne88** [comment]
thanks you for your answer , 
can you give me the link of Readme file plz? 
I did not find it !

**Comment by Nuzhny007** [comment]
It is now in master branch.

**Comment by RedOne88** [comment]
Thanks you, I compiled the program, but when I run it(MultitargetTracker.exe -e=1 atrium.avi), this error appears : this error:
Debug ASSERTION FAILED§
FIle f:\dd\vctools\crt\crtw32\misc\dbgdel.cpp
Line: 52
Expression: _BLOCK_TYPE_IS_VALID (pHead->nBlockUse)
!!
can you help me plz? Thanks you in advance.

**Comment by Nuzhny007** [comment]
Try plz: ./MultitargetTracker ../data/atrium.avi -e=1

**Comment by RedOne88** [comment]
Thank you for your reply,
In fact, I work on windows, for that, ./MultitargetTracker ../data/atrium.avi -e=1 " does not work on cmd for me, if I do "MultitargetTracker.exe -e = 0", the mouse program works perfectly, but the others not! Always the problem of the previous message appears and prevents me from seeing the results of the tracking.

**Comment by Smorodov** [comment]
Are you trying to run from IDE, if so, you need to set working folder to that there exe located. If no, try to move atrium.avi to exe's folder and use MultitargetTracker atrium.avi -e=1 it should resolve video file path issue.

**Comment by RedOne88** [comment]
In my opinion, this is not a path problem. In fact, I was able to launch the program, and it reads the video atrium.avi. But, when it arrives at frame 24 (this is where the detector begins), the error occurs!!.
I attached a screenshot of the displayed error
![capture](https://user-images.githubusercontent.com/30829131/29205107-14999822-7e7b-11e7-8897-ea3a0d595bbe.JPG)

**Comment by Nuzhny007** [comment]
Do you sure then was used equal versions of the exe (Multitargettracker) and libraries (OpenCV)?
Release + Release or Debug + Debug? Not Releas + Debug!

**Comment by RedOne88** [comment]
Ah ok, tanks you.
What can I do with this new error?
"OpenCV bgfg algorithms are not implemented! Used Vibe by default."
I launched the program with CodeBloks by adding all the herders.

When I edit BackfroundSubtract.cpp file:

#else
         Case ALG_MOG:
         Case ALG_GMG:
/ * Case ALG_CNT:
             Std :: cerr << "OpenCV bgfg algorithms are not implemented! Used Vibe by default." << std :: endl;
             Failed = true;
             break;*/
#endif
The program starts but without detection or tracking!
I confirm that I have opencv installed with the extra modules.

**Comment by Nuzhny007** [comment]
This algorithms implemented in opencv_contrib repository. And better new 3.3 version.
 If you want use they then it need configure and rebuild OpenCV with opencv_contrinb. Readme: https://github.com/opencv/opencv_contrib

**Comment by RedOne88** [comment]
Ok, is there any possibility of using this algorithm with the version opencv 3.2?
What I want, is to detect and tracker people!

**Comment by RedOne88** [comment]
Finally, I managed to run your program, I installed opencv 3.3.
Thanks you for your answers and sharing your code.

**Comment by yyy03** [comment]
Hi , i  am working on your code, and find that when a tracker loses the detections , KalmanUnscented is not very good  to predict the location , resulting  in wrongly tracking. But with the KCF , the performance is very good.  but  i find a weird thing.  Mostly the KCF part need about 1ms , but several time , it consumes 50ms ,evern more , i think  it has something to do with the size of target. i am not very sure . does this situation happen to you?  or i just make a mistake . i  appreciate it if you can give me some help.
![2017-08-16 19-10-37](https://user-images.githubusercontent.com/30096591/29360830-5181d5de-82b7-11e7-9fce-1105f571b322.png)

**Comment by Nuzhny007** [comment]
Yes, KalmanUnscented works good not for all objects.

Whats about KCF: KCF tracker now created for the every object. It may be very slow. But! But it can use MultiTracker from opencv_contrib: https://github.com/opencv/opencv_contrib/blob/master/modules/tracking/samples/tutorial_multitracker.cpp
It will be faster then single KCF tracker for each object. If you want I can integrate it in project in couple of days.

**Comment by 88madri** [comment]
Yeah. It will we great to include the opencv multitracker.

**Comment by Nuzhny007** [comment]
>Yeah. It will we great to include the opencv multitracker.
Ok

**Comment by Nuzhny007** [comment]
1. For integration the Multitracker API must include methods for add and remove targets. But it doesn't! It can only add new targets.
2. And now Multitarget tracker supports only one tracker with speed up it work with multiply target - TLD tracker ( see MultiTrackerTLD::update_opt ).
Apparently, I will deal with this task later. It's a pity!

**Comment by debuleilei** [comment]
hello, I have compiled the opencv_contrib,but when I cmake the project ,it still shows can't find it ,then when I run the exe ,there is more message shows like below,what should I do ,can you give me some advice?
![Screenshot from 2019-05-07 11-04-41](https://user-images.githubusercontent.com/35217567/57268852-fb5ccd80-70b7-11e9-841a-5684d7e394c4.png)

**Comment by Nuzhny007** [comment]
Do you run CMake with GUI or from terminal?
If from GUI then set USE_OCV_KCF=ON.
If from terminal then add option: -DUSE_OCV_KCF=ON
