### ISSUE TITLE
ImportError: DLL load failed while importing pymtracking: Impossível localizar o módulo especificado.

### ISSUE THREAD

**Issue by dibet** [Smorodov/Multitarget-tracker#392]
Hi,
I test the library for C++ and Python in linux and it works fine.
In Windows, i compile and install it using python setup.py build and python setup.py install .
The library is installed but i have the error:
ImportError: DLL load failed while importing pymtracking: Impossível localizar o módulo especificado.
Any help?
Iam using Visual Studio to compile it

**Comment by dibet** [comment]
Today i compile with mingw and visual studio, the same problem

**Comment by Nuzhny007** [comment]
Hi!
Thanx for the response. I'll fix it

**Comment by Nuzhny007** [comment]
Hi!
Fixed some problems in demo.py: https://github.com/Smorodov/Multitarget-tracker/pull/393/files

But you problem is another. I don't now why, but result pymtracking.cp38-win_amd64.pyd (in my case) wait all dependences in current folder. I copied all dependences and it works fine:

```
cublas64_11.dll*
cublasLt64_11.dll*
cudart64_110.dll*
cudnn64_8.dll*
cudnn_adv_infer64_8.dll*
cudnn_cnn_infer64_8.dll*
cudnn_ops_infer64_8.dll*
curand64_10.dll*
myelin64_1.dll*
nvinfer.dll*
nvinfer_builder_resource.dll*
nvinfer_plugin.dll*
nvonnxparser.dll*
nvparsers.dll*
opencv_bgsegm460.dll*
opencv_calib3d460.dll*
opencv_core460.dll*
opencv_dnn460.dll*
opencv_features2d460.dll*
opencv_flann460.dll*
opencv_highgui460.dll*
opencv_imgcodecs460.dll*
opencv_imgproc460.dll*
opencv_objdetect460.dll*
opencv_tracking460.dll*
opencv_video460.dll*
opencv_videoio460.dll*
opencv_videoio_ffmpeg460_64.dll*
pthreadVC2.dll*
pymtracking.cp38-win_amd64.pyd*
yolo_lib.dll*
yolo_rt_lib.dll*

```

Maybe I set wrong PATH

**Comment by dibet** [comment]
Hi, it works 
Thanks by your help 👍
