### ISSUE TITLE
some time the KCF part  need more than 100 ms

### ISSUE THREAD

**Issue by yyy03** [Smorodov/Multitarget-tracker#40]
Hi , i am working on your code, i have two confusion 
1  why the KalmanUnscented is not good to predict  when a track lose detections, since the motion of car is mostly linear.
2  the KCF is very good to deal with the situation i mentioned above, and mostly the KCF part need 1~2ms ,  but some time the KCF need more than 100 ms ,    i think it has something to do wih the size of target , because  this situation happened when the target is very big, and the detetion part failed to detet it , KCF need to predit the location. i am not very sure, maybe i am wrong , so please help me .
![2017-08-16 19-10-37](https://user-images.githubusercontent.com/30096591/29392354-e6e40c64-832f-11e7-9e18-9ca89060bf1d.png)

**Comment by Nuzhny007** [comment]
Hi!
Yes, KalmanUnscented works good not for all objects.

Whats about KCF: KCF tracker now will be created for the every lost object. It may be very slow.
But it can to give some speedup:
cv::TrackerKCF::Params params;
params.compressed_size = 1;
params.desc_pca = cv::TrackerKCF::GRAY;
params.desc_npca = cv::TrackerKCF::GRAY;
params.resize = true;   <------ Enable resizing

And now opencv_contrib/tracking module has a lot of the trackers. I can try to use another trackers, not only KCF. If you want I can integrate they in project in couple of days.

**Comment by yyy03** [comment]
thank you very much！
a) i do not understand the LocalTracker, what is the point, is it based on Lucas-Canade optical flow.
b)  is  Lucas-Canade optical flow faster than KCF and MIL, i thought Lucas-Canade optical flow is very slow for detecting much point
c)  i think  KCF is better than MIL , what do you think? 
d)  the tracking module has a lot of trackers, maybe i need to have a good study about them and if you can integrate them i will appreciate it very much.

**Comment by Nuzhny007** [comment]
a, b) LocalTracker is my experimental tracker. It is not so robust as KCF but can be faster. I use it for tracking very small object, for example insects. LocalTracker and KCF are for different goals.
c) Yes!
d) I integrate now only MIL ( in latest pull request Added MIL online tracker for lost objects #42 ). It is too slow.

**Comment by Nuzhny007** [comment]
Hi!
I added pull request #47 with speed-up for KCF tracker (and MIL, and MedianFlow). Now KCF uses not all frame but only quarter.

**Comment by Nuzhny007** [comment]
And two good news:
1. I waiting pull request with the KCF speedup ( https://github.com/opencv/opencv_contrib/pull/1374 ).
2. After my pull request ( https://github.com/opencv/opencv_contrib/pull/1381 ) to the opencv_contrib it can use TLD and Multitracker API for TLD.

**Comment by yyy03** [comment]
Thanks very much,  recently one month， I am focused on the Yolov2,  unfortunately，the accuracy is not very high. by the way, i will try the way to speed up KCF.
do you try to use some feature such as HOG，LBP,Color, to make up for the fail of HungarianAlg??

**Comment by Nuzhny007** [comment]
Hi!
Do you mean an CvHaarEvaluator, CvHOGEvaluator, CvLBPEvaluator etc from opencv_contrib/tracking? I don't sure. All this features are old and high-level trackers used they. But I don't see a very robust and fast tracker witch based on this features.
Do you readed a comment from another ussue? Here: https://github.com/Smorodov/Multitarget-tracker/issues/13#issuecomment-337031781
It looks like to try deep_sort and high-level tracking with YOLO. I think than in the nearest time I will try to implement  algorithms on C++ in this project (with opencv_dnn module).
