### ISSUE TITLE
Question on handling detections from  multiple sensors 

### ISSUE THREAD

**Issue by carlos-antac** [Smorodov/Multitarget-tracker#401]
Hi!
First of all, thanks for maintaining this great project. 

I'd like to know if there is a way to input detections from multiple sensors to the tracker. My use case is that I have two sensors that output detections at almost the same timestamp.  

One option would be two concatenate the detections from both sensors and pass them to the Update method. However, the information is redundant in the sense that some detections can be produced by both sensors, so I believe this wouldn't work as the tracker will create one track for each detection (even the repeated ones).  

The other option would be to call the tracker Update method for each sensor sequentially but I think this also wouldn't work since it will update the Kalman filter twice but the detections correspond to the same timestamp. 

Is there a recommended way to handle this use case?

Thanks in advance.

**Comment by Nuzhny007** [comment]
Hi!
I think so:
1, Find a transform between two scenes (from sensor 1 and sensor 2), for example H12 (Homography scene1 -> scene2).
2. Detection on each frame on scene1 and scene2.
3. Transform coordinates for all detections to scene2: {detection1}* = H12 * {detection1}
4.  Merge all detections: {detections} = {detections1}* U {detections2}
5.  Non maximum suppression for the {detections} for removing duplicates
6. Tracking
7. Profit!
