### ISSUE TITLE
File "video_with_traffic.mp4" is absent

### ISSUE THREAD

**Issue by miromx** [Smorodov/Multitarget-tracker#426]
Hi! In [Wiki](https://github.com/Smorodov/Multitarget-tracker/wiki/Run-examples) You mentioned about building and running CarsCounting example, but in data folder file "video_with_traffic.mp4" is absent. Also, after building project there is no CarsCounting app. Do I need start CarsCounting via MultitargetTracker or is there is special way to compile and run CarsCounting example. Thank You!

**Comment by Nuzhny007** [comment]
Hi!
I fixed this wiki page. Just now a CarsCounting example merget with Multitarget-tracker and runs with -e=7 flag. And also I added page with description how to make correct geo_bind,ini file: https://github.com/Smorodov/Multitarget-tracker/wiki/Speed-calculation

**Comment by miromx** [comment]
@Nuzhny007 Thanks a lot for your work! By a way, is any opportunities to contribute to your project?

**Comment by Nuzhny007** [comment]
Yes of course. I'll glade for any help
