### ISSUE TITLE
Tracking Parameters

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#55]
Hi.
Can you give more info about the Ctracker parameters?? I mean 

```
track_t dt_,
        track_t accelNoiseMag_,
        track_t dist_thres_,
        size_t maximum_allowed_skipped_frames_,
        size_t max_trace_length_
```

**Comment by Nuzhny007** [comment]
Hi!

dt - delta time. It's parameter for Kalman filter, model time interval

dist_thresh - threshold for matching tracked targets on video and detected regions on the current frame. If used DistCenters then dist_thresh - Euclidean distance between centers (in pixels). If used DistJaccard then dist_thresh -  Jaccard disnance (from 0 to 1).

maximum_allowed_skipped_frames - If the target was not found at the specified number of frames, it will be deleted. It can use fps to set this parameter in seconds: maximum_allowed_skipped_frames == 2 * fps. Tracking the target 2 second without detections.

max_trace_length - Each target contains trajectory with this length.

**Comment by Nuzhny007** [comment]
accelNoiseMag - this parameter for Kalman filter, it's noise.

With work of the **dt** and **accelNoiseMag** you can experiment in MouseTracking exaple (-e=0).

**Comment by Nuzhny007** [comment]
Mmm...
Kalman can track a target when it's fully occluded. KCF can help if target partial occluded.
May be you can show video with this problem?

**Comment by 88madri** [comment]
For example. Maybe its a bit challenging this video.

https://drive.google.com/file/d/1lS2HMJKFxryBSwoCDX--u-wujiv9rxeD/view?usp=sharing

Which parameters should we change in order to get better performance of the tracking??

**Comment by Nuzhny007** [comment]
Hi!
For this example approach with Background subtraction is not a good choice.
But if BGFG segmentation is used then for better performance it need to disable KCF and other trackers.
I think than approach with deep_sort and your with YOLO ( https://github.com/Smorodov/Multitarget-tracker/issues/13#issuecomment-337031781 ) may be better. I want to implement it.

I'm using BGFG segmentation for big background areas and small foreground objects.

**Comment by 88madri** [comment]
Maybe using SSD is better than YOLO. Based on https://www.pyimagesearch.com/2017/09/11/object-detection-with-deep-learning-and-opencv/.
I don't exactly what deep_sort tracking does. I guess that detects rectangle based on YOLO detector but I donw know how it follow the track
