### ISSUE TITLE
I have created a SSD Object Model Detector

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#56]
Hi.
Based on last dnn examples from opencv. I have created a new CDetector that give classificator rectangles.
This is the code, maybe I should pull request it.

```
CClassificatorDetector::CClassificatorDetector(
		bool collectPoints,
		cv::UMat& gray
		)

	{
		m_fg = gray.clone();

		m_minObjectSize.width = std::max(5, gray.cols / 100);
		m_minObjectSize.height = m_minObjectSize.width;
		m_collectPoints = collectPoints;

		cv::String protoTxtName = "MobileNetSSD_deploy.prototxt.txt";
		cv::String caffeModelName = "MobileNetSSD_deploy.caffemodel";

		deepLearningModel = cv::dnn::readNetFromCaffe(protoTxtName, caffeModelName);
}

CClassificatorDetector::~CClassificatorDetector() {
	// TODO Auto-generated destructor stub
}

const std::vector<cv::Point_<float>>& CClassificatorDetector::Detect(cv::UMat& gray)
{

	m_fg = gray.clone();
	cv::UMat resizedMat;

	m_regions.clear();
	m_centers.clear();
    std::vector<cv::Rect> rects;
	std::vector<cv::Vec4i> hierarchy;


	cv::resize(m_fg, resizedMat, cv::Size(300, 300));
	cv::Mat blob = cv::dnn::blobFromImage(resizedMat.getMat(cv::ACCESS_READ), 0.007843, cv::Size(300, 300), cv::Scalar(127.5));
	deepLearningModel.setInput(blob);
	cv::Mat prob = deepLearningModel.forward();

	cv::Mat probMat(prob.size[2], prob.size[3], CV_32F, prob.ptr<float>());

	for(int i = 0; i < probMat.rows; i++)
	{

		if (probMat.at<float>(i, 2) > 0.70 && probMat.at<float>(i,1) == 15)
		{
			double startX = m_fg.cols*(probMat.at<float>(i, 3));
			double startY = m_fg.rows*(probMat.at<float>(i, 4));
			double width = m_fg.cols*(probMat.at<float>(i, 5));
			double height = m_fg.rows*(probMat.at<float>(i, 6));

			rects.push_back(cv::Rect(startX, startY, width, height));
		}
	}

	if (rects.size() > 0)
	{
		for (size_t i = 0; i < rects.size(); i++)
		{
			cv::Rect r = rects[i];

			if (r.width >= m_minObjectSize.width &&
				r.height >= m_minObjectSize.height)
			{
				CRegion region(r);
				cv::Point2f center(r.x + 0.5f * r.width, r.y + 0.5f * r.height);

				if (m_collectPoints)
				{
                    const int yStep = 5;
                    const int xStep = 5;

					for (int y = r.y; y < r.y + r.height; y += yStep)
					{
						cv::Point2f pt(0, static_cast<float>(y));
						for (int x = r.x; x < r.x + r.width; x += xStep)
						{
							pt.x = static_cast<float>(x);
							if (r.contains(pt))
							{
								region.m_points.push_back(pt);
							}
						}
					}

					if (region.m_points.empty())
					{
						region.m_points.push_back(center);
					}
				}

				m_regions.push_back(region);
				m_centers.push_back(cv::Point_<float>(center.x, center.y));
			}
		}
	}
	return m_centers;
}
```

**Comment by Nuzhny007** [comment]
Hi!
It's very interesting. I vote for the pull request.

**Comment by 88madri** [comment]
I will try, but maybe we need someone more integrated with the code. I think is a big change.

The interesting portion of code is this. I will try to explain better.

      ```
     //The deep-learning model works with 300X300 images.
      cv::resize(m_fg, resizedMat, cv::Size(300, 300));
     //Extract the blob
	cv::Mat blob = cv::dnn::blobFromImage(resizedMat.getMat(cv::ACCESS_READ), 0.007843, 
        cv::Size(300, 300), cv::Scalar(127.5));
       //give the image blob to the deep learning model
	deepLearningModel.setInput(blob);
       //give a pass to the model.
	cv::Mat prob = deepLearningModel.forward();
        //prob is a multi-dimensional Mat with the result of the pass.
	cv::Mat probMat(prob.size[2], prob.size[3], CV_32F, prob.ptr<float>());
        //prob is a multi-dimensional Mat with the result of the pass.
        //extract the interest info of prob to a 2-D Mat

        //Test all the detections.
	for(int i = 0; i < probMat.rows; i++)
	{
                //We decided to get the ones with more of 70% confidence and also get only if is a person 
                 //(id=15).

               
		if (probMat.at<float>(i, 2) > 0.70 && probMat.at<float>(i,1) == 15)
		{
                        //We also obtain the object detection (rect)
			double startX = m_fg.cols*(probMat.at<float>(i, 3));
			double startY = m_fg.rows*(probMat.at<float>(i, 4));
			double width = m_fg.cols*(probMat.at<float>(i, 5));
			double height = m_fg.rows*(probMat.at<float>(i, 6));

			rects.push_back(cv::Rect(startX, startY, width, height));
		}
	}
```

**Comment by 88madri** [comment]
Is implemented in my own library but shares code with Multitarget-tracker. Maybe you can use CDetector as  base class and then implement CMotionDetector and CClassificatorDetector as childs. Of course, you can use the previous code to make your own pull request. 
Instead of having a BackgroundModel you need a DeepLearningModel created with 
cv::String protoTxtName = "MobileNetSSD_deploy.prototxt.txt";
cv::String caffeModelName = "MobileNetSSD_deploy.caffemodel";

Also we can give options of confidence and categories to look for.

**Comment by Nuzhny007** [comment]
Ok. I will try.
But if you want to make this change yourself then will be great.

**Comment by 88madri** [comment]
I think I will try to add to the CClassificator Detector as another example like the Pedestrian detection.

**Comment by Nuzhny007** [comment]
Hi!
I have implemented SSD detector. Here: https://github.com/Smorodov/Multitarget-tracker/pull/64
Are there any comments or requests for architecture?

**Comment by 88madri** [comment]
Ohh thats was great. It's exactly like I thought, well done. :)
I've read your TODO on your last commit about DCT Tracker. That's also will be interesting.

Do you have any other ideas to add to the tracker?? Maybe like Tracks behaviour?? For example crossing a line, occupation, abandoned object.. counting cars, traffic... etc

**Comment by Nuzhny007** [comment]
Yes, I have some ideas. But now they don't relate to the analysis of the behaviour of objects. Also I want implement deep_sort on C++.

>crossing a line, occupation, abandoned object.. counting cars, traffic

It's all is not on Tracker abstraction level (not all: abandoned object is not so simple for MotionDetector). It can create high-level abstraction for trajectories analysis. About 10-12 years ago I have worked on motion detector for video surveillance system. I have wrote it and Phd dissertation. Here: https://bitbucket.org/nuzhny007/feintrack
With lines crossing, with abandoned objects. You can see video (with me and my sport bag): https://www.youtube.com/watch?v=cdu4FYoguUo
A first camera with motion detection recognize objects and second PTZ camera automatically tracks the goals. Red - moved objects, blue - abandoned.

Now this project - just hobby. I want to create a good tracker as library or framework but not some product.
