### ISSUE TITLE
Question: How do you decide the Kalman Filter matrices?

### ISSUE THREAD

**Issue by kanakiyab** [Smorodov/Multitarget-tracker#59]
Hello,

This is a very interesting and great work! I am tying to understand the implementation as I am not very much familiar with Kalman Filter. I have read [this](http://www.cs.unc.edu/~welch/media/pdf/kalman_intro.pdf) article but that s too generic.  

The first question that comes to my mind is how are the Kalman Filter matrices determined?

For e.g.:
[Here in CreateLinear](https://github.com/Smorodov/Multitarget-tracker/blob/41c61f0649b18c1e55828287205d16c42eb47400/Tracker/Kalman.cpp#L46):

`m_linearKalman->transitionMatrix = (cv::Mat_<track_t>(4, 4) <<
                                        1, 0, m_deltaTime, 0,
                                        0, 1, 0, m_deltaTime,
                                        0, 0, 1, 0,
                                        0, 0, 0, 1);
    
m_linearKalman->processNoiseCov = (cv::Mat_<track_t>(4, 4) <<
                                       pow(m_deltaTime,4.0)/4.0	,0						,pow(m_deltaTime,3.0)/2.0		,0,
                                       0						,pow(m_deltaTime,4.0)/4.0	,0							,pow(m_deltaTime,3.0)/2.0,
                                       pow(m_deltaTime,3.0)/2.0	,0						,pow(m_deltaTime,2.0)			,0,
                                       0						,pow(m_deltaTime,3.0)/2.0	,0							,pow(m_deltaTime,2.0));`

Similarly, for create linear for Rect [here](https://github.com/Smorodov/Multitarget-tracker/blob/41c61f0649b18c1e55828287205d16c42eb47400/Tracker/Kalman.cpp#L92)

`m_linearKalman->transitionMatrix = (cv::Mat_<track_t>(6, 6) <<
                                        1, 0, 0, 0, m_deltaTime, 0,
                                        0, 1, 0, 0, 0,           m_deltaTime,
                                        0, 0, 1, 0, 0,           0,
                                        0, 0, 0, 1, 0,           0,
                                        0, 0, 0, 0, 1,           0,
                                        0, 0, 0, 0, 0,           1);

m_linearKalman->processNoiseCov = (cv::Mat_<track_t>(6, 6) <<
                                       pow(m_deltaTime,4.)/4., 0,                    0,                    0,                    pow(m_deltaTime,3.)/2., 0,
                                       0,                    pow(m_deltaTime,4.)/4., 0,                    0,                    pow(m_deltaTime,3.)/2., 0,
                                       0,                    0,                    pow(m_deltaTime,4.)/4., 0,                    0,                    0,
                                       0,                    0,                    0,                    pow(m_deltaTime,4.)/4., 0,                    0,
                                       pow(m_deltaTime,3.)/2., 0,                    0,                    0,                    pow(m_deltaTime,2.),    0,
                                       0,                    pow(m_deltaTime,3.)/2., 0,                    0,                    0,                    pow(m_deltaTime,2.));`

Why is the process noise covariance matrix is not symmetric in second case? Is there any reference you can provide which explain the reasoning of choosing these matrices? What are the assumptions made for defining them? 

What does  pow(m_deltaTime,4.)/4., pow(m_deltaTime,2.) and pow(m_deltaTime,3.)/2. stand for?

Help is much appreciated.

Thanks!

**Comment by kanakiyab** [comment]
I understand the transition matrices now (after simple linear algebra and the assumption that it is a linear filter). However, I think that the Process noise Covariance matrix for the Rect definition is wrong! AFAIK, one of the properties of covariance matrix is that it is symmetric. 

I still haven't clearly understood the values that the matrix has.

If anyone knows, please help me.

Thanks.

**Comment by Nuzhny007** [comment]
Thanks!
It was my error. I'm fix it here: https://github.com/Smorodov/Multitarget-tracker/pull/63

**Comment by kanakiyab** [comment]
Thanks, how do you decide those values? I am still not sure.

**Comment by Nuzhny007** [comment]
I have read this in some paper. But I don't remember what the paper. May by Smorodov can help you?

**Comment by Smorodov** [comment]
I did according student daves tutorials (there 4 parts) https://www.youtube.com/watch?v=Me0wbxEDO4I&t=1s

**Comment by kanakiyab** [comment]
Thank you, Smorodov.
