### ISSUE TITLE
Robustness of KCF in opencv_contrib

### ISSUE THREAD

**Issue by GarrickLin** [Smorodov/Multitarget-tracker#61]
I have tested TrackerKCF in opencv_contrib, the performance is not satisfactory because [earlier implementation](https://github.com/joaofaro/KCFcpp)(I used this repo) is much robuster. Did you ever test and compare those two repos. And I think code in opencv_contrib should be carefully trusted. UKF should also be further tested.

**Comment by 88madri** [comment]
With UKF you mean this??

https://github.com/JunshengFu/tracking-with-Unscented-Kalman-Filter

This repo uses KCF from open_contrib, I will try the implementation from your repo. 
And maybe you can add a pull request with both tracker: KCF (robuster implementation) and UKF.

**Comment by GarrickLin** [comment]
I have not tested UKF yet. And I will test soon.

**Comment by Nuzhny007** [comment]
About KCF.
A current KCF from OpenCV can be not so robust. Why?
1. For better performance it used gray frames. Color KCF or Lab KCF will be more robust but speed?
2. For better performance I set option params.resize = true in cv::TrackerKCF::Params. This option is not the best for tracker quality.

But you can set another option: params.detect_thresh = 0.3 (default is 0.5).
It can increase false positive but tracking will be more robust.

**Comment by Nuzhny007** [comment]
UKF.
It is very interesting! And it is a first example than I see with UKF. I wrote code with UKF from OpenCV without some information about this filter - it was my first experience.

**Comment by GarrickLin** [comment]
I have tested with UKF and it works fine.

**Comment by 88madri** [comment]
Can you add your code with UKF??

**Comment by Nuzhny007** [comment]
> Can you add your code with UKF??
Yes: https://github.com/Smorodov/Multitarget-tracker/blob/master/Tracker/Kalman.cpp#L256
It was my commit.
