### ISSUE TITLE
using ROI to track

### ISSUE THREAD

**Issue by GarrickLin** [Smorodov/Multitarget-tracker#62]
I noticed that you are using an ROI to do KCF tracking [here](https://github.com/Smorodov/Multitarget-tracker/blob/master/Tracker/track.cpp#L248). If I'm not misunderstanding this scope, ROI tracking does not speed up the KCF algorithm. Because it is a local based tracking algorithm, global area does not affect the speed of KCF.

**Comment by Nuzhny007** [comment]
Hi!
I'm opened TrackerKCFImpl::updateImpl function from opencv_contrib. It works with al frame:
`Mat img=image.clone();
    // check the channels of the input image, grayscale is preferred
    CV_Assert(img.channels() == 1 || img.channels() == 3);

    // resize the image whenever needed
if(resizeImage)resize(img,img,Size(img.cols/2,img.rows/2));`

So if I change ROI size in this project on quarter of the frame size then it is slightly accelerated.
