### ISSUE TITLE
BaseDetector CreateDetector method should return a std:shared_ptr or std::unique_ptr instead of wild pointer to *BaseDetector

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#71]
reference
https://stackoverflow.com/questions/23475776/how-to-initialize-a-stdshared-ptr-from-a-function-returning-by-value

**Comment by Nuzhny007** [comment]
Hi!
I know about make_shared and make_unique - they are used in this project. But I don't know what type of smart pointer need a client. CreateDetector is library function and VideoExamples are client code for this library. Shared or unique ptr and Why?

**Comment by 88madri** [comment]
I usually use shared_ptr on my projects. By using shared_ptr on the return of the method you assure better use of the memory and also avoid a new copy of the Detector. 

The difference between both is better explained here.

https://stackoverflow.com/questions/6876751/differences-between-unique-ptr-and-shared-ptr

**Comment by Nuzhny007** [comment]
Yes. But I think than now libraries user can self select smart pointer type. For VideoExample unique_ptr is the best. For another case shared_ptr may be better. Are you sure than the library must self select pointer type?
What kind of problems you see in case with raw pointer?

**Comment by 88madri** [comment]
I see your point. Maybe I'm worried about make_unique because is on standard c++14 instead of c++11.
Nevertheless...  
Close The Issue??

**Comment by Nuzhny007** [comment]
This question for Smorodov: he is admin and project owner.
