### ISSUE TITLE
Mac OS X build linking Error

### ISSUE THREAD

**Issue by MyraBaba** [Smorodov/Multitarget-tracker#72]
Hi Smorodov,

Thank you for your share and source code for our learning.

I try to build and run the source code in Clion Mac os x. I am using g++-7 for c++14 compatibility.

It went well until below message:
`[100%] Linking CXX executable ../build/MultitargetTracker
Undefined symbols for architecture x86_64:
  "cv::KeyPointsFilter::runByImageBorder(std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Size_<int>, int)", referenced from:
      LBSP::computeImpl(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
      LBSP::compute2(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
      LBSP::validateKeyPoints(std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Size_<int>) in LBSP.cpp.o
  "cv::KeyPointsFilter::runByKeypointSize(std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, float, float)", referenced from:
      LBSP::computeImpl(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
      LBSP::compute2(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
  "cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)", referenced from:
      HybridFaceDetectorExample::ProcessFrame(cv::Mat, cv::UMat)        in main.cpp.o
      FaceDetector::Detect(cv::UMat&)       in FaceDetector.cpp.o
  "cv::Feature2D::detectAndCompute(cv::_InputArray const&, cv::_InputArray const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::_OutputArray const&, bool)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::detect(cv::_InputArray const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::_InputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::detect(cv::_InputArray const&, std::vector<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >, std::allocator<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> > > >&, cv::_InputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::compute(cv::_InputArray const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::_OutputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::compute(cv::_InputArray const&, std::vector<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >, std::allocator<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> > > >&, cv::_OutputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::HOGDescriptor::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, cv::Size_<int>, cv::Size_<int>, double, double, bool) const", referenced from:
      PedestrianDetector::Detect(cv::UMat&)       in PedestrianDetector.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [../build/MultitargetTracker] Error 1
make[2]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
make[1]: *** [CMakeFiles/MultitargetTracker.dir/rule] Error 2
make: *** [MultitargetTracker] Error 2
`

I have already installed Opencv with contrib ( I assume)

what could be the steps to solve this._

Best

**Comment by MyraBaba** [comment]
I tested in ubuntu its working perfectly. Problem was the incorrect opencv_contrib pkg_config.
So all is ok now.

I just wonder to is it feasible to use in rainy, stormy area to detect motions ? Or in night vision ? 

There is a benchmark video : https://www.youtube.com/watch?v=IDalwc52674 

can we have the same performance ? less false alarm.  ie tree leafs..

Thx

**Comment by Nuzhny007** [comment]
Hi!

>I have already installed Opencv with contrib ( I assume)
>what could be the steps to solve this._

1. Tell please about OpenCV version
2. Functions with errors are static. You can try to remove static keyword in LBSP.h and compile project: https://github.com/Smorodov/Multitarget-tracker/blob/master/Detector/Subsense/LBSP.h#L98

>I just wonder to is it feasible to use in rainy, stormy area to detect motions ? Or in night vision ?
Yes. You can change some background subtraction parameters for faster adaptation for the background changing. For example if was used MOG2 algorithm:
```
case ALG_MOG2:
            m_modelOCV = cv::createBackgroundSubtractorMOG2(500, 16, true).dynamicCast<cv::BackgroundSubtractor>();
break;
```
The first parameter with value 500 - history length or adaptation speed. You can set value 100 or 50 for more faster adaptation. In this case will be filtered a small background noise.

**Comment by MyraBaba** [comment]
Hi

Opencv 3.4 is currently installed and active .

Still error even I removed static keyword from LBSP.h at 98.

How we can change the detector ? 
Mac Os X Sierra currnet OS which I have error.

Ubuntu is fine.

thx


`Undefined symbols for architecture x86_64:
  "cv::KeyPointsFilter::runByImageBorder(std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Size_<int>, int)", referenced from:
      LBSP::computeImpl(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
      LBSP::compute2(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
      LBSP::validateKeyPoints(std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Size_<int>) in LBSP.cpp.o
  "cv::KeyPointsFilter::runByKeypointSize(std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, float, float)", referenced from:
      LBSP::computeImpl(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
      LBSP::compute2(cv::Mat const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::Mat&) const in LBSP.cpp.o
  "cv::CascadeClassifier::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, int, int, cv::Size_<int>, cv::Size_<int>)", referenced from:
      HybridFaceDetectorExample::ProcessFrame(cv::Mat, cv::UMat)        in main.cpp.o
      FaceDetector::Detect(cv::UMat&)       in FaceDetector.cpp.o
  "cv::Feature2D::detectAndCompute(cv::_InputArray const&, cv::_InputArray const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::_OutputArray const&, bool)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::detect(cv::_InputArray const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::_InputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::detect(cv::_InputArray const&, std::vector<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >, std::allocator<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> > > >&, cv::_InputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::compute(cv::_InputArray const&, std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >&, cv::_OutputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::Feature2D::compute(cv::_InputArray const&, std::vector<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> >, std::allocator<std::vector<cv::KeyPoint, std::allocator<cv::KeyPoint> > > >&, cv::_OutputArray const&)", referenced from:
      construction vtable for cv::Feature2D-in-LBSP in LBSP.cpp.o
      vtable for LBSP in LBSP.cpp.o
  "cv::HOGDescriptor::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, double, cv::Size_<int>, cv::Size_<int>, double, double, bool) const", referenced from:
      PedestrianDetector::Detect(cv::UMat&)       in PedestrianDetector.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [../build/MultitargetTracker] Error 1
make[2]: *** [CMakeFiles/MultitargetTracker.dir/all] Error 2
make[1]: *** [CMakeFiles/MultitargetTracker.dir/rule] Error 2
make: *** [MultitargetTracker] Error 2
`

**Comment by Nuzhny007** [comment]
Ok.
All undefined function (runByImageBorder, runByKeypointSize etc) are in features2d module in file keypoint.cpp from OpenCV.
Can you check than installed OpenCV has this module with exported functions? I don't have Mac and can't check it self.
