### ISSUE TITLE
 error: no matching function for call to ‘cv::Tracker::init

### ISSUE THREAD

**Issue by zg9uagfv** [Smorodov/Multitarget-tracker#73]
mkdir build && cd build && cmake .. && make

get the errors:
`/home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp: In member function ‘void CTrack::RectUpdate(const CRegion&, bool, cv::UMat, cv::UMat)’:
/home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp:260:75: error: no matching function for call to ‘cv::Tracker::init(cv::UMat, cv::Rect2d&)’
                     m_tracker->init(cv::UMat(prevFrame, roiRect), lastRect);
                                                                           ^
In file included from /usr/local/include/opencv2/tracking.hpp:304:0,
                 from /home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.h:9,
                 from /home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp:1:
/usr/local/include/opencv2/tracking/tracker.hpp:542:16: note: candidate: bool cv::Tracker::init(const cv::Mat&, const Rect2d&)
   CV_WRAP bool init( const Mat& image, const Rect2d& boundingBox );
                ^
/usr/local/include/opencv2/tracking/tracker.hpp:542:16: note:   no known conversion for argument 1 from ‘cv::UMat’ to ‘const cv::Mat&’
/home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp:268:94: error: no matching function for call to ‘cv::Tracker::update(cv::UMat, cv::Rect2d&)’
             if (!m_tracker.empty() && m_tracker->update(cv::UMat(currFrame, roiRect), newRect))
                                                                                              ^
In file included from /usr/local/include/opencv2/tracking.hpp:304:0,
                 from /home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.h:9,
                 from /home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp:1:
/usr/local/include/opencv2/tracking/tracker.hpp:553:16: note: candidate: bool cv::Tracker::update(const cv::Mat&, cv::Rect2d&)
   CV_WRAP bool update( const Mat& image, CV_OUT Rect2d& boundingBox );
                ^
/usr/local/include/opencv2/tracking/tracker.hpp:553:16: note:   no known conversion for argument 1 from ‘cv::UMat’ to ‘const cv::Mat&’
/home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp: In member function ‘void CTrack::CreateExternalTracker()’:
/home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp:349:20: error: ‘struct cv::TrackerKCF::Params’ has no member named ‘detect_thresh’
             params.detect_thresh = 0.3;
                    ^
/home/dh/Workspace/Test/Multitarget-tracker/Tracker/track.cpp:411:29: error: ‘cv::TrackerMOSSE’ has not been declared
`

**Comment by kseniaryabinova** [comment]
I had simular problem. If you also have it, than it is likely that you need to update your OpenCV. I updated mine to 4.3.0 and it resolved the errors.
