### ISSUE TITLE
There is a new Tracker in opencv_contrib

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#74]
I see that in the new release of OPENCV .3.4.1 They added the new CSR-DCF tracker.

Anybody has tested it??

Also.. I read about this one

https://github.com/mcamplan/DSKCF_CPP

Maybe we can add to this project.

**Comment by Nuzhny007** [comment]
Hi!
It's cool and I will add this tracker. But... where I can find RGB-D videos for this tracker?
