### ISSUE TITLE
Accuracy VS Speed

### ISSUE THREAD

**Issue by wait1988** [Smorodov/Multitarget-tracker#77]
Thanks for your awsome project.With better detector,the tracking system works well.The only way to achieve real-time performan is to use GPU?

**Comment by Nuzhny007** [comment]
It depends. Do you know what is the slowest in your case? May be it's the local tracker (KCF, MIL etc). If you set tracking::TrackNone instead tracking::TrackKCF?
And some about GPU: in this project it used only OpenCV library without CUDA. But it can use built-in OpenCL version of algorithms on CPU, integrated GPU or discrete GPU.

**Comment by wait1988** [comment]
You're right,when I set tracking::TrackNone instead of tracking::TrackKCF,the time costs less.Maybe do the detection and tracking in two threads will help too?

**Comment by Nuzhny007** [comment]
Yes, it's a good idea.

**Comment by Nuzhny007** [comment]
Waiting this Pull request: https://github.com/Smorodov/Multitarget-tracker/pull/78

**Comment by Nuzhny007** [comment]
Can you update master branch and test speed?

**Comment by wait1988** [comment]
Since I change the detector to yolov3 and run the code on GPU,the whole process takes about 50ms/frame in one thread.
