### ISSUE TITLE
What is the purpose of m_collectPoints on Detector and more questions

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#79]
Hi. I'm testing with MOG2 Background substraction. and I don't know exactly the purpose of this variable and what does to m_regions.

Sometimes with my video feed, a truck or a car can have multiple boxes instead of only one. How can I combine into one?? In the repo there is nms.h (Non-Maximum Suppression) but what you don't use it??  

Also about the m_fps variable? What we can control with it? I think is the number of frames without a detection of a saved track. But this is not the frame-rate we are updating tthe tracker and detector am I right? 
Do you test with feeds with different frame-rate? I have a camera with 50fps, I assume it don't be neccesary to make the full process at that rate so I can leave one frame of two without process
 
Sometimes I have a car running from left to right of the scene  but in te middle of the image I have a wall .
The car is trackered reasonabily good on the left and right areas but with different Ids. How can I make the car is assigned the same track ID??

Sorry for the amount of questions... jejeje

Thanks.

**Comment by Nuzhny007** [comment]
Hi!
They are the good questions and I will answer in some hours. If you can share some videos with described problems it will be very exellent illustration.

**Comment by Nuzhny007** [comment]
1. m_regions it's an array with raw detects on current frame. Region or blob - detection, Object or Track - target on some frames with trajectory and type.

2. Multiple boxes and NMS.
BGFG segmentation algorithm don't know about moving objects. One big object or 10 small? This algorithm can't decide what is it. For roads and cars: a small cars on horizon and a big cars near the camera. I think than it need to use advanced segmentation or recognition for this case.
![vlcsnap-2018-03-24-12h47m32s003](https://user-images.githubusercontent.com/5041357/37862704-7693c29e-2f62-11e8-8d0f-cc3694c188e2.png)
NMS used for multiple detection of the one object, see you my primary repository: https://github.com/Nuzhny007/Non-Maximum-Suppression

3. fps now used only for time-to-frames conversion. Algorithms don't used current time and time difference - they used frames counting for time calculation. And yes - I have some tests videos with 20, 25, 30 and 60 fps, but I don't prop frames. In this project we don't have some independent from fps time. It's an advanced work.

4. Under construction...

**Comment by 88madri** [comment]
Hi!

Thank for all your responses.

1. Maybe I don't explain well but I asked about m_collectPoints (bool variable) not m_regions.

2. I will try to detect using SSD detector or YOLO (BTW Do you try the new YOLO v3?). I'm using thermal image and when the cars are not very different with the background is when I found problems. On the other hand when is a good detection the tracker works really good. I adjust the Tracker without local Trackers (KCF and localTracking = false) and is OK. 

3. I adjust the proccesed Frames with a variable. So now one of two frames are proccesed. And still the track works right. I think I could tune this parameter in order to work with more advanced detectors (ML ones) which are slower than Background Substractor.

4. Finally, can you tell me something about the type of Kalman, Match , Filter Goal and Distance?

PD: When I have time I want to follow this tutorial.
https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API

It could be a really good detector.!!

**Comment by Nuzhny007** [comment]
About m_collectPoints. I added advanced visualization for points:
- for small objects and Motion detection: https://www.dropbox.com/s/yykecr5v5wl523r/points_md.mp4?dl=0
- for YOLO:  https://www.dropbox.com/s/i4eqcykghxxampy/points_yolo.mp4?dl=0
 I have used it for small objects (not bugs but similar) and this algorithm works good in this case. I think for scenes with walls, barriers, trees and another LK tracker is not a good thing.

Kalman: it's a big topic. What do you want to know about it?
Filter goal: the Kalman filter can create model only for objects centre (model for the trajectory) or for trajectory and size. Second case may be used for videos with perspective when objects moved from camera to the horizon.
Math type: Hungrian algorithm or bipartite matching, It's a equivalent methods for assignment problem (you can read about it in Wikipedia).
Distance:
1. Dist centers - Euclidean distance between objects centres on two N and N+1 frames.
2. Dist rects - Euclidean distance between object rectangles on two N and N+1 frames.
3. Dist Jaccard - Jaccard distance (you can read about it in Wikipedia).
The distances 1 and 2 are in pixels and Jaccard distance is relative from 0 to 1.

Thanx for links to the YOLO v3 and new TF API. I will try they both.

**Comment by Nuzhny007** [comment]
And MobileNet v2: https://research.googleblog.com/2018/04/mobilenetv2-next-generation-of-on.html?m=1

**Comment by 88madri** [comment]
Hi. 
I continue to test and also playing with the parameters of the CTracker and IsRobust Function of track.

Do you know how can I clean from short detections when conditions changes?? I mean with changes of contrast for example. 

Also sometimes I have problems with cars or people changing direction (curve trajectories), (I mean with not a line rect trajectory) The track sometimes makes a drift. Begins follow the car and then the car maybe stop or change the directions and the tracks seems to follow the first trajectory before the turning point 
Tomorrow I will try to share you a video to show this two kinds of troubles.

**Comment by wait1988** [comment]
yolov3 is excellent,faster and strongger!!!!

**Comment by Nuzhny007** [comment]
Cool!
What do you use for YOLO inference? Darknet+cudnn or opencv_dnn?

**Comment by 88madri** [comment]
Hi. Now I am on holidays, I will try on thursday from the office.

It seems that opencv master now have support to YOLOv3. But I am also interested in train with my images (you know thermal images) 

https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects

I will try to follow this example.
