### ISSUE TITLE
face tracking suggestion

### ISSUE THREAD

**Issue by MyraBaba** [Smorodov/Multitarget-tracker#84]
Hi Smorodov,

I wan to utilise object tracking for face detection/recognition.

When we detect the face first time we are calculating its features for detection. But when the same people changes its angle row pitch its features changes. But its is the same object and the same face.

Can we use the tracker to tell algorithm this is the SAME people but just moved/changed pose etc. So we can add this calculated face feature same people. 

What will be your suggestion to track same face object (non rigid object trackin)?

thx

**Comment by Smorodov** [comment]
Hi, yes, you can go with approach you described above. It should work.

**Comment by MyraBaba** [comment]
Hi,

Current face detection and tracking have lots of false positive(detection).
May I suggest dlib face detection ? 

Best

**Comment by MyraBaba** [comment]
Hi Smorodov,

Wha would be your suggestion for object tracking from drones ?

 Current difficulties are :  ie. car , vehicle

Occulsion (buildings trees)
Zoom in zoom out 
Camera changing another direction and come back to same position
clouds.

etc..

What would be the best practices 2019 :)

And finally have you time to make consultancy if we start this projects

Best

BC

**Comment by Nuzhny007** [comment]
Hi!
The best trackers used 2 features:
1. Min flow graphs algorithms for Multitarget tracking. For example: http://www.cs.toronto.edu/boundTracking/
Hungrian algorithm is not optimal approach.

2. Re-id for tracking objects for occlusions. For example Siamese networks.

I hope that I will have time to implement this approaches.
