### ISSUE TITLE
MobileNet SSD and tracking 

### ISSUE THREAD

**Issue by KuntimaKiala** [Smorodov/Multitarget-tracker#87]
Hi Smorodov

I'm currently using the DNN detector, it works fine, I need to track people, I managed to use Kalman filtering for one person, but it failed drastically for multiple persons, but this is not even the big issue, correct me if I am wrong, apparently DNN detector ( based in MobileNet SSD) start detecting the objects ( persons in my case) with the highest score to the lowest, I was wondering how did you solve this problem ( assuming you had it too), since that could be problematic when you measure the spatial position of the objects in the frames to feed the the Kalman filter.
I saw the " MobileNet SSD and tracking for low resolution and low quality videos from car DVR" demo, I wanted to have the same result, I downloaded your project and manage to run it fine, but I did not quite understand how you put the DNN+tracking together, do you have some paper about your project ? That could helpful.
Best regards 
Kuntima K. M.

**Comment by Nuzhny007** [comment]
Hi!
Thank you for your attention to the project.
In latest version to starting MobileNet example you need to write:
_./MultitargetTracker your_video.mp4 -e=4_

P.S. An user manual or paper coming soon...

**Comment by KuntimaKiala** [comment]
Hi
Thanks for your time, as I mentioned, I did run the project, since I was interested with the MobileNet, I used ./MultitargetTracker your_video.mp4 -e=4, and it worked fine, but I just did not understand how you connect the detector with the tracker, it seems like you run the detector forever, and you accord one tracker to each person that appears in the scenario, but the detector does not know the differences between persons, so can you tell me, how do you track each individual ? without putting many tracker in the same person, what is your condition for tracking and stop tracking ? you have the tracker and the detector running in parallel ?

**Comment by Nuzhny007** [comment]
Yes, Detector - MobileNet (or YOLO, or HOG, or Haar, or background subtraction etc) works on each frame. We get a list of the raw detections - regions (or blobs, or bounding boxes). Here: https://github.com/Smorodov/Multitarget-tracker/blob/master/VideoExample.h#L310

For raw detections on each frame we solve a spatio-temporal data association problem. Global data association - Hungrian algorithm (or Kuhn–Munkres algorithm, or Munkres assignment algorithm). Also it can use max flow in weighted bipartite graphs.
Local tracking and trajectories processing - Kalman filter.

But modern algorithms use another approaches for global data association:
1. http://vision.cse.psu.edu/courses/Tracking/vlpr12/lzhang_cvpr08global.pdf
2. http://www.milanton.de/dctracking/
3. https://github.com/nwojke/mcf
I want to include the latest library to the our project.

**Comment by KuntimaKiala** [comment]
Thanks, 
So if I understand You, You use the Hungrian algorithm to assign each person to one tracker according to they spatial-temporal position ? I guess I have to check first what is spatio-temporal data association problem, can you show me where do you use the Hungrian algorithm in your project ?

**Comment by Nuzhny007** [comment]
>You use the Hungrian algorithm to assign each person to one tracker
...to one Kalman filter.
Or to one tracker like KCF if this object wan't found on this frame.

Hungrian use here: https://github.com/Smorodov/Multitarget-tracker/blob/master/Tracker/Ctracker.cpp#L73
