### ISSUE TITLE
Track fast move objects

### ISSUE THREAD

**Issue by wait1988** [Smorodov/Multitarget-tracker#88]
When objects move fast,the kalman filter can't predict the next location well.Is there any proposed method to solve this problem?

**Comment by Nuzhny007** [comment]
Hi!
It's a good question.
I know one way: Kalman filter has a parameter deltaTime. It means how fast Kalman filter will be respond for the changing a objects moving. Now deltaTime is constant for all objects trajectory. But you can change this parameter dynamically: if the objects speed is growing than deltaTime must be grow too. And vice versa.
