### ISSUE TITLE
How use of kcf？

### ISSUE THREAD

**Issue by bleakie** [Smorodov/Multitarget-tracker#89]
I had  installed opencv_contrib，but how could i use of it in code?

**Comment by Nuzhny007** [comment]
Hi!
It need to set USE_OCV_KCF option in CMake (in CMake gui or -DUSE_OCV_KCF=ON in terminal).

**Comment by bleakie** [comment]
Hi，I've already done that. Will he automatically use KCF when he runs the program? thank you very much!

**Comment by Nuzhny007** [comment]
It need to set option in CTracker constructor: https://github.com/Smorodov/Multitarget-tracker/blob/master/VideoExample.h#L461
And KCF will be used when there is no detect on the current frame for the object.
