### ISSUE TITLE
make_unique

### ISSUE THREAD

**Issue by NicolasMat** [Smorodov/Multitarget-tracker#9]
Hi Mr Smorodov
thanks for sharing your code
I use visual 2012
when I run the code I give an error "namespace std has no member make_unique".
it's in Ctracker.cpp
I searched on net and found pot that I should use visual 2014 for "make_unique"(if I'm not mistaken).
Is there any way that I can run the code in my visual 2012?
thank you in advance.

**Comment by Nuzhny007** [comment]
Hi!
It was my patch. You can use raw constructor of std::unique_ptr instead std::make_unique from C++14.
For example:
Current version:
`tracks.push_back(std::make_unique<CTrack>(d, dt, Accel_noise_mag));`
New version:
`tracks.push_back(std::unique_ptr<CTrack>(new CTrack(d, dt, Accel_noise_mag)));`

**Comment by Nuzhny007** [comment]
It will be a small overhead but nothing critical

**Comment by NicolasMat** [comment]
dear Nuzhny007
thanks for your reply
your suggestion was really helpful.
it's really a good code.
i want to use it for people counting.
i tried it on atrium.avi. the code count a person in some occasions more than 1 (when just a person is in the scene , counter shows 4 or ...). i thinks it's for background subtraction that split the  person forground.
i think if we make the background subtraction a bit better, the result will be better.

if two person cross each other, does the code find out and counter them as 2 person?

**Comment by Nuzhny007** [comment]
1. A background substrator now - Vibe algorithm from Bes: https://github.com/BelBES/VIBE
But in this project are old version of Vibe. Maybe Smorodov can integrate a new version of Vibe? In this case you can use some params:
`VIBE::VIBE(int channels, int samples, int pixel_neighbor, int distance_threshold, int matching_threshold, int update_factor)`
And it is hoped then you will improve detection.
Just now you can also change this params in function **libvibeModelNew()** but this way is not right.

2. You can filtering a small detections. In function **CDetector::DetectContour** you can use **cv::contourArea** or check bounding rectangle size before **Rects.push_back** call.

**Comment by NicolasMat** [comment]
thanks for your reply :)
