### ISSUE TITLE
Will KCF lost tracker method will achieve this?

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#90]
Hi I'm trying to implement a Abandoned Object detection

i could see with the background substraction detector the beggining of track when someone left a luggage. The track will remain there until the background Method learn that the luggage is part of the background. So my idea is begin a KCF automatically when the Background method begin to fail to follow this luggage. I don't know what happen but always finally the track is lost 
Do you know wich parameters I need to tune?? Will the KCF stays there forever (or until the luggage left...)

**Comment by Nuzhny007** [comment]
Hi!
Yes, the KCF tracker stays forever. And you can use it for Abandoned Object detection.
I think than you should not wait until the background model learn the luggage. It need to check the immobility on last N second and keep the object crop in this moment. If object will be moved than this crop will reset.

**Comment by Nuzhny007** [comment]
What dataset do you use for this task? I know any old datasets: PETS 2006 ( http://www.cvg.reading.ac.uk/PETS2006/data.html ) and PETS 2007 ( http://www.cvg.reading.ac.uk/PETS2007/data.html ) with abandoned luggage.

**Comment by Nuzhny007** [comment]
It need to make some changes in code. I'll try to do it in the nearest time.

**Comment by 88madri** [comment]
Hi. I could achieve by modifying the Max Trace Length Parameter to for example 1000 .
Then I Control the persistency of the track with IsRobust() with a minimal trajectory size (for example 100 ) . Then I have create another Track Object with The KCF and LastRect() (similar to CTrack).
Also I have a maxSkippedFrames parameter to control when the KCF fails repeatly to remove the Track from my structure.

I don't know why with your lost track implementation I cannot get the same results..  So I decided to put the lost track type to None and then follow this new architecture... Also with this I can control which Tracks I want to get follow.

One more thing... 
I have added a ROI Parameter to BaseDectector to mask the ROI of the Detector. Also I have a new kind of Detector, is simple is just a binary detector, It receives a Binary Mat, then find countors and is used as a Motion Detector. Do you want me to pull request this changes??

**Comment by Nuzhny007** [comment]
Hi!
What about pull request: You can create it. I'll finish coding my part in 1-2 days and we will compare approaches.

**Comment by Nuzhny007** [comment]
Hi!
I have implemented a simple Abandoned detector. Video is here: https://www.youtube.com/watch?v=fpkHRsFzspA
It seem that Smorodov can't right now merge my pull request. But all source code available on my fork for testing: https://github.com/Nuzhny007/Multitarget-tracker

And you can compare this implementation with 15 years old my Motion detector on same video: https://github.com/Nuzhny007/feintrack

**Comment by Nuzhny007** [comment]
Hi @la-tuna!
You can find they here: https://cloud.mail.ru/public/seiD/RhZXpyWWn
