### ISSUE TITLE
OpencL target is not supported 

### ISSUE THREAD

**Issue by scp-sjrim** [Smorodov/Multitarget-tracker#93]
Hello.

I have a problem about OpenCL.

I use Nvidia geforce gtx 1050.

I installed cuda but OpenCL doesn't work..

How can I fix it ?

[ INFO:1] Successfully initialized OpenCL cache directory: C:\Users\sjRim\AppData\Local\Temp\opencv\4.0.0-pre\opencl_cache\
[ INFO:1] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_1050--388_19
[ WARN:1] DNN: OpenCL target is not supported with current OpenCL device (tested with Intel GPUs only), switching to CPU.

**Comment by Nuzhny007** [comment]
Hi!
This question is for OpenCV developers. I have Ubuntu 16.04 and NVidia 1070 and all works well.
You can test this option with example from OpenCV repository: https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp
Set parameter --target=1

And You can test OpenCL examples from NVidia CUDA toolkit.

**Comment by henrique** [comment]
Try setting the environment variable OPENCV_DNN_OPENCL_ALLOW_ALL_DEVICES=1 
E.g. on linux shell: 
OPENCV_DNN_OPENCL_ALLOW_ALL_DEVICES=1 ./your_program
