### ISSUE TITLE
CaptureAndDetect: Tracking timeout!

### ISSUE THREAD

**Issue by dmaugis** [Smorodov/Multitarget-tracker#94]
Hi ! I try example 1, motion detection+tracking, but it seems I cannot get a reliable deterministic result: I almost always end up with "CaptureAndDetect: Tracking timeout!" at different frames in the video. Any idea what's going wrong ? Thanks.

./MultitargetTracker -e=1
OpenCL not used
Frame 1: tracks = 1, time = 5
...
Frame **109**: tracks = 31, time = 23
CaptureAndDetect: Tracking timeout!Process: Frame capture timeout
work time = 
0.930499

Frame **89**: tracks = 28, time = 21
CaptureAndDetect: Tracking timeout!Process: Frame capture timeout
work time = 
0.540753

Frame **141**: tracks = 45, time = 27
CaptureAndDetect: Tracking timeout!Process: Frame capture timeout
work time = 
1.85506

**Comment by Nuzhny007** [comment]
Hi!
I'll fix it only after my vacation, about 12 July

**Comment by dmaugis** [comment]
Have very very good hollidays.

**Comment by Nuzhny007** [comment]
Hi!
I'm increase Tracking and Capture timeouts in latest pull request. Pipeline works in 2 threads: Capture and Tracking. I think that it have not time for processing and ended with timeouts. If this solutions will don't woks then I will added advanced logs.

**Comment by dmaugis** [comment]
I will give it a try this week and keep you posted on the outcome - thanks :-)
