### ISSUE TITLE
Problem running the code

### ISSUE THREAD

**Issue by mash2612** [Smorodov/Multitarget-tracker#96]
Hello,
Thanks for the code. I am beginner and trying to run the code and I am encountering certain errors which I am not able to understand. I am attaching the image after I run the executable file in debug mode.
![image](https://user-images.githubusercontent.com/30777758/42263238-b2c1da84-7f6d-11e8-919b-fff9c4355986.png)
Can you tell me where am I possibly going wrong?

TIA :)

**Comment by Nuzhny007** [comment]
Hi!
I can't check it now but Yolo v3 support works with OpenCV 4.0. And You use 3.4.1

**Comment by mash2612** [comment]
hi,
Thanks for the input. I will trying changing this.

**Comment by Nuzhny007** [comment]
Hi!
I get the latest OpenCV version from master branch and compile it.

**Comment by mash2612** [comment]
Thank you I have done this successfully :)
