### ISSUE TITLE
Difference between Tracker Rectangle and raw detections

### ISSUE THREAD

**Issue by 88madri** [Smorodov/Multitarget-tracker#99]
Hi I don't know why its working like this.

![image](https://user-images.githubusercontent.com/17722229/42812365-b5a92ebe-89bd-11e8-97d8-2b2d7e1f7882.png)
![image](https://user-images.githubusercontent.com/17722229/42812400-cde5c60e-89bd-11e8-8d7d-d2c764046ee7.png)
![image](https://user-images.githubusercontent.com/17722229/42812424-df36b850-89bd-11e8-8239-c5e0fd8ef0a8.png)

These captures are showing the mog2 background substractor frame processed and the rectangles

The  green rectangles are the raw rectangles found by the function cv::findContours
and the blue rectangles are the ones the tracker are generating 
as you can see the tracker rectangles are smaller and centered in the topleft corner of the raw rectangle

Thanks

**Comment by Nuzhny007** [comment]
Hi!
Do you can to show settings for CTracker?

**Comment by 88madri** [comment]
Sure !!

Detector MOG2 CUDA version
Kalman Type : Lineal
Dist Type: Rect
Filter Goal Type: Rect
Math Type: Bipart
Use Local Tracker : false
Lost Track Type : None
Delta Time = 0.2
Accel Noise = 0.1
Distance Threshold : 15
Min Object 10

It's ok with that??

**Comment by Nuzhny007** [comment]
Mmm...
Try, plz, settings.m_filterGoal = tracking::FilterCenter
Maybe Kalman don't have time to adapt to the object resizing. Or you can increase delta time from 0.2 to 0.5

**Comment by 88madri** [comment]
Seems with increasing delta time it's working better.
I'm usually working with car detections.. sometimes with high speed , maybe you know better parameters

**Comment by Nuzhny007** [comment]
It seems to me that you need to use information about speed and perspective: closer to the camera the car will be bigger and move faster. I'll think about how you can use it ...

**Comment by Nuzhny007** [comment]
Hi!
I have added a new functionality for the Linear Kalman filter: https://github.com/Nuzhny007/Multitarget-tracker/blob/master/Tracker/Kalman.cpp#L691
It's an inertia correction: if the object moves faster then deltaTime in Transition matrix will be increased else decreased in interval [deltaTime, 2 * deltaTime].
After I did some tests on this dataset: https://medusa.fit.vutbr.cz/traffic/
For example: https://medusa.fit.vutbr.cz/traffic/data/2016-ITS-BrnoCompSpeed-video-previews/
The initial parameters: https://github.com/Nuzhny007/Multitarget-tracker/blob/master/VideoExample.h#L139
```
settings.m_dt = 0.4f;                             // Delta time for Kalman filter
settings.m_accelNoiseMag = 0.5f; // Accel noise magnitude for Kalman filter
```
Became better than before!
It will be great if you check on your video. And I suggest that you try to repeat all errors on videos from this open dataset. OK?

**Comment by Nuzhny007** [comment]
Hi!
This question is too hard for me. I updated my TODO list: https://github.com/Nuzhny007/Multitarget-tracker/blob/master/TODO
It seems that it can quite simply port deep sort from C++ repositories. But I have not any free time for it. But I can't say exactly.

**Comment by 88madri** [comment]
What is the difference between a good detector as YOLO v3 with a good tracker like KCF, Kalman or CSRT versus Deep Sort??
